new Mooc footer
CoorpAcademy/components pull request #1779
Opened 2020-08-25 15:51 UTC by StefanoA1

**Detailed purpose of the PR**

Adds a new organism "MoocFooter", modifies the atom "Social Link" (adds additional tests with the modification).

Trello card: https://trello.com/c/LyOY58Is/1836-modifier-le-footer-du-mooc

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [x] Manual testing
- [x] Unit testing

2020-08-25 15:51 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modifier le footer du MOOC](https://trello.com/c/LyOY58Is/1836-modifier-le-footer-du-mooc)

2020-08-26 12:15 UTC, jomaora approved these changes

2020-08-26 13:48 UTC, esa-coorp requested changes

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/social-link/index.js
> +  const {type, link, mode = 'default'} = props;
je veux bien que l'on regarde ....

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/social-link/style.css
> +  border-radius: 50%;
remonte le `border-radius` sur `defaultLink` il est dans `link` et `linkFooter`

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/social-link/style.css
> +  /* color: color(white lightness(60%)); */
supprime le commentaire

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/index.js
> +  const {headSection = {}, socialLinks = [], siteMapSections = []} = props;
je veux bien que l'on regarde ...

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/index.js
> +      <div className={style.line}> </div>
utilise un Pseudo-éléments `::after` pour cela

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/index.js
> +              <Link href={page.link} data-text={`${page.title} `} className={style.pageLink}>
```suggestion
              <Link href={page.link} title={page.title} data-text={page.title} className={style.pageLink}>
```

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/index.js
> +            <div className={style.sectionMobileDivisor} />
utilise un Pseudo-éléments ::after pour cela

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* margin-left: 225px; */
supprime les commentaires

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* max-width: 180px; */
idem

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* width: 444px; */
idem

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* compose: defaultText; */
idem

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* margin-left: 225px; */
idem

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  /* justify-content: space-between; */
idem

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +  .line {
utilise un pseudoElement pour faire une ligne

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +    width: 0px;
display: none ;-)

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/mooc-footer/style.css
> +    /* width: 250px; */
utilse un pseudoElement pour faire une ligne

2020-08-26 13:48 UTC, esa-coorp commented on packages/@coorpacademy-components/locales/en/global.json
> +  "something_went_wrong": "Oh Snap! Something went wrong.",
Pas besoin d'ajouter des locales, tu injectes tout en props

2020-08-27 09:08 UTC, esa-coorp approved these changes

2020-08-27 09:16 UTC, merged