Teams dashboard
CoorpAcademy/components pull request #1799
Opened 2020-10-06 14:51 UTC by StefanoA1

**Detailed purpose of the PR**

- Adds new component: template/teams-dashboard

- Updates mooc-header for the use case and adds (some)missing tests to get up coverage on the existing component

- Removes unused code from existing components, adds tests

  
**Result and observation**

![teams dashboard](https://user-images.githubusercontent.com/33550261/95221855-2ccf5080-07f8-11eb-938b-18096b0b6bfc.gif)

**Testing Strategy**

- [x] Already covered by tests
- [x] Manual testing
- [x] Unit testing

2020-10-07 15:06 UTC, silouone commented on packages/@coorpacademy-components/src/atom/cta/style.css
> +}
on evite les importants, pk tu a besoin d'en set ici ?

2020-10-07 15:13 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/cta/style.css
> +}
oui, je suis d'accord en eviter les importants, ce sont des classes du style sur le Cta exclusives pour le header teams, car le skin dans Cta prends prevalence (il devient orange car il est surchargé) sauf que sur le design il n'y a pas de specification pour prendre le skin sur le "bleu" standard, je vais ajouter un commentaire peut etre pour exprimer ça

2020-10-07 15:52 UTC, silouone commented on packages/@coorpacademy-components/src/atom/cta/style.css
> +}
car les deux classe son importé 🤔  jss pas assez à l'aise avec ce projet je vais gco la branche pour regarder ça

2020-10-07 15:55 UTC, silouone commented on packages/@coorpacademy-components/src/template/teams-dashboard/test/header.js
> +test('should render only empty TeamsHeader if no header props are pased', t => {
passed

2020-10-07 15:57 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/teams-dashboard/test/header.js
> +test('should render only empty TeamsHeader if no header props are pased', t => {
bien vu merci, je vais corriger ça

2020-10-07 16:12 UTC, silouone commented on packages/@coorpacademy-components/src/atom/cta/style.css
> +}
pk tu passes  
``` 
className === 'teamsHeader' ? style.teamsHeader : null,
className	         
```
 tu peux rebuild un set pour MSTeams et composer tes classes au besoin avec `compose`

on en reparle, demain je gco ce soir et je regarderai

2020-10-07 16:19 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/cta/style.css
> +}
je fais des modifs sur l’histoire du Cta / important, c'est plus direct maintenant et pas besoin du !important que j'avais mis, si tu peux re-regarder la diff de nouveau stp merci :+1:

2020-10-07 16:21 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> -const ContentTypeInfo = ({mode, adaptiv, type, externalContent}, context) => {
je n'ai pas vu que adaptiv était utilisé null part, donc je l'ai retiré

2020-10-08 07:57 UTC, DjamelSoualmi reviewed
Je préfère dire  microsoftTeams ou msTeams que Teams c'est plus précis

2020-10-08 07:57 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/teams-header/index.js
> +    srcMobile: PropTypes.string,
tu l'utilises dans ce composant ?

2020-10-08 08:04 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[TEAMS] build APP FRONT](https://trello.com/c/qvrXiBtI/884-teams-build-app-front)

2020-10-08 08:23 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/teams-header/index.js
> +    srcMobile: PropTypes.string,
le srcMobile? non pour l'instant mais j'avait gardé les props communes (comme logo) iso avec le mooc-header ou cas ou on aurait besoin mais oui c'est mieux de réduire le bruit sur le component

2020-10-08 09:09 UTC, esa-coorp requested changes

2020-10-08 09:09 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/teams-header/index.js
> +        <Link className={style.logoTeamsHeader} data-name="logo" href={logo.href}>
```suggestion
        logo.href?<Link className={style.logoTeamsHeader} data-name="logo" href={logo.href}><Picture src={logoUrl} /></Link>:<Picture src={logoUrl} />
```

2020-10-08 09:09 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/teams-header/style.css
> +  z-index: 10;
pourquoi?

2020-10-08 09:11 UTC, esa-coorp reviewed
tu n'as pas desactivé les favoris des cartes?

2020-10-08 12:36 UTC, StefanoA1 commented
> Je préfère dire microsoftTeams ou msTeams que Teams c'est plus précis

je viens d'effacer teams-header pour mettre les changements plutot sur mooc-header, avec des certaines updates pour faire un sort que ça marche sans avoir de breaking changes sur le style/logique

2020-10-08 12:40 UTC, StefanoA1 commented
> tu n'as pas desactivé les favoris des cartes?

pas encore, c'est à dire c'est géré, mais j'ai mis le motif dans la carte https://trello.com/c/c9GsrNLa/855-projet-teams sur TO DO: Teams Dashboard, j'ai parlé avec @godu sur ça :+1:

2020-10-08 13:41 UTC, esa-coorp approved these changes

2020-10-08 14:05 UTC, godu approved these changes

2020-10-08 15:12 UTC, silouone approved these changes

2020-10-08 15:13 UTC, merged