Adding data names
CoorpAcademy/components pull request #1808
Opened 2020-11-02 15:57 UTC by jomaora

**Detailed purpose of the PR**

Adding data-names related to this ticket = https://trello.com/c/JMmGLmvZ/1946-ajouter-des-datanames

2020-11-02 16:11 UTC, StefanoA1 approved these changes

2020-11-02 16:17 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/news/index.js
> +          <Cta {...cta} secondary name="news-cta" />
c'est data-name="news-cta" non !

2020-11-02 16:28 UTC, esa-coorp requested changes

2020-11-02 16:28 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/social-link/index.js
> +      data-name={`footer-${type}`}
```suggestion
      data-name={`${mode}-${type}`}
```

2020-11-02 17:02 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/news/index.js
> +          <Cta {...cta} secondary name="news-cta" />
non, le component Cta a une prop name qui est utilisée pour passer justement la valeur dans data-name https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/atom/cta/index.js#L118

2020-11-03 09:24 UTC, DjamelSoualmi approved these changes

2020-11-03 09:25 UTC, esa-coorp approved these changes

2020-11-03 09:30 UTC, merged