add teams popin
CoorpAcademy/components pull request #1813
Opened 2020-11-24 16:11 UTC by DjamelSoualmi

This pr adds new component, a Popin for Teams front
 
![image](https://user-images.githubusercontent.com/58167920/100120308-19477a00-2e78-11eb-86bc-b1ea695b8859.png)

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2020-11-25 15:19 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/wrong.js
> +    buttonLabel: 'Reload my dashboeard',
dashboard

2020-11-25 15:19 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +    case 'loginFaild':
failed

2020-11-25 16:08 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/wrong.js
> +    buttonLabel: 'Reload my dashboeard',
`header: 'Somthing went wrong',` pour `header: 'Something went wrong',`

2020-11-25 17:03 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +}
pas tres flex tout ca

2020-11-25 17:27 UTC, esa-coorp requested changes

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +  switch (type) {
j'aime pas trop le switch. je préfère une map d'icon:

https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/atom/social-link/index.js#L16

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +      return null;
impossible à tester :-)
type: PropTypes.oneOf(['reload', 'loginFailed', 'addressError', 'wrong'])

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +          <Icon type={type} />
const IconType = ICONS[type];
```suggestion
          <div className={style.iconContainer}>
               <IconType className={style.icon} />
          </div>
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +          <div className={style.content}>
```suggestion
          <p className={style.content}>{content}</p>
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  background-color: '#eceff1';
`@value light from colors;`
```suggestion
  background-color: light;
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  color: '#13171a';
`@value black from colors;`
```suggestion
  color: black;
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  color: '#13171a';
```suggestion
  color: black;
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  padding: 10px 30px 10px 30px;
```suggestion
  padding: 10px 30px;
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  color: rgba(247, 63, 82);
```suggestion
  color: negative;
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +  background-color: rgba(247, 63, 81, 0.05);
```suggestion
  background-color: color(negative a(5%));
```

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +            <div className={style.buttonContainer}>
tu devrais utiliser le composant `Cta`?

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +      <div className={style.disable}>
disable ???? étrange comme nom de classe

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +      <div className={style.disable}>
`style .background` plutôt ????

2020-11-25 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +    <div className={style.wrapmessage}>
```suggestion
    <div className={style.wrapMessage}>
```

2020-11-25 17:31 UTC, esa-coorp requested changes

2020-11-25 17:31 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +    <div className={style.wrapmessage}>
style.overlay ??? serait mieux et je pense que tu peux merger wrapMessage et disable en une seule div

2020-11-25 17:33 UTC, esa-coorp reviewed
@DjamelSoualmi tu n'as pas une couverture à 100%

2020-11-26 10:23 UTC, esa-coorp requested changes

2020-11-26 10:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/index.js
> +            <button className={style.button} type="button" onClick={onButtonClick}>
utilise le composant `cta`

2020-11-26 10:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/teams-popin/style.css
> +.button {
style deja gérer par le composant cta

2020-11-26 11:28 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/wrong.js
> +    header: 'Somthing went wrong',
something

2020-11-26 11:29 UTC, silouone commented
@DjamelSoualmi vu que t'a un point avec audric en début d'aprem tu peux directement lui demander le design du login ? et integrer la fixtures. C'est le mm rendu normalement, à voir ce qu'il te propose en icon. 

ℹ️  Il faut aussi lui parler du changement d'icon qu'il avait prévu sur une des tabs

2020-11-26 16:02 UTC, esa-coorp approved these changes

2020-11-26 16:24 UTC, StefanoA1 approved these changes

2020-11-27 09:31 UTC, silouone approved these changes

2020-11-30 16:51 UTC, StefanoA1 approved these changes

2020-12-01 09:04 UTC, esa-coorp approved these changes

2020-12-01 09:07 UTC, merged