Create cockpit video translation popin
CoorpAcademy/components pull request #1827
Opened 2021-01-14 07:33 UTC by DjamelSoualmi

[Ticket](https://trello.com/c/WwwgTNzA)
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/58167920/104558428-10d31a80-5643-11eb-9097-da051b0650da.png">

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-01-14 17:16 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
> +                style={{backgroundColor: '#FFFFFF', color: '#546e7a'}}
utilise les couleurs de coorp, y'a un white  et l'autre si c'est cockpit color et que ca n'existe pas il faut peut être l'ajouter

2021-01-15 10:02 UTC, esa-coorp requested changes

2021-01-15 10:02 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
> +                style={{
ajoute cela au style `style.button`

2021-01-15 10:02 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
> +                style={{
backgroundColor: 'white',
color: 'gray' // utilise une couleur de la palette

2021-01-15 10:02 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
> +  width: 35%;
j'ajouterais en plus un min-width

2021-01-15 10:02 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
> +  background-color: #fafafa;
utilise une couleur de la palette

2021-01-15 14:16 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
> +                style={{
je peux pas faire ça parce que le composant button surcharge les props [ici](https://github.com/CoorpAcademy/components/blob/cockpit-popin/packages/@coorpacademy-components/src/atom/button/index.js/#L97-L102)

2021-01-15 14:24 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
> +                style={{
👍

2021-01-18 09:17 UTC, StefanoA1 approved these changes

2021-01-18 09:28 UTC, esa-coorp requested changes

2021-01-18 09:28 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
> +  max-width: 600px;
il manque un min-width ....

2021-01-18 09:28 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
> +  background-color: whitesmoke;
c'est quoi cette couleur. c'est pas dans la palette ....

2021-01-18 09:32 UTC, silouone approved these changes
moyennant les derniers retours d'eric, lgtm

2021-01-18 09:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
> +  background-color: whitesmoke;
utilise `lightGrey` 
https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/variables/colors.css#L12

2021-01-18 10:50 UTC, esa-coorp approved these changes

2021-01-18 11:05 UTC, merged