adds info icon
CoorpAcademy/components pull request #1837
Opened 2021-02-10 17:38 UTC by StefanoA1

**Detailed purpose of the PR**

adds info icon
<img width="497" alt="Screenshot 2021-02-10 at 18 33 20" src="https://user-images.githubusercontent.com/33550261/107548621-2c442d80-6bcf-11eb-9984-2afc62dc6fb8.png">

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-02-10 17:39 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Lists sendinblue] Mooc, ajout toogle subscribe/unsubscribe marketing list dans page account](https://trello.com/c/pgXKuaWk/2035-lists-sendinblue-mooc-ajout-toogle-subscribe-unsubscribe-marketing-list-dans-page-account)

2021-02-10 18:12 UTC, esa-coorp requested changes

2021-02-10 18:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/index.js
> +      <InfoIcon height={16} className={style.infoIcon} />
il ne faut pas ajouter de picto s'il n'y a pas de description

2021-02-10 18:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  padding-right: 17px;
cursor: pointer

2021-02-10 18:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  max-width: 185x;
qu'est ce qui se passe si le tooltip est sur plusieurs ligne ça pousse tout vers le bas. Il devrait pas être en absolute

2021-02-11 11:23 UTC, esa-coorp requested changes

2021-02-11 11:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  visibility: hidden;
utilise les pseudo-élément pour faire ton triangle

https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/template/activity/engine-stars.css#L194

2021-02-11 11:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  text-align: center;
je pense que ton `showToolTip` doit être en position absolue

2021-02-11 11:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/index.js
> +          <span className={style.triangle}> </span>
```suggestion
```

2021-02-11 11:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/index.js
> +          <InfoIcon height={16} className={style.infoIcon} />
```suggestion
          <InfoIcon height={16} width={16} className={style.infoIcon} />
```

2021-02-11 11:24 UTC, esa-coorp reviewed
n'oubliez pas de tester sur ie

2021-02-11 12:01 UTC, StefanoA1 commented
> n'oubliez pas de tester sur ie

@esa-coorp j'ai ce rendu sur ie: 
![VirtualBox_IE11 - Win7_11_02_2021_12_58_44](https://user-images.githubusercontent.com/33550261/107634017-33b81500-6c69-11eb-8c1f-182cc04d4d57.png)

j'ai pas trouvé le pourquoi du spacing encore

2021-02-11 13:54 UTC, silouone commented
@StefanoA1 regarde les pb de `proportionnal aspect ratio` avec les svg sur IE sur google. 

 J'avais rencontré un pb comme ça côté mooc au tt début de coorp. Un truc du genre il faut pas leur passer height & width en mm temps. jsais pas si ca va tout fixer mais C'est une piste 😉

2021-02-11 14:43 UTC, DjamelSoualmi approved these changes

2021-02-11 15:04 UTC, esa-coorp requested changes

2021-02-11 15:04 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  z-index: 1;
```suggestion
```

2021-02-11 15:04 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/user-preferences/style.css
> +  max-height: 4.2em;
```suggestion
```

2021-02-11 16:40 UTC, esa-coorp approved these changes

2021-02-11 17:16 UTC, merged