Add coorplogo on download the app page + colour injection revamp
CoorpAcademy/components pull request #1845
Opened 2021-03-01 16:38 UTC by StefanoA1

**Detailed purpose of the PR**
- Adds coorplogo on download the app page + colour injection revamp

**Result and observation**

![Screenshot 2021-03-01 at 17 37 43](https://user-images.githubusercontent.com/33550261/109528376-e33c1680-7ab4-11eb-8872-bf4b2d7db9a4.png)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-03-01 16:41 UTC, StefanoA1 commented on packages/@coorpacademy-nova-icons/scripts/generate-icons.js
> +const isFillAttribute = ({name: {name}, value: {value} = {}}: JSXAttribute): boolean => name === 'fill' && value === '#757575';
avant le generate-icons ne gardé pas les autres couleurs, maintenant il remplace #757575 par currentColor et le reste il les laisse -as is- pour plus de simplicité

2021-03-01 16:50 UTC, StefanoA1 commented on packages/@coorpacademy-nova-icons/scripts/generate-icons.js
> +  name === 'fill' && value === '#757575';
avant le generate-icons ne gardé pas les autres couleurs, maintenant il remplace #757575 par currentColor et le reste il les laisse -as is- pour plus de simplicité

2021-03-01 16:54 UTC, jomaora approved these changes

2021-03-02 11:09 UTC, StefanoA1 commented on packages/@coorpacademy-nova-icons/scripts/generate-icons.js
> +  name === 'stroke' && value === '#757575';
idem que pour isFillAttribute

2021-03-02 11:12 UTC, esa-coorp requested changes

2021-03-02 11:12 UTC, esa-coorp commented on packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-failed.js
> +        ".prefix__st1{fill:none;stroke:currentColor;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10}"
il ya un pb là?

2021-03-02 12:25 UTC, StefanoA1 commented on packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-failed.js
> +        ".prefix__st1{fill:none;stroke:currentColor;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10}"
Non, cette modif c'est prevue, ça était pas géré avant, c'est le seul edge case non-géré pour des inline props (que restent dans le AST comme props et pas comme des attributes) donc le seul js icon qu’a changé (apart coor-app) c’était le login-failed.js, car meme avant il n’était pas bien pris en compte, j'ai testé le rendu sur TeamsPopin et c'est correct 
![Screenshot 2021-03-02 at 13 24 30](https://user-images.githubusercontent.com/33550261/109648226-ab87aa00-7b5a-11eb-9a27-dc4a55ed45f2.png)

2021-03-02 12:53 UTC, esa-coorp approved these changes

2021-03-02 12:59 UTC, merged

2021-03-02 14:46 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter le logo coorpacademy dans la page "télécharger l'app"](https://trello.com/c/bh0VnWBT/2015-ajouter-le-logo-coorpacademy-dans-la-page-t%C3%A9l%C3%A9charger-lapp)