add add to my list button
CoorpAcademy/components pull request #1880
Opened 2021-05-20 08:13 UTC by DjamelSoualmi

**Web**

![image](https://user-images.githubusercontent.com/58167920/118943058-93524a80-b953-11eb-9ed1-f40c5226cfb8.png)

Add "add to my list" action to discipline page
[Ticket](https://trello.com/c/jr3pblRw)
**Hover**

![image](https://user-images.githubusercontent.com/58167920/118943185-ae24bf00-b953-11eb-8854-c871adf58769.png)

**Clicked**

![image](https://user-images.githubusercontent.com/58167920/118943325-cd235100-b953-11eb-8dba-51a838f0248c.png)

**Mobile** 
![image](https://user-images.githubusercontent.com/58167920/118942817-5b4b0780-b953-11eb-8fa9-92cbc215830d.png)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-05-21 08:38 UTC, esa-coorp requested changes

2021-05-21 08:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/forum/forum-thread/index.js
> +    <ForumThread {...answerProps} key={answerProps.id + index} />
pourquoi? l'id du post est bien unique coté mooc.

2021-05-21 08:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/share/index.js
> +      <div className={styles.container}>
pour quoi ajouter une div de plus
```suggestion
      <div className={classNames(style, styles.container)}>
```

2021-05-21 08:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/common/discipline/index.js
> +        <div>
cette `div` ne sert à rien

2021-05-21 08:46 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/forum/forum-thread/index.js
> +    <ForumThread {...answerProps} key={answerProps.id + index} />
on a eu des soucis dans les testes !

2021-05-26 09:03 UTC, silouone approved these changes

2021-05-26 09:35 UTC, merged