fix: remove child from parent rather than removing the child itself cuz IE11 :)
CoorpAcademy/components pull request #1892
Opened 2021-06-07 12:20 UTC by Fausto95

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-06-07 12:31 UTC, DjamelSoualmi approved these changes

2021-06-07 16:10 UTC, esa-coorp requested changes

2021-06-07 16:10 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/share/index.js
> +  textarea.style.margin = '0 auto';
pas besoin surtout si c'est en display: none
```suggestion
```

2021-06-07 16:10 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/share/index.js
> +  textarea.style.textAlign = 'center';
idem
```suggestion
```

2021-06-09 09:09 UTC, esa-coorp approved these changes

2021-06-09 09:09 UTC, merged