[Teams] Dashboard Header - mobile support
CoorpAcademy/components pull request #1921
Opened 2021-07-28 17:46 UTC by StefanoA1

**Detailed purpose of the PR**

**Result and observation**
![Kapture 2021-07-28 at 19 32 59](https://user-images.githubusercontent.com/33550261/127371214-a959303a-7c11-4416-9189-9201b95abe38.gif)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-07-28 17:47 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Teams Dashboard Header - mobile support](https://trello.com/c/q0ZENZMx/233-teams-dashboard-header-mobile-support)

2021-07-29 10:14 UTC, godu requested changes

2021-07-29 10:14 UTC, godu commented on packages/@coorpacademy-components/src/template/teams-dashboard/index.js
> +        // eslint-disable-next-line react/jsx-no-bind
Ah non, on laisse pas des `eslint-disable-next-line` comme ça.

2021-07-29 10:25 UTC, godu requested changes

2021-07-29 10:25 UTC, godu commented on packages/@coorpacademy-components/src/template/teams-dashboard/index.js
> +  const onMenuOpen = () => setShadowed(true);
```suggestion
  const onMenuOpen = useCallback(() => setShadowed(true));
```

2021-07-29 10:25 UTC, godu commented on packages/@coorpacademy-components/src/template/teams-dashboard/index.js
> +  const onMenuClose = () => setShadowed(false);
```suggestion
  const onMenuClose = useCallback(() => setShadowed(false));
```

2021-07-29 11:02 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/teams-dashboard/index.js
> +  const onMenuOpen = () => setShadowed(true);
done 👍

2021-07-29 14:11 UTC, StefanoA1 commented
OBS: a refactor for the mooc's header usage will be needed in the main mooc repo

2021-07-30 08:18 UTC, silouone approved these changes
lgtm, Tu deploy ca cote teams en staging quand c'est mergé qu'on verifie le rendu in app et les potentiels regression ?

J'ai proposé de bump canary à stefano s'il il est pas serein sur la non présence de regression mooc/teams 😉

2021-07-30 11:31 UTC, godu requested changes

2021-07-30 11:31 UTC, godu commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +      prevState.isMenuOpen ? this.handleOnMenuClose() : this.handleOnMenuOpen();
Tu n'as pas le droit de faire ça dans un `setState`

2021-07-30 11:47 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +      prevState.isMenuOpen ? this.handleOnMenuClose() : this.handleOnMenuOpen();
done 👍

2021-08-02 08:17 UTC, godu approved these changes

2021-08-02 08:20 UTC, merged