Quickaccess dashboard
CoorpAcademy/components pull request #1967
Opened 2021-10-11 09:57 UTC by jomaora

**Detailed purpose of the PR**

This PR integrates the cards into the brand-dashboard organism and the brand update template.

**Result and observation**

## Brand-dashboard organism

### Desktop
<img width="1145" alt="Capture d’écran 2021-10-11 à 16 33 09" src="https://user-images.githubusercontent.com/7602475/136808316-2b9ac3b5-15d3-4091-b7c6-87e24bea3e9e.png">

### Tablet
<img width="811" alt="Capture d’écran 2021-10-11 à 16 33 19" src="https://user-images.githubusercontent.com/7602475/136808324-be37a5f2-d13f-4f06-b660-cbd7e503d513.png">

### avec 3 cards
<img width="1146" alt="Capture d’écran 2021-10-11 à 16 40 57" src="https://user-images.githubusercontent.com/7602475/136809525-e700c66e-3d8e-4d99-96f0-e2d243b8f2e7.png">

## Cards on template

![Kapture 2021-10-11 at 16 25 24](https://user-images.githubusercontent.com/7602475/136807736-8e0df886-5afb-4471-8252-4294a77efebe.gif)

**Testing Strategy**

- Already covered by tests
- Manual testing
- Unit testing

2021-10-11 17:27 UTC, esa-coorp requested changes

2021-10-11 17:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/quick-access-cards-group/style.css
> +  margin-right: 16px;
plus besoin???

2021-10-12 07:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/quick-access-cards-group/style.css
> +  margin-right: 16px;
je pense que tu n'as plus besoin de `.group > *:not(:last-child)`

2021-10-12 08:27 UTC, Fausto95 approved these changes

2021-10-12 08:34 UTC, merged