Wizard summary - WEB
CoorpAcademy/components pull request #1992
Opened 2021-11-02 16:37 UTC by jomaora

https://trello.com/c/WKiCLEWJ/2360-molecule-summary

**Detailed purpose of the PR**

Add web component with summary information to be used on wizard process on Coorpmanager

**Result and observation**

![Kapture 2021-11-02 at 17 33 02](https://user-images.githubusercontent.com/7602475/139906959-f52772e5-bd02-45be-be3b-5fd6a5361dea.gif)

**Testing Strategy**

- Manual testing
- Unit testing

2021-11-03 08:52 UTC, esa-coorp requested changes

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +                <span className={style.contentTitle}>{item.title}</span>
Pour avoir un tooltip (vu qu'il y a un ellipsis)
```suggestion
                <span className={style.contentTitle} title={item.title}>{item.title}</span>
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +                <span className={style.contentTitle}>{item.title}</span>
le titre d'un cours peux être en html (cours en arabe alignement à droite)

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  max-height: 586px;
Etrange ce max-height. A quoi sert'il?

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  padding-top: 40px;
```suggestion
  padding: 40px 37px 32px 37px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  overflow-y: auto;
```suggestion
  overflow: hidden auto;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  height: 458px;
tjrs étrange ....

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  overflow-y: auto;
```suggestion
  overflow: hidden auto;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-top: 24px;
```suggestion
  margin: 24px 0px 0px 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-top: 32px;
```suggestion
  margin: 32px 0px 0px 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-top: 0px;
```suggestion
  margin: 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-top: 8px;
```suggestion
  margin: 8px 0px 0px 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-top: 8px;
```suggestion
  margin: 8px 0px 0px 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
> +  margin-right: 4px;
```suggestion
  margin: 0px 4px 0px 0px;
```

2021-11-03 08:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/wizard-summary/test/fixtures/default.js
> +            title: 'Learn Everywhere #10 : Inclusion, Diversité, et autre élements importants',
```suggestion
            title: 'Learn <b>Everywhere #10</b> : <u>Inclusion, Diversité</u>, et autre élements importants',
```

2021-11-03 09:23 UTC, DjamelSoualmi requested changes

2021-11-03 09:23 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +        );
ça parle pas trop le type mainElement ! 
pour les keys tu peux mettre plus de détails stp ? ( pour la RGAA)

2021-11-03 09:23 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +                    category === 'podcast' && style.podcast
```suggestion
                    style[category]
```
à testé ..

2021-11-03 13:23 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +                    category === 'podcast' && style.podcast
@DjamelSoualmi ce type de syntaxe génère des erreurs lint car les styles définies dans le css ne sont pas "accessible" via le linteur css et on a des message comme quoi ces styles sont définis dans le css mais pas utilisés dans le fichier.

2021-11-03 13:46 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +        );
key={`${item.title}-${index}`}

2021-11-03 16:35 UTC, esa-coorp approved these changes

2021-11-04 09:09 UTC, Fausto95 approved these changes

2021-11-04 09:09 UTC, DjamelSoualmi approved these changes

2021-11-04 09:10 UTC, merged