add info / error banner
CoorpAcademy/components pull request #1995
Opened 2021-11-03 15:25 UTC by DjamelSoualmi

[ticket](https://trello.com/c/FMP2VyMl/2365-banni%C3%A8res-dinfo-et-derreur)
Information banner:
![image](https://user-images.githubusercontent.com/58167920/140090155-e28852d7-4472-4a6d-8494-6de7f2c1911a.png)

Error banner 
![image](https://user-images.githubusercontent.com/58167920/140090244-aac8a73a-09bf-44c7-851e-915bc75ab15c.png)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-03 15:33 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/banner/index.js
> +  secondeCTALabel: PropTypes.string,
second

2021-11-03 15:37 UTC, jomaora requested changes

2021-11-03 15:37 UTC, jomaora commented on packages/@coorpacademy-components/src/variables/colors.css
> +@value cm_negative_50: #ffe5e6;
tu peux le mettre dans l'ordre, stp

2021-11-03 15:37 UTC, jomaora commented on packages/@coorpacademy-components/src/variables/colors.css
> +@value cm_warning_50: rgba(255, 192, 67, 0.13);;
pareil

2021-11-03 15:37 UTC, jomaora commented on packages/@coorpacademy-components/src/variables/colors.css
>  @value cm_green_50: #e8fcf8;
profiter pour trier ça

2021-11-03 16:09 UTC, jomaora approved these changes

2021-11-04 07:46 UTC, esa-coorp requested changes

2021-11-04 07:46 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/banner/style.css
> +    composes: banner;
pas besoin
`className={classnames(style.banner, type === 'error' && style.errorBanner)}>`
```suggestion
```

2021-11-04 08:46 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/banner/style.css
> +    composes: banner;
aah yes , bien vu

2021-11-04 11:05 UTC, esa-coorp approved these changes

2021-11-04 14:20 UTC, merged