Cm popin
CoorpAcademy/components pull request #2000
Opened 2021-11-08 13:55 UTC by DjamelSoualmi

[Ticket](https://trello.com/c/4HV5GP9L)
Coorpmanager popin 

![cm-popin](https://user-images.githubusercontent.com/58167920/140754190-c21c02bb-b54f-4356-b406-bbc57a2a8ddf.gif)
e of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-08 14:38 UTC, esa-coorp requested changes

2021-11-08 14:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  font-family: Open Sans, sans-serif;
on est sûr?

2021-11-08 14:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  background-size: 'cover';
```suggestion
```
ca ne sert pas

2021-11-08 14:38 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +CMPopin.propTypes = {
```
CMPopin.propTypes = {
  content: PropTypes.string,
  buttons: PropTypes.arrayOf(
    PropTypes.shape({
      label: PropTypes.string,
      onClick: PropTypes.func,
      type: PropTypes.oneOf(['warning', 'warningWithClose', 'dangerous', default])
    })
   ),
   onClose: PropTypes.func,
   icon: PropTypes.string
};
```

2021-11-08 14:43 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +CMPopin.propTypes = {
il n’y a que deux button pour quoi je mis un tableau ? 
le type concerne les buttons et l'icon et pas seulement les buttons

2021-11-08 15:30 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +CMPopin.propTypes = {
c'est mieux on voit tout de suite les informations liés au bouton (label, onclick, style, ...)
le style par défaut c'est le bouton gris.

2021-11-08 16:32 UTC, jomaora approved these changes

2021-11-09 08:56 UTC, silouone approved these changes

2021-11-09 09:40 UTC, esa-coorp approved these changes

2021-11-09 09:58 UTC, merged