CM Input Search
CoorpAcademy/components pull request #2001
Opened 2021-11-08 15:38 UTC by Fausto95

<img width="480" alt="Capture d’écran 2021-11-08 à 16 23 35" src="https://user-images.githubusercontent.com/23306911/140769977-2577f862-11fa-4385-8617-ecdd2f894030.png">

### Notes

This component is heavily inspired by the input-text with CM theme(the css copy-pasted with some tweaks), therefore why did I create a new component instead of using the existing you'd ask. 
Well, The Input-text component is getting hefty and unreadable(even the css file) with all the overload, so making this it's own component it's more maintainable.

2021-11-08 16:27 UTC, jomaora approved these changes

2021-11-09 14:21 UTC, jomaora requested changes
@Fausto95 est-ce que tu peux renommer le fichier sans le cm-, stp

2021-11-10 11:27 UTC, esa-coorp requested changes

2021-11-10 11:27 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/cm-input-search/index.js
> +        {value ? <CloseIcon className={style.rightIcon} /> : null}
il manque un onclick sur la croix pour pouvoir clear le input
attention ne pas oublier le `cursor: pointer;`

2021-11-15 10:42 UTC, esa-coorp requested changes

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +          <SearchIcon color={dark} className={style.searchIcon} />
pourquoi ne pas mettre la couleur coté css dans . searchIcon?

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +        placeholder={placeholder}
pas de besoin

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +            {placeholder}
```suggestion
            {label}
```

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +        onChange={noop}
Etrange ....

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/style.css
> +  color: medium;
display: none;

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/style.css
> +.coorpmanager:focus-within .search::placeholder {
```suggestion

```

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/style.css
> +.coorpmanager .search::placeholder {
```suggestion
```

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/style.css
> +  .search::placeholder {
```suggestion
```

2021-11-15 10:42 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/style.css
> +  .search::placeholder {
```suggestion
```

2021-11-15 11:00 UTC, DjamelSoualmi requested changes

2021-11-15 11:00 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +      <label htmlFor="search">
dans ce cas un `title` est indispensable (" search course ")
```suggestion
      <label htmlFor="search" title={searchButtonTitleRgaa...}>
```

2021-11-15 13:40 UTC, esa-coorp approved these changes

2021-11-15 13:40 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-search/index.js
> +      <label htmlFor="search">
👍

2021-11-15 14:24 UTC, DjamelSoualmi approved these changes

2021-11-15 14:25 UTC, merged