Update wizard summary - user ButtonLink atom
CoorpAcademy/components pull request #2009
Opened 2021-11-15 14:34 UTC by jomaora

https://trello.com/c/XHWc9gVm/2384-button-link

**Detailed purpose of the PR**

Replace Link by ButtonLink component
Also the link click zone was restricted only to the div (before the click zone was to 100% width, so outside the text)

**Testing Strategy**

- Already covered by tests
- Manual testing

2021-11-15 15:48 UTC, DjamelSoualmi requested changes

2021-11-15 15:48 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +    </div>
```suggestion
      <ButtonLink {...buttonProps} />
```

2021-11-15 15:48 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
> +  };
le title rgaa !!

2021-11-15 16:43 UTC, DjamelSoualmi approved these changes

2021-11-16 09:19 UTC, esa-coorp approved these changes

2021-11-16 09:39 UTC, merged