Translation organisme
CoorpAcademy/components pull request #2010
Opened 2021-11-15 15:41 UTC by DjamelSoualmi

[Ticket](https://trello.com/c/9hO068sy)
![trans-org](https://user-images.githubusercontent.com/58167920/141810465-bdedafe8-24f2-49a5-b015-bf917d436037.gif)

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-16 14:33 UTC, esa-coorp approved these changes

2021-11-16 14:58 UTC, jomaora requested changes

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +  analytics: AnalyticsIcon,
tu peux garder l'ordre alphabetique stp

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +  background: transparent;
```css
.textNegative {
   composes: text;
   color: cm_negative_100;
}
```

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/input-text/index.js
> +        wrapperStyle
il n'y a pas d'autre façon de faire que de passer à un component une css qu'il n'a pas ? je trouve ça bizarre et surtout que aucune fixture de cet atom ne rend compte de cette situation. cc @esa-coorp

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/input-textarea/index.js
> +    <div className={classnames(mainClass, className, disabled && style.disabled, wrapperStyle)}>
pareil

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +function PlayListTranslation(props) {
Arrow function syntax

`const PlayListTranslation = props => {`

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +  deleteIcon: DeleteIcon
pas de Icon dans le suffix, stp

```json
{
    add: AddIcon,
    trash/bin: Trash[Bin]Icon
}

2021-11-16 14:58 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +  NovaSolidContentEditionBin as DeleteIcon
BinIcon

2021-11-16 15:55 UTC, esa-coorp requested changes

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +  deleteIcon: DeleteIcon
👍

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/input-text/index.js
> +        wrapperStyle
bonne remarque. @DjamelSoualmi pourquoi as tu besoin de cela?

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  width: 100%;
est que ça ne doit pas être mis directement dans le composant text-area?

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  width: 100%;
est que ça ne doit pas être mis directement dans le composant text-input?

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  width: 100%;
idem

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +        <TextArea {...textArea} wrapperStyle={style.description} theme={'coorpmanager'} />
est ce que `coorpmanager` ne doit pas etre dans props `textArea`?

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +        <InputText {...inputText} wrapperStyle={style.nameWrapper} theme={'coorpmanager'} />
idem

2021-11-16 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +        <TextArea {...textArea} wrapperStyle={style.description} theme={'coorpmanager'} />
on doit pouvoir faire sans wrapperStyle={style.description}

2021-11-17 11:21 UTC, esa-coorp requested changes

2021-11-17 11:21 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +  color: cm_negative_100;
@jomaora @DjamelSoualmi on a pas dit que pour le bouton de type text on passait en inherit et que c'était le parent qui donnait la couleur?

2021-11-17 11:21 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +            type={cta.type === 'delete' ? 'text-negative' : 'primary'}
```suggestion
            type={cta.type === 'delete' ? 'text' : 'primary'}
```

2021-11-17 15:02 UTC, esa-coorp requested changes

2021-11-17 17:14 UTC, jomaora requested changes

2021-11-17 17:14 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +        <TextArea {...textArea} />
Il y a 16 px entre ces deux éléments selon la maquette.

![Capture d’écran 2021-11-17 à 18 10 44](https://user-images.githubusercontent.com/7602475/142248878-57d34b07-ab6f-4987-b59c-d73c08dbcb54.png)

Ils sont pas présents.
<img width="658" alt="Capture d’écran 2021-11-17 à 18 11 04" src="https://user-images.githubusercontent.com/7602475/142248883-dbb3bf2a-9b73-4c47-8200-8fdaf0afbedc.png">

2021-11-18 09:36 UTC, jomaora requested changes

2021-11-18 09:36 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  gap: 16px;
utilise margin

2021-11-18 09:36 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/playlist-translation/index.js
> +      <div className={style.inputs}>
le gap ici doit s'appliquer aux inputs, mais pas au bouton qu'ils sont une margin de 32 avec le textarea

2021-11-18 10:40 UTC, jomaora approved these changes

2021-11-18 11:00 UTC, merged