Refactor: Select Multiple to FC with Hooks
CoorpAcademy/components pull request #2014
Opened 2021-11-16 11:02 UTC by Fausto95

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-16 14:07 UTC, DjamelSoualmi approved these changes

2021-11-16 14:28 UTC, esa-coorp approved these changes

2021-11-16 15:57 UTC, esa-coorp requested changes

2021-11-16 15:57 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/test/index.js
> -test('should open and close list', t => {
Pourquoi tu supprimes ces tests

2021-11-17 10:40 UTC, esa-coorp approved these changes

2021-11-17 13:57 UTC, merged