use new button in cm banner
CoorpAcademy/components pull request #2016
Opened 2021-11-16 13:43 UTC by DjamelSoualmi

![image](https://user-images.githubusercontent.com/58167920/141996341-10cfe3e8-deee-4a7a-bf53-e21705d9b9e2.png)
**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-16 14:02 UTC, Fausto95 approved these changes

2021-11-16 14:15 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [[atom] Button link > ajouter icon edition](https://trello.com/c/cKBkJ21G/400-atom-button-link-ajouter-icon-edition)

2021-11-16 14:36 UTC, esa-coorp requested changes

2021-11-16 14:36 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/banner/style.css
> +.button button{
je suis pas d'accord. Tu dois lui passer un type à ton bouton c'est lui qui décide de sa couleur

2021-11-16 14:36 UTC, jomaora approved these changes

2021-11-17 13:36 UTC, jomaora approved these changes

2021-11-17 14:23 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/banner/style.css
> +.button{
```
.button{
  background-color: transparent;
  color: cm_yellow_200;
}
```

2021-11-17 14:27 UTC, esa-coorp approved these changes

2021-11-17 14:46 UTC, merged