BulletPointMenuButton
CoorpAcademy/components pull request #2018
Opened 2021-11-16 14:57 UTC by StefanoA1

**Detailed purpose of the PR**
- Adds bullet point icon to button link & adds css for popupmenu buttons, creates BulletPointMenuButton component

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-16 15:11 UTC, silouone commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +.secondaryFlatDelete {
la culeur rouge du bouton s'apelle dangerous dans le cas avec border radius autant reutiliser le mm naming ?

2021-11-16 15:15 UTC, silouone commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +.secondaryFlatDelete {
ah cetait le background mais bon delete me parait trop précis. dangerousText ? 🤔

2021-11-16 15:16 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +.secondaryFlatDelete {
@silouone pour la couleur du texte? j'ai vu que dangerous était utilisé pour le background

2021-11-17 17:04 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/button-link/test/button-link.js
> +});
missing test

2021-11-17 17:43 UTC, jomaora requested changes

2021-11-17 17:43 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +    size: PropTypes.number
pas d'accord, la taille des icon est fixe sur les specs, je ne vois pas dans quel cas on aurait à la modifier

2021-11-17 17:43 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-tertiary-icon-bullet.js
> +      size: 14
je comprends que pour le button avec un seul icon on ait besoin de cette taille... ce n'est pas possible de le faire avec une css plutôt qu'avec des props (comme on évite qu'ont mette n'importe quel chiffre ici)...

Il y a un autre solution... Les specs viennent de changer à nouveau concernant le bouton Icon Only... maintenant on a deux types de bouton, `default` et `small`. Voir ici --> https://zpl.io/2pqkn8r

Je ne sais pas si le mieux c'est de refaire un atom juste pour ce button, ou revoir les props de l'existant (mais ajouter une prop size, alors qu'elle ne s'applique qu'aux buttons icon only me parait pas bien). Autant avoir deux components comme dans les specs. cc @esa-coorp .

Dispo pour en discuter.

2021-11-18 08:12 UTC, esa-coorp requested changes

2021-11-18 08:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +    size: PropTypes.number
👍

2021-11-18 08:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/index.js
> +    type: PropTypes.oneOf([
```suggestion
    type: PropTypes.oneOf(keys(ICONS)),
```

2021-11-18 08:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +  user-select: none;
👍

2021-11-18 08:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +    isFirst && style.firstButton,
tu peux le gérer en CSS idem pour le last

2021-11-18 08:12 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +    <button
pourquoi on utilise pas le buttonLink?

2021-11-18 09:26 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +    <button
comme on l'a vu ensemble, dans zeplin c'est pas un Button.

2021-11-18 09:54 UTC, esa-coorp approved these changes

2021-11-18 09:54 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +    <button
👍

2021-11-18 10:35 UTC, jomaora requested changes

2021-11-18 10:35 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +  const buttonList = useCallback(map.convert({cap: false})(buildButton, buttons), [
useMemo

2021-11-18 10:35 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/button-menu/index.js
> +    type === 'secondary' && style.secondary,
default

2021-11-18 10:52 UTC, jomaora approved these changes

2021-11-18 11:33 UTC, merged

2021-11-18 11:34 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [molecule bullet point CM](https://trello.com/c/Im5qFqUn/394-molecule-bullet-point-cm)