Button icon only
CoorpAcademy/components pull request #2023
Opened 2021-11-18 14:22 UTC by jomaora

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-18 15:50 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/test/fixtures/button-icon-bullet.js
> +    size: 'default',
Supprimer cette prop pour avoir un fixture sans size et prendre la valeur par défaut (`'default'`), pour monter le coverage:
```suggestion
```

2021-11-18 16:01 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/test/fixtures/button-icon-bullet.js
>      'aria-label': 'aria button',
Pareil, pour prendre en compte le cas `ariaLabel || label`
```suggestion
```

2021-11-18 16:13 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/index.js
> +  icon: PropTypes.string,
Pour avoir le warning en cas de ne pas prendre le bon icon name
```suggestion
  icon: PropTypes.oneOf(keys(ICONS)),
```

2021-11-18 16:19 UTC, StefanoA1 approved these changes

2021-11-18 16:29 UTC, DjamelSoualmi requested changes

2021-11-18 16:29 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/index.js
> +    size === 'default' ? style.default : style.small,
Soit tu supprimes cette ligne 
```suggestion
    size === 'default' ? style.default : style.small,
```
soit tu supprimes les `composes` dans le css de default et small , car button est appliqué deux fois

2021-11-18 16:29 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/style.css
> +  composes: button;
les `composes` 👆

2021-11-18 16:29 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/button-link-icon-only/test/button-link.js
>    const button = wrapper.find('[data-name="bullet-button"]');
tu peux stp ajouter icon only dans le titre !

2021-11-19 08:45 UTC, DjamelSoualmi approved these changes

2021-11-19 09:24 UTC, merged