replace Links by new button in cm header
CoorpAcademy/components pull request #2024
Opened 2021-11-18 15:10 UTC by DjamelSoualmi

responsive 
![image](https://user-images.githubusercontent.com/58167920/142441810-bbeed50c-1fe6-4901-bf0f-9edc1c391296.png)

![image](https://user-images.githubusercontent.com/58167920/142441860-6cb85774-caaa-4f6f-8590-dbe11c0d04de.png)
web version

![image](https://user-images.githubusercontent.com/58167920/142439836-4f8bef4f-7b10-44e1-afa4-4a4d9706f112.png)

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-18 16:05 UTC, jomaora requested changes

2021-11-18 16:05 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/setup-header/index.js
> +              <ButtonLink {...platformListIconButtonProps} />
pourquoi deux ButtonLink si avant il n'y avait qu'un avec icon ?

2021-11-18 16:14 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/setup-header/index.js
> +              <ButtonLink {...platformListIconButtonProps} />
dans la version web on affiche le label plus l'icon et dans tablette on affiche que l'icon 
et je ne peux pas utiliser qu'un seul button car les props changent quand la taille de l’écran change et dans js on a pas l'information si on est sur un navigateur ou une tablette

2021-11-18 16:38 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/setup-header/style.css
> -  [data-name="logout-show"] .logOut:hover {
je ne savais pas qu'on pouvait utiliser le data-name comme selector haha the more you know

2021-11-18 16:38 UTC, StefanoA1 approved these changes

2021-11-19 15:44 UTC, Fausto95 approved these changes

2021-11-22 09:23 UTC, jomaora approved these changes

2021-11-22 09:54 UTC, merged