Molecule custom playlist
CoorpAcademy/components pull request #2025
Opened 2021-11-22 10:08 UTC by GhaziCoorpacademy

Molecule custom playlist qui integre l'atome Tag, buttonLink et la molecule bulletPoints.
<img width="1222" alt="Capture d’écran 2021-11-22 à 11 03 58" src="https://user-images.githubusercontent.com/94372828/142842405-82850220-e1e4-41d0-b3a4-30238bb6c700.png">

2021-11-22 10:09 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [[organisme] Section page Home Custom Playlist](https://trello.com/c/SwKzkpp9/399-organisme-section-page-home-custom-playlist)

2021-11-22 12:54 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/custom-playlist/style.css
> +  width: 153px;
mettre la width en dur risque de poser des problèmes si le titre est plus long...
vaudrait mieux la laisser en auto pour que la div s'adapte au contenu je pense

2021-11-22 12:54 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/custom-playlist/index.js
> +    <div className={style.wrapper} style={{marginTop: '150px'}}>
le marginTop tu peux le mettre directement dans la classe CSS, non?

2021-11-22 13:22 UTC, silouone commented
tu ne gères pas le cas du double tag > `published & ongoing changes`. On a vu avec adams il manque un type/label dans l'atom pour gérer ça proprement enfait. adams fait le bump et tu pourra bumper component et avoir sa modif. on aura du coup toujours un type/label mais quand ce type sera revision  il faut gerer le cas d'affichage du double tag

2021-11-22 13:23 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/custom-playlist/index.js
> +  label: PropTypes.oneOf(['Published', 'Draft', 'Archived']),
les label possible doivent inclure `ongoing change`

2021-11-22 13:38 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/custom-playlist/style.css
> +.wrapper {
il manque du radius
`  border-radius: 7px;`

2021-11-22 16:20 UTC, silouone requested changes
passe ton composant en organisme du coup vu qu'il intègre une molécule

2021-11-22 16:21 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/list-item/style.css
> +.onGoingChanges {
peut être revised, plus court et plus simple

2021-11-22 16:27 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/list-item/style.css
> +.onGoingChanges {
ok

2021-11-22 17:55 UTC, esa-coorp requested changes

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/tag/style.css
> +.revised {
```suggestion
.revised,
.draft  {
```

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/tag/style.css
> +.draft {
```suggestion
```

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +              <Tag label="Ongoing changes" type="revised" />
label dans les props

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +              <Tag label="Published" type="published" />
idem

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/tag/index.js
> +  draft: style.draft
pourquoi ajouter un mode draft?

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +  label: PropTypes.oneOf(['Published', 'Draft', 'Archived', 'Ongoing changes']),
```suggestion
  tags: PropTypes.arrayOf(
    PropTypes.shape({
      label: PropTypes.string,
      type: PropTypes.oneOf(['Published', 'Draft', 'Archived', 'Ongoing changes'])
    })
  ),
```

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +      <div className={style.title}>{title}</div>
```suggestion
      <div className={style.title} title={title}>{title}</div>
```

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            <div className={style.revised}>
cette div ne sert à rien

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            <div>
idem

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            label="Edit"
values dans les props

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            label="Edit"
pas de données en dur

2021-11-22 17:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +        <BulletPointMenuButton
idem

2021-11-22 22:04 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/tag/index.js
> +  draft: style.draft
@adamska27 pour faire la différentiation entre le mode draft et le cas du double tag (published & ongoing changes)

2021-11-22 22:18 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            <div className={style.revised}>
@esa-coorp même logique de la molécule setup-section.

2021-11-23 09:13 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/tag/index.js
> +  draft: style.draft
oui c'est ça, c'était plus simple de dupliquer le style,  vu qu'on se base sur le type pour la gestion des 2 rendus différents:
- type draft ->  Tag (style draft)
- type revised -> 2 Tags:
                         1 tag (style revised)
                          1 tag (style published)

2021-11-23 09:24 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +            <div>
@esa-coorp pour appliquer les margin

2021-11-24 11:25 UTC, closed without merging