Input select
CoorpAcademy/components pull request #2026
Opened 2021-11-22 11:24 UTC by Fausto95

**Detailed purpose of the PR**

<img width="800" alt="Capture d’écran 2021-11-22 à 12 08 16" src="https://user-images.githubusercontent.com/23306911/142853149-2289c671-0234-4559-aded-f2fcdd5be174.png">
<img width="800" alt="Capture d’écran 2021-11-22 à 12 08 26" src="https://user-images.githubusercontent.com/23306911/142853153-e45e9a22-2981-447e-aef0-cc456863f607.png">
<img width="800" alt="Capture d’écran 2021-11-22 à 12 08 41" src="https://user-images.githubusercontent.com/23306911/142853156-c873a6ad-7b06-449e-a2df-fc64a1d1389f.png">

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-22 11:25 UTC, Fausto95 commented on packages/@coorpacademy-components/src/molecule/select-multiple/style.css
> +  color: black !important;
Don't blame me 😭

2021-11-22 13:35 UTC, jomaora requested changes

2021-11-22 13:35 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +      type="checkbox"
L'atom `<Checkbox />` n'a pas de propriété type. On pourrait l'ajouter pour eviter de passer les class CSS comme ça.

2021-11-22 13:35 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/input-checkbox/index.js
> +    extraClassName = null,
à éviter, cette classe devrait définie au sein du CSS de l'atom

2021-11-22 13:35 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +        {isCMTheme ? (
```js
{theme === 'coorpmanager' ? () : ()
```

2021-11-22 15:01 UTC, Fausto95 commented on packages/@coorpacademy-components/src/atom/input-checkbox/index.js
> +    extraClassName = null,
cette classe c'est pour rajouter des styles en plus

2021-11-22 15:02 UTC, Fausto95 commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +      type="checkbox"
```suggestion
```

2021-11-23 09:13 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/select-multiple/style.css
> +  color: black !important;
😱

2021-11-23 10:48 UTC, DjamelSoualmi requested changes

2021-11-23 11:19 UTC, esa-coorp requested changes

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +    error = false,
sur les autres inputs, l'erreur est une chaine de caractère qui remplace le hint si elle est defini et qui conditionne l'affichage de picto 🔴

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +  theme: PropTypes.oneOf(['default', 'coorpmanager', 'cockpit', 'sidebar', 'setup'])
```suggestion
  theme: PropTypes.oneOf(keys(themeStyle))
```

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +  error: PropTypes.bool,
```suggestion
  error: PropTypes.string,
```

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +      checked={choice.selected}
titleStyle ="default"

et en mode default tu mets `color: inherit;` comme ça c'est le parent qui définit la couleur

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/style.css
> +  color: black !important;
@Fausto95 il faut creer un style à la checkbox où c'est le parent qui définit sa couleur (color: inherit)

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/style.css
> +.checkbox label {
à définit dans le style par default de la checkbox

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/style.css
> +.checkbox {
```suggestion
.coorpmanager .checkbox {
```

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/test/fixtures/checked-cm-theme.js
> +        name: 'English',
```suggestion
        name: '🇬🇧 English',
```

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/search-and-chips-results/style.css
> -  font-size: 16px;
👍

2021-11-23 11:19 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/search-and-chips-results/style.css
> -  font-size: 16px;
il y a moyen de le détecter au linter?

2021-11-25 10:21 UTC, esa-coorp approved these changes

2021-11-25 10:21 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +        return onChange(choice);
j'ai testé en version multiple et en version non multilple et j'ai l'impression que le choice n'est pas le bon en version multiple. @Fausto95 peux tu check s'il te plait. en tout cas en multiple:false ca fonctionne correctement.

2021-11-25 10:21 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +      return onChange({...choice, selected: checked});
ca remonte toujour sle meme element quelque soit la check selectioné

2021-11-25 11:14 UTC, jomaora approved these changes

2021-11-25 11:17 UTC, merged