Fix translation org
CoorpAcademy/components pull request #2033
Opened 2021-11-23 14:36 UTC by DjamelSoualmi

[Ticket](https://trello.com/c/erE2lU5K/2400-organism-traduction-vertical-tab)
![trans-org](https://user-images.githubusercontent.com/58167920/143043947-d48a9c00-aed2-40a6-8e4a-dfc2f3d8e4fa.gif)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-23 15:55 UTC, esa-coorp requested changes

2021-11-23 15:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  height: 88%;
```suggestion
  height: auto;
```

2021-11-23 16:00 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  height: 88%;
done

2021-11-23 16:12 UTC, esa-coorp approved these changes

2021-11-24 08:47 UTC, Fausto95 commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  left: 0px;
```suggestion
  top: 0;
  left: 0;
```

2021-11-24 08:47 UTC, Fausto95 commented on packages/@coorpacademy-components/src/organism/playlist-translation/style.css
> +  bottom: 0px;
```suggestion
  bottom: 0;
```

2021-11-24 08:47 UTC, Fausto95 approved these changes

2021-11-24 09:21 UTC, merged