add aria labels to mooc header to respect rgaa
CoorpAcademy/components pull request #2044
Opened 2021-11-26 17:14 UTC by DjamelSoualmi

This pr will add some aria-labels to make the header accessible ( to respect rgaa recommandation )

![image](https://user-images.githubusercontent.com/58167920/143613851-2b27990d-6dda-4b0e-9039-c9e32470ab6a.png)

![image](https://user-images.githubusercontent.com/58167920/143613962-fd20476a-0373-4efd-83b7-b9733c8739e2.png)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2021-11-29 09:31 UTC, jomaora requested changes

2021-11-29 09:31 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +    'logo-aria-label': PropTypes.string,
si on a un bloc `logo` dans les props à la ligne 25, pourquoi ne pas mettre la propriété 'aria-label' dans ce bloc, plutôt que 'logo-aria-label'. Cette même remarque s'applique pour les notifications et les autres props ajoutées.

2021-11-29 09:58 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +    'logo-aria-label': PropTypes.string,
je regarde ça ok

2021-12-03 13:49 UTC, StefanoA1 approved these changes

2021-12-03 14:57 UTC, jomaora approved these changes

2021-12-10 13:51 UTC, merged