Update content cards for coorpmanager
CoorpAcademy/components pull request #2096
Opened 2022-01-20 16:50 UTC by jomaora

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-01-24 17:52 UTC, esa-coorp requested changes

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const ContentTypeInfo = ({mode, type, externalContent, theme}, context) => {
```suggestion
export const THEMES = {
  'default': null,
  'coorpmanager': style.coorpmanager
};
const ContentTypeInfo = ({mode, type, externalContent, theme='default'}, context) => {
```

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +          theme === 'coorpmanager' ? style.coorpmanager : null,
```suggestion
          THEMES[theme],
```

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +  theme: PropTypes.string
```suggestion
  theme: PropTypes.oneOf(keys(THEMES))
```

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const ContentTypeInfo = ({mode, type, externalContent, theme}, context) => {
`'default': null`, ou `'default': style.default`

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const ContentTypeInfo = ({mode, type, externalContent, theme}, context) => {
je trouve que c'est mieux d'avoir une map des themes supportés. on peut mieux gérer les valeurs de `theme`

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> -.default[disabled] .customer {
est ce que ce cas fonctionne encore? @jomaora

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/index.js
> +const CardBackground = ({type, image, empty, theme}, {skin}) => {
idem que pour `card-content/index.js `

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/customer.css
> +.default[disabled] .customer {
je suis pas sûr que c'est équivalent à ce qu'il y avait avant....

2022-01-24 17:52 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +  theme
idem que sur `card-content/index.js`

2022-01-25 09:16 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/card/style.css
> -.default[disabled] .customer {
En fait, je sais pas trop à quoi ça correspond ce bloc, mais j'ai du le déplacer à cause du eslint sur `customer.css`. Vu que `.customer` n'est plus géré sur l'index.

2022-01-25 09:52 UTC, Fausto95 approved these changes
+1 pour les retours d'Eric, sinon le reste me parait ok

2022-01-25 09:52 UTC, StefanoA1 approved these changes

2022-01-25 09:53 UTC, StefanoA1 commented
idem, pas de retours apart de ceux qui sont déjà mentionnes, lgtm 👍🏻

2022-01-25 14:12 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const ContentTypeInfo = ({mode, type, externalContent, theme}, context) => {
done

2022-01-25 14:13 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/card/style.css
> -.default[disabled] .customer {
fixé sur cutomer.css

2022-01-25 15:22 UTC, esa-coorp requested changes

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +          theme={theme}
```suggestion
```
pas besoin de theme l'élément root a déjà la class coorpmanager

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +        <CardTitle title={title} empty={empty} courseContent={courseContent} theme={theme} />
```suggestion
        <CardTitle title={title} empty={empty} courseContent={courseContent} />
```
pas besoin de theme l'élément root a déjà la class coorpmanager

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +      <ContentTypeInfo mode={mode} type={type} externalContent={externalContent} theme={theme} />
```suggestion
      <ContentTypeInfo mode={mode} type={type} externalContent={externalContent}/>
```
pas besoin de theme l'élément root a déjà la class coorpmanager

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +        THEMES[theme],
```suggestion
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const CardTitle = ({title, empty, courseContent, theme}) => {
```suggestion
const CardTitle = ({title, empty, courseContent}) => {
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +        THEMES[theme],
```suggestion
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +  theme: PropTypes.oneOf(keys(THEMES))
```suggestion
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/index.js
> +const ContentTypeInfo = ({mode, type, externalContent, theme}, context) => {
```suggestion
const ContentTypeInfo = ({mode, type, externalContent}, context) => {
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/style.css
> +.externalContent .coorpmanager.author {
```suggestion
.externalContent.coorpmanager .author {
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/index.js
> +        <IconType className={classnames(THEMES[theme], style.externalIcon)} />
```suggestion
        <IconType className={style.externalIcon} />
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/index.js
> +  theme: PropTypes.oneOf(keys(THEMES)),
```suggestion
  theme: PropTypes.oneOf(keys(THEMES)),
```

le root a deja le theme coorpamanager

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/index.js
> +      <CardBackground type={type} image={image} empty={empty} theme={theme} />
```suggestion
      <CardBackground type={type} image={image} empty={empty} />
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/index.js
> +            THEMES[theme],
```suggestion
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> +.coorpmanager.badge {
```suggestion
.coorpmanager .badge {
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> +.coorpmanager.externalIconWithImage {
```suggestion
.coorpmanager .externalIconWithImage {
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> +.coorpmanager.externalIconCircleWithImageWrapper::after,
```suggestion
.coorpmanager .externalIconCircleWithImageWrapper::after,
```

2022-01-25 15:22 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> +.coorpmanager.externalIconCircleWithImageWrapper::before {
```suggestion
.coorpmanager .externalIconCircleWithImageWrapper::before {
```

2022-01-25 16:03 UTC, esa-coorp requested changes

2022-01-25 16:03 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/style.css
> +.externalContent.cardInfo {
```suggestion
.externalContent .cardInfo {
```

2022-01-25 16:04 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card-content/style.css
> +.externalContent.cardInfo {
c'était comme ça avant ... ou c'était faux avant?

2022-01-25 16:08 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/card-content/style.css
> +.externalContent.cardInfo {
Pour moi c'était faux avant, si on regarde, `externalContent` est dans le parent et `cardInfo` est à l'intérieur

![Capture d’écran 2022-01-25 à 17 06 10](https://user-images.githubusercontent.com/7602475/151013799-61d4603d-0029-49b0-b39f-9a70fcb7aabb.png)

2022-01-25 16:15 UTC, esa-coorp approved these changes

2022-01-25 17:42 UTC, jomaora commented
Go de @audric-coorp sur CM SS, je merge et je bump

2022-01-25 17:45 UTC, merged