changed condition for showing sub tabs
CoorpAcademy/components pull request #2098
Opened 2022-01-20 21:55 UTC by GhaziCoorpacademy

https://trello.com/c/kOGSCRz2/562-pas-de-selection-sur-le-menu-de-gauche-quand-on-est-sur-les-custom-playlist-focus-perdu-lors-du-passage-en-creation
- Changed condition for showing sub tabs
<img width="1440" alt="left selection" src="https://user-images.githubusercontent.com/94372828/150428345-a8811704-8fad-4dbe-9f64-35dc174f3ae8.png">

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-01-20 21:55 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [pas de selection sur le menu de gauche quand on est sur les custom playlist (focus perdu lors du passage en creation)](https://trello.com/c/kOGSCRz2/562-pas-de-selection-sur-le-menu-de-gauche-quand-on-est-sur-les-custom-playlist-focus-perdu-lors-du-passage-en-creation)

2022-01-21 09:46 UTC, DjamelSoualmi requested changes

2022-01-21 09:46 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
> +  const selectedSubTab = find(e => e.selected, selectedTab?.subTabs);
[Ça marche pas sur IE le optional chaining ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2022-01-21 13:30 UTC, adamska27 approved these changes

2022-01-21 13:39 UTC, DjamelSoualmi requested changes

2022-01-21 13:39 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
>    if (!showTabs) return null;
```suggestion
 const showTabs = selectedTab ? find(e => e.selected, selectedTab.subTabs) : undefined;
  if (!showTabs) return null;
```

2022-01-21 14:01 UTC, DjamelSoualmi approved these changes

2022-01-21 14:45 UTC, merged