changed position
CoorpAcademy/components pull request #2102
Opened 2022-01-24 19:52 UTC by GhaziCoorpacademy

![summary](https://user-images.githubusercontent.com/94372828/150854223-599f4f63-cb56-491c-ad9f-c458fa81e71e.gif)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-01-25 15:15 UTC, silouone commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  height: 79.7vh;
pk ce chiffre en particulier ? 🤔

2022-01-25 15:21 UTC, silouone commented
j'ai demandé à @GhaziCoorpacademy une canary puis deploy sur uber pour valider le comportement small /bug screen une bonne fois. hors retour sur le css

2022-01-25 15:29 UTC, jomaora requested changes
@GhaziCoorpacademy checkouté en local.. j'ai eu le summary qui passe en dessous le right section pour les dim width < 1380px

![Kapture 2022-01-25 at 16 24 19](https://user-images.githubusercontent.com/7602475/151006640-ea4431c4-0238-43cd-a0d6-8885de7680e0.gif)

2022-01-26 08:42 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  height: 79.7vh;
c pour fixer la taille du conteneur pour n'avoir que la partie à gauche qui est scrollable. Et c en vh pour gérer n'importe quelle taille d'écran

2022-01-26 10:16 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  height: 79.7vh;
@GhaziCoorpacademy c'est pas mieux :
height: calc(100vh - xpx); x étant la hauteur de ton header ou autre?

2022-01-26 10:16 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  max-height: 73vh;
pourquoi as tu besoin d'un max-height?

2022-01-26 10:16 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  top: 0;
il n'est pas plutot sticky bottom?

2022-01-26 10:45 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  max-height: 73vh;
@esa-coorp c pour avoir la marge en dessous des actions buttons (previous step...) 
https://app.zeplin.io/project/60c37c437b709167de4a178c/screen/61825cab05dc0381236c199e
et c en % de la hauteur du viewport pour garder le meme ratio que ce lui du template

2022-01-26 10:48 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/wizard-contents/style.css
> +  top: 0;
c'était en sticky top pour éviter ça: 
<img width="1440" alt="eric" src="https://user-images.githubusercontent.com/94372828/151149919-7edcffb9-8b00-460c-809d-502f279e54a8.png">

2022-01-26 11:13 UTC, esa-coorp approved these changes

2022-01-26 12:02 UTC, jomaora approved these changes

2022-01-26 12:34 UTC, merged