Card image preview
CoorpAcademy/components pull request #2109
Opened 2022-01-28 16:33 UTC by GhaziCoorpacademy

when we got url image: 
![Capture d’écran 2022-01-28 à 17 31 11](https://user-images.githubusercontent.com/94372828/151585158-6e75fbae-ad92-4556-b7fb-a4f1011f6962.png)
when no url:
![Capture d’écran 2022-01-28 à 17 31 47](https://user-images.githubusercontent.com/94372828/151585198-a97d1664-63e9-4537-8687-ab0cb6dfb1d4.png)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-01-28 16:36 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Atom cards image preview](https://trello.com/c/mjjGGjk4/615-atom-cards-image-preview)

2022-01-28 16:44 UTC, esa-coorp requested changes

2022-01-28 16:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/card-image-preview/index.js
> +          backgroundColor: primaryColor,
pourquoi? C'est un composant coorpmanager, il n'y a pas de couleur primaire

2022-01-28 16:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/card-image-preview/index.js
> +    <div className={style.container} data-name="card-image-preview">
pourquoi as tu besoin de 2 div? Je pense que tu peux faire avec une seule

2022-01-28 16:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/card-image-preview/test/handle-test.js
> +import browserEnv from 'browser-env';
c'est quoi ce test? encore un pb de rebase?

2022-01-28 16:52 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/card-image-preview/test/handle-test.js
> +import browserEnv from 'browser-env';
nn c rien 😆

2022-01-28 16:53 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/card-image-preview/index.js
> +          backgroundColor: primaryColor,
aha je ne savais pas 👍

2022-01-28 17:13 UTC, esa-coorp approved these changes

2022-01-31 10:15 UTC, adamska27 approved these changes

2022-01-31 10:42 UTC, merged