create course section component
CoorpAcademy/components pull request #2114
Opened 2022-02-02 14:38 UTC by adamska27

https://trello.com/c/Rq871ejF/619-add-molecule-section

**Detailed purpose of the PR**

create course section component

**Result and observation**

![image](https://user-images.githubusercontent.com/23300140/152188309-f000b85a-fbbe-4d86-a715-0431a9262acf.png)

![image](https://user-images.githubusercontent.com/23300140/152188180-2962acaa-8ea0-4b79-b607-13b295baf14d.png)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [x] Manual testing
- [x] Unit testing

2022-02-02 14:44 UTC, DjamelSoualmi requested changes
ça ressemble à quoi en mode responsive ?

2022-02-02 14:44 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +    <div className={style.container}>
add data-name and aria-lable plz

2022-02-02 14:44 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +          <span className={style.author}>{author}</span>
aria-lable needed

2022-02-02 14:44 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/course-section/style.css
> +    border-radius: 7px;;
```suggestion
    border-radius: 7px;
```

2022-02-02 15:53 UTC, adamska27 commented
> ça ressemble à quoi en mode responsive ?

y a pas de changements, ça s'adapte à son conteneur, y a juste le titre qui peut être trunqué (voir capture plus haut)

2022-02-02 16:37 UTC, DjamelSoualmi requested changes

2022-02-02 16:37 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +          </span>
le aria lable doit être passée dans une props `author-aria-label `, car il faut expliquer ce que ca veut dire la valeur de author

2022-02-02 16:38 UTC, DjamelSoualmi requested changes

2022-02-02 16:38 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +      aria-label={`course-section-${position}`}
aria lable c'est un text passé dans les props

2022-02-02 16:46 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +      aria-label={`course-section-${position}`}
okay mais c'est quoi l'intérêt?

2022-02-03 08:56 UTC, silouone approved these changes
lgtm, à voir comment on intègre l'ancre de drag par rapport à l'index de position ds un second temps avec le refacto du draggable. 

vois avec djamel pour qu'il valide les aria-label

2022-02-03 08:57 UTC, silouone commented
on voudrait bien un rendu small screen responsive mode pour voir comment ca s'écrase en effet @adamska27

2022-02-03 09:05 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/course-section/index.js
> +        </div>
Je pense qu'on peut enlever le "div" et appliquer un "display: block" au "span"

2022-02-03 09:37 UTC, GhaziCoorpacademy approved these changes

2022-02-03 09:37 UTC, adamska27 commented
> on voudrait bien un rendu small screen responsive mode pour voir comment ca s'écrase en effet @adamska27

https://github.com/CoorpAcademy/components/pull/2114#issuecomment-1028083927
@silouone

2022-02-03 09:49 UTC, DjamelSoualmi approved these changes

2022-02-03 09:59 UTC, merged