Redesign molecule Qcm && add coverage
CoorpAcademy/components pull request #2121
Opened 2022-02-04 20:42 UTC by StefanoA1

**Detailed purpose of the PR**

- Redesigns molecule Qcm && adds coverage

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-02-04 20:43 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Re-design composant question QCM](https://trello.com/c/yUxfVGRg/2477-re-design-composant-question-qcm)

2022-02-07 09:32 UTC, Fausto95 requested changes

2022-02-07 09:56 UTC, esa-coorp approved these changes

2022-02-07 10:08 UTC, Fausto95 requested changes

2022-02-07 10:08 UTC, Fausto95 commented on packages/@coorpacademy-components/src/molecule/questions/qcm/style.css
> +  box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.12);
Actually, just review all the designs, and this box-shadow is the same across multiple elements.
Mind creating a variable for this? One could name it: revisionBoxShadow

2022-02-07 16:12 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/questions/qcm/style.css
> +  box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.12);
@Fausto95 for the rgba color or the whole variable? si couleur j'ai trouvé que: notification-banner et popin qui utilisent ça

2022-02-08 11:28 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/questions/qcm/index.js
> +          : {};
sur unselected on laisse le css gérer le hover car on a pas besoin de couleurs de skin pour ça

2022-02-08 15:43 UTC, Fausto95 approved these changes

2022-02-08 15:53 UTC, esa-coorp approved these changes

2022-02-09 09:29 UTC, merged