Review correction popin
CoorpAcademy/components pull request #2148
Opened 2022-03-02 14:33 UTC by jomaora

https://trello.com/c/6QnVgT2S/2496-or-composant-popin-r%C3%A9vision

**Detailed purpose of the PR**

This PR introduces the new component popin for review mode. It handles the right and wrong answer feedback in web, tablet and mobile format and IE11 compatibility.

There are some modifications related to the original designs on Figma. (see comments on Trello card, approved by @audric-coorp)

- On tablet mode, the "WRONG ANSWER" or "CORRECT ANSWER" disappears. 
- On mobile mode, the "WRONG ANSWER" or "CORRECT ANSWER" should be aligne to the left. 

**Result and observation**

### Right
![Kapture 2022-03-02 at 14 52 34](https://user-images.githubusercontent.com/7602475/156375136-8ea38c0d-0d9b-4368-8bd8-31496d612fbb.gif)

### Wrong
![Kapture 2022-03-02 at 14 50 50](https://user-images.githubusercontent.com/7602475/156374437-f5efc1a9-894a-48b9-85fb-a7a2f5ea6e3f.gif)

### IE 11
![Kapture 2022-03-02 at 15 31 06](https://user-images.githubusercontent.com/7602475/156381744-a4548ed3-03c2-4b19-a808-93738695076f.gif)

**Testing Strategy**

- Manual testing

2022-03-02 15:07 UTC, StefanoA1 approved these changes

2022-03-02 17:11 UTC, esa-coorp requested changes

2022-03-02 17:11 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/index.js
> +    onClick: () => {}
pourquoi???

2022-03-02 17:11 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/style.css
> +  box-shadow: 0px 0px 68px rgba(53, 204, 127, 0.4);
```suggestion
  box-shadow: 0px 0px 68px color( cm_positive_100 a(40%));
```

2022-03-02 17:11 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/style.css
> +  box-shadow: 0px 0px 68px rgba(239, 72, 74, 0.4);
```suggestion
  box-shadow: 0px 0px 68px color( cm_negative_100 a(40%));
```

2022-03-03 09:29 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/index.js
> +    onClick: () => {}
Le <ButtonLink /> (qu'ici se comporte comme un CTA - _je veux bien bien un CTA avec le même comportement du ButtonLink, mais du coup c'est un component nouveau_) s'attend à avoir une propriété onClick. Si on l'a pas, lorsqu'on clic sur on a une erreur dans la console.

![Kapture 2022-03-03 at 10 28 35](https://user-images.githubusercontent.com/7602475/156536289-0e5dee14-e783-455a-b0d3-0ea77828d072.gif)

2022-03-03 09:40 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/style.css
> +  box-shadow: 0px 0px 68px rgba(239, 72, 74, 0.4);
@esa-coorp Je veux bien, et je suis d'accord sur le principe (comme je suis d'accord sur ton antérieur commentaire, **MAIS**, une chose est ce qu'on pense logique, une autre est ceux qui dise la maquette

`@value cm_negative_100: #ed3436;` = `rgb(237, 52, 54)`

Or la maquette dit...

```css
  box-shadow: 0px 0px 68px rgba(239, 72, 74, 0.4);
```

![Capture d’écran 2022-03-03 à 10 38 38](https://user-images.githubusercontent.com/7602475/156537984-de09d52c-9b66-4489-9f19-34e0579e95d3.png)

Du coup je me fie à la maquette, même si je trouve qu'il y a une incohérence. Du coup... @wernerdurand à toi de nous ce qui en est vraiment ?

2022-03-03 09:55 UTC, esa-coorp requested changes

2022-03-03 09:55 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/review-correction-popin/index.js
> +    onClick: () => {}
est ce que sur le composant ButtonLink il faudrait pas mettre en valeur par default du onclick _.noop?

2022-03-03 10:38 UTC, esa-coorp approved these changes

2022-03-03 10:49 UTC, merged