Molecule add stars
CoorpAcademy/components pull request #2150
Opened 2022-03-07 14:57 UTC by GhaziCoorpacademy

https://trello.com/c/Aomhgjpf/680-ajout-composant-add-stars
First component: title + checkbox
checked: 
<img width="254" alt="checked" src="https://user-images.githubusercontent.com/94372828/157058599-6cda44c3-8ad4-4fa6-85eb-b4937b94b5f7.png">
unchecked: 
<img width="254" alt="unchecked" src="https://user-images.githubusercontent.com/94372828/157058666-ef07f910-4bbb-4ebd-856b-1c28c399d206.png">

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-03-07 14:58 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [ajout composant "add stars"](https://trello.com/c/Aomhgjpf/680-ajout-composant-add-stars)

2022-03-07 17:11 UTC, DjamelSoualmi requested changes
Tu peux utiliser un nom générale plz , le composant sera utilisé dans plusieurs endroit et pas que pour les reward 
Proposition: checkbox-with-title

2022-03-07 17:11 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/reward-title/index.js
> +    </label>
data-name aussi pour les tests e2e

2022-03-08 09:26 UTC, silouone approved these changes

2022-03-08 09:30 UTC, esa-coorp approved these changes

2022-03-08 09:31 UTC, adamska27 approved these changes

2022-03-08 09:39 UTC, DjamelSoualmi approved these changes

2022-03-08 09:41 UTC, merged