Organism rewards
CoorpAcademy/components pull request #2168
Opened 2022-03-22 09:45 UTC by GhaziCoorpacademy

https://trello.com/c/EV71J1c6/730-cr%C3%A9er-le-template-rewards
- fixed checkboxWithTitle component (CSS)
- created organism for certification rewards
- injected the organism in wizardContent
- injected the wizardContent in brandUpdate template
![rewards](https://user-images.githubusercontent.com/94372828/159452475-c4c19341-b7c3-4e4a-b129-6ce0c6a7d4bb.png)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-03-22 09:45 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [créer le template rewards](https://trello.com/c/EV71J1c6/730-cr%C3%A9er-le-template-rewards)

2022-03-23 16:22 UTC, silouone commented on packages/@coorpacademy-components/src/organism/rewards-form/index.js
> +      )}
demain on décide d'ajouter un 3ieme type genre un text-area or else. on se retrouve avec du code à refacto ou du ternaire imbriqué illisible. 

autant le faire propre. déclare toi un object: 

ITEM : {
 [type]: <InputTextWithTiteledCheckbox {...item} /> || <DragAndDropWrapper {...item} />
}

et tu peux acceder dans ton map à ITEM[type]

2022-03-24 08:54 UTC, DjamelSoualmi requested changes

2022-03-24 08:54 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/rewards-form/index.js
> +  return <ul className={style.list}>{itemsView}</ul>;
aria-label  et data name plz

2022-03-24 10:34 UTC, adamska27 approved these changes

2022-03-24 10:34 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/default.js
> +import checkedInputText from '../../../../molecule/input-text-with-titeled-checkbox/test/fixtures/checked';
petite typo dans le nom du file, ``input-text-with-titled-checkbox``

2022-03-24 13:03 UTC, silouone approved these changes

2022-03-24 14:20 UTC, DjamelSoualmi approved these changes

2022-03-24 14:21 UTC, merged