Molecule Skill Card
CoorpAcademy/components pull request #2173
Opened 2022-03-24 08:59 UTC by StefanoA1

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-03-24 16:41 UTC, jomaora approved these changes

2022-03-24 17:14 UTC, esa-coorp requested changes

2022-03-24 17:14 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/skill-card/style.css
> +  border-radius: 7px;
```suggestion
```

2022-03-25 09:17 UTC, esa-coorp approved these changes

2022-03-25 09:31 UTC, merged