Atom Review Presentation
CoorpAcademy/components pull request #2175
Opened 2022-03-25 09:57 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR includes the Review Presentation Atom.

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-03-25 10:18 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Atom review-mode-presentation](https://trello.com/c/11YdC1iv/2547-atom-review-mode-presentation)

2022-03-29 12:19 UTC, jomaora requested changes

2022-03-29 12:19 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +  width: 348px;
Je le mettrais en 100% au niveau de l'atom. Ce taille fixe (ou plutôt en pourcentage), on devrait la donner dans le container qui va accueillir ce component.

Je te laisse regarder la molecula [summary](http://coorpacademy.github.io/components/components/?path=/story/moleculewizardsummary--organizecourses), tu verras bien que lorsqu'elle est "isolée", elle prend le 100%, mais quand elle est intégrée au sein d'un [autre component](http://coorpacademy.github.io/components/components/?path=/story/templatebackofficebrandupdate--wizardformeditplaylist), du coup, c'est ce component qui lui définit sa taille.

Une fois que tu dois sur le storybook, tape sur "S" pour cacher le menu de gauche avec tous la liste de components, histoire que tu puisse voir bien le rendu en desktop.

2022-03-29 12:19 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +    width: 100%;
👍

2022-03-29 12:19 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +    width: 326px;
Idem ici, je crois que ça devrait être 100%

2022-03-29 12:19 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +const buildTooltip = tooltip => {
On peut faire ce cette fonction soit un component

```js
const ToolTip = ({tooltip }) => {
    // tu laisses les reste comme c'est déjà
}
```

Et après, plutot que faire 

```js
{buildTooltip(el.tooltipText)}
```

tu fais 

```js
<Tooltip ...el />
```

et c'est plus élégant.

2022-03-29 12:19 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +        {map.convert({cap: false})((el, key) => {
`el` ... tu peux renommer cette variable, stp... ce sont des label, non ? du `labelList` ?

2022-03-29 12:24 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +        }, labelList)}
```suggestion
        {map.convert({cap: false})((label, key) => {
          return (
            <li key={key} className={style.reviewList}>
              <div className={style.reviewListItemWrapper} data-tip data-for="reviewListItem">
                <div className={style.reviewListText}>
                  {getIcon(key)} {label.text}
                </div>
                {buildTooltip(label.tooltipText)}
              </div>
            </li>
          );
        }, labelList)}
```

2022-03-29 12:54 UTC, esa-coorp approved these changes

2022-03-29 12:59 UTC, StefanoA1 approved these changes

2022-03-29 13:02 UTC, jomaora approved these changes

2022-03-29 13:12 UTC, StefanoA1 approved these changes

2022-03-29 13:13 UTC, DjamelSoualmi requested changes

2022-03-29 13:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +  'aria-label': PropTypes.string.isRequired,
```suggestion
  'aria-label': PropTypes.string,
```

2022-03-29 13:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +  labelList: PropTypes.shape({
```suggestion
  labelsList: PropTypes.shape({
```
je trouve ça bizarre , le type c'est  un objet et dans le code tu mappes dessus !

2022-03-29 13:32 UTC, DjamelSoualmi approved these changes

2022-03-29 14:01 UTC, merged