Template Dashboard Skills
CoorpAcademy/components pull request #2183
Opened 2022-03-31 14:30 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR includes the Dashboard Skills Template.
https://trello.com/c/Gxa3IUnz/2549-template-dashboard-skills

Tested with:

ie11
safari
chrome
mozilla

**Result and observation**
- **ie**:
_Loading_: 

**Desktop**
<img width="871" alt="Loading-desktop" src="https://user-images.githubusercontent.com/79636283/161756336-2c2fbd47-d9df-43eb-9000-8eecf8ead01a.png">
**Tablet**
<img width="561" alt="Loading-tablet" src="https://user-images.githubusercontent.com/79636283/161756362-043b74db-6e7b-4415-aac2-7890f5d35367.png">
**Mobile**
<img width="318" alt="Loading-mobile" src="https://user-images.githubusercontent.com/79636283/161756375-8d5eaa12-9d36-4301-9342-a04ca1b2fb85.png">

_Many-Skills_:
![Kapture 2022-04-05 at 17 17 15](https://user-images.githubusercontent.com/79636283/161787827-617dc156-45a2-4aa2-ae59-3c36f0d9ff86.gif)

_No-Skills_:
![Kapture 2022-04-05 at 17 32 53](https://user-images.githubusercontent.com/79636283/161791060-b84b2ad9-c8ff-4b06-8a25-3cbec16882b7.gif)

_Sticky Atom Review Presentation_:
![Kapture 2022-04-06 at 14 28 08](https://user-images.githubusercontent.com/79636283/161974942-254c9528-b87f-4f51-9892-95b4b1e306ce.gif)

- **chrome**:
_Loading_:
![Kapture 2022-04-05 at 17 07 54](https://user-images.githubusercontent.com/79636283/161785777-97363bda-58c1-4455-870e-b4a54739f4ac.gif)

_Many-Skills_:
![Kapture 2022-04-05 at 17 04 24](https://user-images.githubusercontent.com/79636283/161785070-c11c58a3-e948-47d1-bc2f-758cf28edc21.gif)

_No-Skills_:
![Kapture 2022-04-05 at 17 10 23](https://user-images.githubusercontent.com/79636283/161786274-ace01739-268b-436d-8897-e71f001f07f8.gif)

_Sticky Atom Review Presentation_:
![Kapture 2022-04-06 at 14 22 21](https://user-images.githubusercontent.com/79636283/161973861-9e7836f3-1a20-4c30-82ea-269bde896224.gif)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-04-05 16:17 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +  user-select: none;
👍🏻

2022-04-05 17:06 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/review-skills/style.css
>      margin-right: 0px;
```suggestion
    margin-right: 0;
```

2022-04-05 17:06 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/review-skills/style.css
>    margin: 0px 16px 16px 0px;
```suggestion
  margin: 0 16px 16px 0px;
```

2022-04-05 17:06 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/skill-card/style.css
> +  padding: 0px 24px 24px;
```suggestion
  padding: 0 24px 24px;
```

2022-04-05 17:07 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +  margin: 16px 40px 0px 0px;
```suggestion
  margin: 16px 40px 0 0;
```

2022-04-05 17:07 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +  margin-bottom: 0px;
```suggestion
  margin-bottom: 0;
```

2022-04-06 08:32 UTC, StefanoA1 approved these changes

2022-04-06 08:55 UTC, jomaora requested changes

2022-04-06 08:55 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +  margin-bottom: 0px;
Alors, attention à appliquer des styles aux valises html comme ça... je crois que par le passé, ce type de choses a eu des impacts sur d'autres components utilisant le même valise (@esa-coorp tu me dis si je me trompe). 

@EmelineLeduc  Est-ce possible de ajouter une classe css à l'`ul` ?

2022-04-06 13:03 UTC, StefanoA1 approved these changes

2022-04-06 13:20 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/review-dashboard-skills/style.css
> +  z-index: 1;
pourquoi on a besoin de ça?

2022-04-06 13:32 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/template/review-dashboard-skills/style.css
> +  z-index: 1;
C'est une erreur. Au cours du développement (pour rendre l'atome Review Presentation sticky), j'ai ajouté 'z-index' car les éléments se chevauchaient, mais j'ai trouvé une autre solution. Et j'ai oublié d'enlever cette ligne...

2022-04-06 13:45 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/review-presentation/style.css
> +ul {
👍

2022-04-06 13:45 UTC, esa-coorp approved these changes

2022-04-06 15:46 UTC, merged