add fixture steps-animation
CoorpAcademy/components pull request #2203
Opened 2022-05-09 13:04 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-05-09 13:06 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Animate the transition of the header step items (for finished revision)](https://trello.com/c/qioPGb9m/2592-animate-the-transition-of-the-header-step-items-for-finished-revision)

2022-05-09 13:33 UTC, jomaora approved these changes

2022-05-09 13:35 UTC, StefanoA1 requested changes

2022-05-09 13:35 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/review-header/style.css
> +    animation: stepsAnimation 0.5s ease-in-out 0.5s forwards;
```suggestion
    opacity: 0;
    transform: opacity 0.5s ease-in-out 0.5s;
```

2022-05-09 13:35 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/review-header/style.css
> +  animation: stepsAnimation 0.5s ease-in-out 0.5s forwards;
pareil que pour l'autre, c'est possible avec transition

2022-05-09 13:51 UTC, StefanoA1 commented
selon les gifs que je vois, la view mobile est cassé (tous les step items deviennent collés les uns avec les autres), normalement on attend ça:

![Screenshot 2022-05-09 at 15 51 28](https://user-images.githubusercontent.com/33550261/167424998-3131c4c9-faa6-4fe9-8360-6921c4580527.png)

2022-05-10 07:57 UTC, StefanoA1 approved these changes

2022-05-10 08:12 UTC, merged