Introducing app review
CoorpAcademy/components pull request #2210
Opened 2022-05-17 15:09 UTC by chrisdugne

introducing new package `app-review`;
still early POC, dedicated for mobile on this version

2022-05-18 10:03 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [[OR] mise en place du store dédié app-revision](https://trello.com/c/0dTz8TQB/2597-or-mise-en-place-du-store-d%C3%A9di%C3%A9-app-revision)

2022-05-19 12:37 UTC, jomaora commented on packages/@coorpacademy-app-review/src/components/root-view.tsx
> +const Button = (props) => <p {...props} className={styles.textButton} />;
@chrisdugne Juste pour confirmer, mais on est d'accord qu'ici on n'a pas à déplacer les components web déjà fait mais juste à installer la lib et utiliser la template, non ?

2022-05-19 13:07 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/components/root-view.tsx
> +const Button = (props) => <p {...props} className={styles.textButton} />;
oui bonne question! je vais POC ça sur `@coorpademy/components`

https://coorpacademy.slack.com/archives/GA45KH3UM/p1652965278102089

2022-05-19 19:41 UTC, chrisdugne commented on packages/@coorpacademy-components/package.json
> +    "react-native": "^0.68.2",
note: c'est bien une `devDeps`

2022-05-20 12:16 UTC, StefanoA1 approved these changes

2022-05-20 12:41 UTC, jomaora requested changes

2022-05-20 12:41 UTC, jomaora commented on packages/@coorpacademy-app-review/src/components/__tmp-backup-vues-mobile/revision-home.stories.tsx
> +import * as React from 'react';
ces fichiers sont toujours nécessaires ? On dirait des fixtures

2022-05-20 13:48 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/components/__tmp-backup-vues-mobile/revision-home.stories.tsx
> +import * as React from 'react';
oui je les garde ici pour les deplacer plus tard, il faudra les readapter aux props;
il s'agit des vues mobiles creees sur le design figma

2022-05-20 14:11 UTC, jomaora approved these changes

2022-05-20 14:18 UTC, merged