Review/skills --> introducing fetch and state
CoorpAcademy/components pull request #2251
Opened 2022-06-28 14:20 UTC by chrisdugne

**Detailed purpose of the PR**

- introducing skills 
- improved data/ui reducers and actions
- reordered types
- introduced mocks versions for services to be used by sandbox

2022-06-28 15:15 UTC, StefanoA1 approved these changes

2022-06-29 15:07 UTC, StefanoA1 approved these changes

2022-06-30 08:15 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-dasboard-skills-sur-app-review)

2022-06-30 12:04 UTC, jomaora commented on packages/@coorpacademy-app-review/src/middlewares/on-start-app.ts
> +            return dispatch(receivedSkills(skills));
l'action de devrait être alors un truc du genre `storeUserSkillsAction`, `storeReceivedSkillsAction` ?

2022-06-30 12:05 UTC, jomaora commented on packages/@coorpacademy-app-review/src/middlewares/on-start-app.ts
> +        fetchSkills(token)
on peut pas faire une async/await ?

2022-06-30 12:06 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/data/skills.ts
> +export type State = Skills;
à éviter et à préférer `SkillsState`

2022-06-30 12:06 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
>  export type State = Slides;
`export type SlideState`

2022-06-30 12:11 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/step-items.ts
> +  lastVisitedIndex = -1
ce logique devra se faire avec le state de la progression

2022-06-30 12:13 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/fetch-skills.mock.ts
> +  {
je commence à m'inquiéter sur le fait que ces données ne ressemblent pas aux vraies données des apis.

Voici un exemple de réponse du mooc quand on fecth les skills d'un user à afficher

```json
[
  {
    "skillRef": "skill_41BBqFKoS",
    "slidesToReview": 25,
    "name": "Cultural Sensitivity",
    "custom": false
  },
  {
    "skillRef": "skill_41HaT-0hH",
    "slidesToReview": 38,
    "name": "Critical Thinking",
    "custom": false
  },
  {
    "skillRef": "skill_4yw5hYFjH",
    "slidesToReview": 9,
    "name": "Digital Dexterity",
    "custom": false
  }
]
```

@chrisdugne @StefanoA1 @alanlanglois Si vous avez des questions sur les fixtures ou le format des données, vous me dites. Il faut surtout pas qu'on perd du temps avec des fixtures qui n'ont pas le même format que la réalité.

2022-06-30 12:16 UTC, jomaora commented on packages/@coorpacademy-app-review/src/types/skills.ts
> +  _id: string;
ref

2022-07-01 07:14 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/actions/data/skills.ts
> +export type ErrorFetchingSkills = {
Parlons en car je ne suis pas d'accord: ça surchargerait la lecture partout dans le code pour rien, c'est typiquement de la notation [hungarian](https://en.wikipedia.org/wiki/Hungarian_notation#Disadvantages)

et c'est d'ailleurs, en partie, l'objectif de cette PR justement, puisque j'ai positionné les types précisement là où ils définissent leur logique: (je reprends `ReceivedSkills`: on est bien dans `/actions/data/skills` et pas dans un "fourre tout" `/common/types`) 

de plus:
- lorsque tu fais une completion, tu auras la meme proposition avec ou sans suffixe, et tu vois de toute manière le path, et le type lui meme:

<img width="910" alt="Screenshot 2022-07-01 at 09 06 47" src="https://user-images.githubusercontent.com/910636/176842677-2f692525-78ee-403d-b6dd-569bef351f6d.png">

- puis là où tu manipules le type, c'est à dire dans un reducer ou dans un middleware, tu as tout de suite l'info grâce à ton IDE:

<img width="715" alt="Screenshot 2022-07-01 at 09 10 07" src="https://user-images.githubusercontent.com/910636/176843207-98169786-cc02-4b46-8a06-9059bea7acfe.png">

2022-07-01 07:45 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/actions/data/slides.ts
> +export type Slide = SlideFromAPI & {
je suis d'accord, je ne sais pas trop comment nommer ces types sont bien différents mais qui devraient avoir le meme nom...

- le `Slide` qui vient de l'API et donc qui sera du type décrit par `progression-engine`
- le `Slide` manipulé par le reducer à qui on rajoute des properties pour le fonctionnement de l'app

pour l'instant `SlideFromAPI` est décrit ici, mais le but est bien de l'importer de `progression-engine`

2022-07-01 07:48 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/services/fetch-skills.mock.ts
> +  {
ok merci, (j'avais pris le format de https://onboarding.coorpacademy.com/explorer/#!/skills/getSkills pour l'instant)

2022-07-01 08:05 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/types/skills.ts
> +  _id: string;
✅

2022-07-01 08:05 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
>  export type State = Slides;
✅

2022-07-01 08:05 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/skills.ts
> +export type State = Skills;
✅

2022-07-04 08:26 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/fetch-skills.mock.ts
> +  {
le bon endpoint est https://onboarding.coorpacademy.com/explorer/#!/skills/skills_review_user

2022-07-04 08:53 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +      // hard coded for now
from https://github.com/CoorpAcademy/components/pull/2254
merci @StefanoA1

2022-07-04 08:53 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/data/skills.ts
> +export type ErrorFetchingSkills = {
ok

2022-07-04 09:08 UTC, jomaora requested changes

2022-07-04 09:08 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +type Slides = {
si renommé, est-ce que cette ligne est nécessaire, vu que tu fais après `SlidesState = Slides;` ?

2022-07-04 09:08 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
>      exitNode: PropTypes.string,
@chrisdugne @StefanoA1 je reviens sur l'importance de connaitre les données renvoyés par les API avant de faire de typage / protypes, etc... la propriété exitNode elle est ajoutée ici et ça laisse penser qu'on a un failExitNode alors que ça n'arrive jamais dans le mode review. Du coup, je ne vous pas trop à quoi elle sert cette prop.

2022-07-04 09:26 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/progression.ts
> +          answerUI: {
effectivement, et comme tu me le disais tout à l'heure on aura une `ref` ici depuis le d'api progression;

- donc il faudra faire un `fetchSlide` qui stockera dans `data/slides`
- le `mapStateToProps` s'occupera de constituer cette `nextSlide` pour la vue
- très juste: c'est différent des `ui/answers` du user, il faudrait trouver un autre nom oui (d'ailleurs il faudrait faire un point pour redefinir un peu mieux ces noms, trop de choses s'appellent "answer" et pourraient etre plus précises)`

ce validateSlide est encore "statique" en attendant les prochains branchement cela dit, et ne dépend pas du sujet de cette PR en particulier;

listons ces taches pour faire avancer l'app en gardant bien en mire ces sujets de construction ?

2022-07-04 09:32 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
>      exitNode: PropTypes.string,
effectivement, il faut simplifier si on peut, tu valides @StefanoA1 ?

2022-07-04 10:16 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
>      exitNode: PropTypes.string,
peut être on le renomme comme earlyExit alors?
vu que de toute façon on a besoin de savoir s'il y a une sortie prématuré, car il y a qqs effets (UI) à faire dans ce cas là et donc on a besoin de cette info

2022-07-04 15:35 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/middlewares/on-start-app.ts
> +        fetchSkills(token)
pb des async/await dans les middlewares:
ils rendent le code ‘synchrone’ puisqu’on les attend 1 par 1;

or on veut parfois `dispatch` plusieurs choses en meme temps, et on reagira au retour de chacun de maniere asynchrone, peu importe l’ordre


exemple: qd tu fais
```
dispatch(fetchA).then(() => dispatch(receiveA))
dispatch(fetchB).then(() => dispatch(receiveB))
```

tu auras par exemple:
```
fetchA
fetchB
receiveB
receiveA
```

alors qu’avec async await tu forces l’ordre et l’attente
```
await dispatch(fetchA)
await dispatch(receiveA)
await dispatch(fetchB)
await dispatch(receiveB)
```

```
fetchA
receiveA
fetchB
receiveB
```

parfois c’est bien voire mieux, mais en général on veut etre plus souple sur du frontend, notamment sur les middlewares: on pourrait tout demander d'un coup et afficher au fur et à mesure que les retours arrivent;

2022-07-04 15:37 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/actions/data/skills.ts
> +export type ReceivedSkills = {
https://github.com/CoorpAcademy/components/pull/2251#discussion_r911680648

2022-07-04 15:37 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/actions/ui/finished-slides.ts
>  export type UpdateFinishedSlides = {
https://github.com/CoorpAcademy/components/pull/2251#discussion_r911680648

2022-07-04 15:40 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
>      exitNode: PropTypes.string,
@StefanoA1 earlyExit pour moi n'a pas de sens non plus... on aura toujours l'`exitNode` dans le nextContent.ref (qu'on ait arrivé à la fin ou qu'on n'ai plus de slides par cas extrême) --> dans les deux cas on devra passer dans la partie d'animation.

2022-07-04 15:40 UTC, jomaora approved these changes
@chrisdugne @StefanoA1 je valide. Il reste le sujet d'exitNode, je vous liasse le traiter dans une autre PR

2022-07-04 15:48 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +type Slides = {
👍

2022-07-04 15:55 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/progression.ts
> +          answerUI: {
sujet complet suivi ici https://trello.com/c/sW0MXkHS/2637-or-app-review

2022-07-04 15:57 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/ui/step-items.ts
> +  lastVisitedIndex = -1
:+1: parties progression + validate slide suivies ici https://trello.com/c/sW0MXkHS/2637-or-app-review

2022-07-05 08:12 UTC, merged