Add CREATE_PROGRESSION action
CoorpAcademy/components pull request #2261
Opened 2022-07-08 08:51 UTC by StefanoA1

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-07-08 08:51 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Redux Action: CREATE_PROGRESSION](https://trello.com/c/2q6qa9fc/2678-add-redux-action-createprogression)

2022-07-11 13:04 UTC, chrisdugne requested changes

2022-07-11 13:04 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/types/ui-progression.ts
> +  _id?: string;
ce type sera au niveau de reducer/ui/progression, mais c;est en WIP ok

2022-07-11 13:46 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +const setFirstSlide = (state: SlidesState, slide: UISlide): SlidesState => {
yes, pris en compte dans le prochain ticket https://trello.com/c/Ng7LlU6D/2684-add-redux-action-fetchslide (pour ne pas refactor tout d'un coup)

2022-07-12 08:48 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +const setFirstSlide = (state: SlidesState, slide: UISlide): SlidesState => {
👍

2022-07-12 08:49 UTC, chrisdugne approved these changes

2022-07-12 12:31 UTC, jomaora requested changes

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/create-progression.ts
> +const createProgression: CreateProgressionFnBuilder = fetch => async (skillRef, token) => {
C'est normal que `fetch`, `skillRef` et `token` n'ont pas de type ?

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/create-progression.ts
> +    headers: {authorization: token},
pas besoin de passer method : "POST" ?

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/fetch-skills.ts
> +  return toJSON<Skills>(response);
@chrisdugne @StefanoA1 je suis un peu perturbé par les nom de type et de fonction... `createFetchSkills` alors qu'on fetch seulement. Pourquoi utiliser `create` ? C'est quoi ce qu'on crée ici ? c'est pas plutôt un build pour créer une fonction ?

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/fetch-slide.ts
> +const buildFetchSlide: DefaultFetchSlideBuilder = () => {
@StefanoA1 j'aurais préféré, que si cette fonction n'est pas utilisée pas dans ta PR (je n'ai pas trouvé un call dans un autre fichier) et tenant compte qu'il y a un ticket pour la partie fetch Slides, que ce fichier ne soit pas inclus dans ce PR, pour garder la cohérence dans la lecture de la PR.

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/types/ui-progression.ts
> +  exitNode?: 'successExitNode' | 'failExitNode';
on encore cet `exitNode` qui traine ?

2022-07-12 12:31 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
>          const exitNode = get('exitNode', progression);
est-ce qu'on devrait pas calculer si on a un exitNode (donc valeur true/false) en fonction de ce qu'on dans progression.state.nextContent ?

2022-07-12 12:53 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/types/ui-progression.ts
> +  exitNode?: 'successExitNode' | 'failExitNode';
oui, mais ça va être enlevé des la prochaine pr (pour le supprimer il faut alterer de code dans qqs endroits)

2022-07-12 12:55 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/services/fetch-slide.ts
> +const buildFetchSlide: DefaultFetchSlideBuilder = () => {
c'est utilisé dans onReceiveProgression, l'import est un import défaut

2022-07-12 13:00 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
>          const exitNode = get('exitNode', progression);
oui, c'est inclus dans le prochaine ticket https://trello.com/c/Ng7LlU6D/2684-add-redux-action-fetchslide car il y a qqs endroits ou les slides prennent ce valeur

2022-07-12 13:50 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/services/create-progression.ts
> +const createProgression: CreateProgressionFnBuilder = fetch => async (skillRef, token) => {
oui ils l'ont, le type est inferé car c'est déclaré dans CreateProgression plus en haut

2022-07-13 06:40 UTC, jomaora approved these changes

2022-07-13 08:03 UTC, merged