popine no access
CoorpAcademy/components pull request #2267
Opened 2022-07-19 14:37 UTC by BEN-HALIMA-Bilel

Trello: https://trello.com/c/f46ywgcT/869-player-scorm-ecran-contenu-non-accessible
Figma : https://www.figma.com/file/wKfiuExJYFuzxj5deVJWiL/Scormification-game-Interface?node-id=337%3A128
Ajout de la TemplateAppPlayerNoAccess => this screen used to block unlicensed users. 
![Capture d’écran 2022-07-19 à 16 43 59](https://user-images.githubusercontent.com/109510491/179779042-cf19100c-292f-4c73-8e57-bc8f08ae34e1.png)

2022-07-19 15:19 UTC, adamska27 commented
t'as pushé un file vide:
[packages/@coorpacademy-components/src/template/app-player/popin-no-access/style.css](https://github.com/CoorpAcademy/components/pull/2267/files#diff-aa94bd1d21f3c015d8475981c7ac7564df0f1e4c9aae48fa37a32e394cf6c234)

2022-07-19 15:59 UTC, BEN-HALIMA-Bilel commented
> t'as pushé un file vide: [packages/@coorpacademy-components/src/template/app-player/popin-no-access/style.css](https://github.com/CoorpAcademy/components/pull/2267/files#diff-aa94bd1d21f3c015d8475981c7ac7564df0f1e4c9aae48fa37a32e394cf6c234)

2022-07-20 08:29 UTC, esa-coorp approved these changes

2022-07-20 08:30 UTC, esa-coorp reviewed
@BEN-HALIMA-Bilel il faudra tester sur ie11

2022-07-20 12:28 UTC, BEN-HALIMA-Bilel commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-block-start: 0px;
Par défaut sur les balises <p></p> On a un espacement de margin block et pour avoir le bon rendu sans toucher au ancien code, je dois éliminer cet espacement.

2022-07-21 07:54 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-block-start: 0px;
'est pas supporté sur ie par contre

2022-07-22 13:21 UTC, BEN-HALIMA-Bilel commented
> @BEN-HALIMA-Bilel il faudra tester sur ie11

@esa-coorp C'est fait et c'est corriger le BUG de mettre en centre cette composante CM-POPIN sur IE11.

2022-07-25 11:48 UTC, DjamelSoualmi requested changes

2022-07-25 11:48 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-block-start: 0px;
@adamska27  a raison 
![image](https://user-images.githubusercontent.com/58167920/180769933-637cd574-fbae-4a1b-8788-d912d679f795.png)

2022-07-25 11:48 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +          {descriptionText ? <p className={style.descriptionText}>{descriptionText}</p> : null}
```suggestion
          {descriptionText ? <p className={style.descriptionText} dangerouslySetInnerHTML={{__html: descriptionText}} /> : null}
```

2022-07-25 11:48 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/no-access.js
> +    descriptionText: `You do not have access to this page or your license has \n expired. \n Please contact your administrator for more information.`
ça marche pas sans dangerouslySetInnerHTML

2022-07-26 13:01 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-block-start: 0px;
@BEN-HALIMA-Bilel  t'as pas corrigé ça

2022-07-26 15:27 UTC, godu requested changes
`margin-block-start`, j'ai pas l'impression que c'est adapté

2022-07-26 15:27 UTC, godu commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-block-start: 0px;
```suggestion
  margin-top: 0px;
```

2022-07-26 15:48 UTC, DjamelSoualmi approved these changes

2022-07-26 15:51 UTC, godu approved these changes

2022-07-26 17:05 UTC, esa-coorp requested changes

2022-07-26 17:05 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/no-access.js
> +    descriptionText: `You do not have access to this page or your license has \n expired. \n Please contact your administrator for more information.`
👍 
```suggestion
    descriptionText: `You do not have access to this page or your license has expired. <br> Please contact your administrator for more information.`
```

2022-07-27 12:49 UTC, esa-coorp approved these changes

2022-07-27 12:50 UTC, merged