Customisation-Player-Scorm-end-screen
CoorpAcademy/components pull request #2281
Opened 2022-07-29 14:53 UTC by BEN-HALIMA-Bilel

2022-07-29 15:07 UTC, esa-coorp requested changes

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-correct.js
> +        }
```suggestion
        failed: false
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-correct.js
> +      }
```suggestion
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-with-recommendations.js
> +});
A supprimer

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm-with-feedback.js
> +      }
```suggestion
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm.js
> +    }
```suggestion
      mode: 'scorm'
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/player-scorm-result/index.js
> +export default PlayerResult;
A supprimer

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/player-scorm-result/style.css
> +}
Asupprimer

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/player-scorm-result/test/fixtures/fail.js
> +}
A supprimer

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/player-scorm-result/test/fixtures/success.js
> +}
Asupprimer

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-correct.js
> +    summary: {
```suggestion
    mode: 'scorm',
    summary: {
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm-with-feedback.js
> +      Mode: 'scorm',
```suggestion
      mode: 'scorm',
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm.js
> +      Mode: 'scorm',
```suggestion
      mode: 'scorm',
```

2022-07-29 15:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/variables/colors.css
> +@value green_success: #38CC6C
on garde l'ancien vert . A voir avec @SachaPerathoner

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/feedback/style.css
> +}
saut de ligne

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +    <div className={!(mode === 'scorm') && style.popinWrapper}>
c'est quoi ça? pourquoi cette condition?
et pk pas ça plutôt?
`mode !== 'scorm'`

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +  mode: PropTypes.string
tu peux être plus précis là et mettre un enum:
`PropTypes.oneOf(['scorm'...])`

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +  mode: PropTypes.string
pareil

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/style.css
> +
à supprimer

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +    <div className={!(mode === 'scorm') && style.popinWrapper}>
si c'est mode: scorm tu ne veux pas du style popinWrapper c'est ça?

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +  mode: PropTypes.string
enum

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +      <div className={!(mode === 'scorm') && style.summaryWrapper}>
`mode !== 'scorm'`

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +const BackGroundScorm = props => {
`BackgroundScorm` serait mieux je pense

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +  else return children;
pas besoin du else

2022-08-02 15:47 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-correct.js
> +    summary: {
il te manque tjrs le mode ici

2022-08-02 18:47 UTC, esa-coorp requested changes

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +  const {header, summary, mode} = props;
```suggestion
  const {header, summary, mode= "default"} = props;
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
> +  mode: PropTypes.oneOf(['scorm'])
```suggestion
  mode: PropTypes.oneOf(['scorm', 'default'])
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/feedback/index.js
> +  const {media, mediaDescription, title, description, mode} = props;
```suggestion
  const {media, mediaDescription, title, description, mode='default'} = props;
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
> +.smallCricle {
```suggestion
.smallCircle {
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
> +.mediumCricle {
```suggestion
.mediumCircle {
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
> +.largeCricle {
```suggestion
.largeCircle {
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
> +  .largeCricle , .mediumCricle, .smallCricle {
```suggestion
  .largeCircle , .mediumCircle, .smallCircle {
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +  const {header, recommendation, comment, footer, action, feedback, mode} = props;
```suggestion
  const {header, recommendation, comment, footer, action, feedback, mode='default'} = props;
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +  const {mode, children, failed} = props;
```suggestion
  const {mode='default', children, failed} = props;
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
> +  mode: PropTypes.oneOf(['scorm'])
```suggestion
  mode: PropTypes.oneOf(['scorm', 'default'])
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
> +  mode: PropTypes.oneOf(['scorm'])
```suggestion
  mode: PropTypes.oneOf(['scorm', 'default'])
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
> +    mode
```suggestion
    mode='default'
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
> +  const {failed, corrections, title, subtitle, stars, rank, gameOver, mode} = props;
```suggestion
  const {failed, corrections, title, subtitle, stars, rank, gameOver, mode='default'} = props;
```

2022-08-02 18:47 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
> +const buildClass = (value, success, failed, loading, mode, scormStyle) => {
```suggestion
const buildClass = (value, success, failed, loading, mode='default', scormStyle) => {
```

2022-08-03 08:30 UTC, adamska27 approved these changes

2022-08-03 12:00 UTC, esa-coorp requested changes

2022-08-03 16:10 UTC, esa-coorp approved these changes

2022-08-04 07:34 UTC, merged