[OR] Fetch Slides + Show Slides
CoorpAcademy/components pull request #2289
Opened 2022-08-04 21:01 UTC by StefanoA1

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-04 21:09 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Redux action: FETCH_SLIDE + Show slides](https://trello.com/c/Ng7LlU6D/2684-add-redux-action-fetchslide-show-slides)

2022-08-05 15:41 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/test/helpers/render-component.js
> +  t.is(get('type', json), 'react-native-mock');
to have a more specific error (more on ava level than @ script level).
From:
```
  Error thrown in test:
  TypeError {
    message: 'Cannot read properties of null (reading \'type\')',
  }
```
To:
```
  - undefined
  + 'react-native-mock'
```

2022-08-08 09:36 UTC, jomaora requested changes

2022-08-08 09:36 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/index.native.tsx
> +    return <View />;
@chrisdugne ce changement est ok pour le mobile ?

2022-08-08 09:36 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
> +  apiSlides: PropTypes.shape({
`apiSlides` dans un component ? je ne vois pas où le component utilise ça, et je crains une sorte de adhérence entre le state et le component.

2022-08-08 09:36 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
> +  const currentSlideIndex = useMemo(
Dans quelle mesure on devrait pas passer déjà le `currentSlideIndex` au component ? Là je sens qu'il y a trop de logique encore dans le component, alors qu'il doit être stateless

2022-08-08 10:04 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/slides/index.native.tsx
> +    return <View />;
oui c'est temporaire, il faut considérer que le template mobile est à refaire à 99% (on ne gardera que le style)

2022-08-08 12:09 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/api/fetch-slide.ts
> +        const isFirstSlide = isEmpty(getState().ui.finishedSlides);
C'est que pour les slides UI (les API ont qu'on seul setter), il y a besoin de faire un diff car le 1er état est particulier car il y a pas des animations à programmer, ni position, etc..

2022-08-08 12:18 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
> +  const currentSlideIndex = useMemo(
côté `AppReview` il n'y a pas un access pour direct à la store (getState retourne un object non mutable et donc les hooks ne sont suscrits vraiment a tous les changements internes, donc c'était plus simple de utiliser un couple de hooks pour faire ça en fonction de la progression (api) et les slides (api), c'était là que je les utilise, je garde l'ordre d'insertion dans `slideRefs` (celui de la progression ne me sert pas car pour les animations j'ai besoin de calculer le step un peu à l'avance)

2022-08-08 13:05 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
> +  const currentSlideIndex = useMemo(
Je ne suis pas sur qu'utiliser des hooks soit la bonne approche car le component reste très dépendant. 

Le calcul de cette valeur doit être côté Redux, à partir du state (auquel on a accès) et passé au component en tant que property.

Il y a aussi un truc qui me semble bizarre, et c'est le fait de passer toute la progression en entière au component, alors qu'on a besoin d'elle pour avoir le `isCorrect` (information qu'on peut aussi calculer côté Redux et passer en tant que property, pareil pour `currentSlideRef`. Quand je compare avec l'app-player web, ce player n'a pas besoin de la progression pour faire son taf, on devrait avoir une configuration similaire.

2022-08-12 08:20 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/slides/index.js
> +  const currentSlideIndex = useMemo(
oui, je suis d'accord avec @jomaora ici, il faut avoir un maximum de logique reçue via les props.

2022-08-17 12:06 UTC, jomaora approved these changes

2022-08-17 12:53 UTC, merged