in prog
CoorpAcademy/components pull request #2290
Opened 2022-08-05 15:48 UTC by BEN-HALIMA-Bilel

2022-08-10 15:05 UTC, DjamelSoualmi requested changes

2022-08-10 15:05 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  100% {
pour quoi t'as ajouté de l'espace ?

2022-08-10 15:27 UTC, BEN-HALIMA-Bilel commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +  };
Pour ne pas faire des conditions sur le className je les mis dans une fonctionne et selon la position j' assigne le className et j'ai utilisé Switch pour éviter l'utilisation des if  else

2022-08-10 15:32 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +    requiredSelection
```suggestion
    requiredSelection = false
```

2022-08-10 15:33 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +    details,
```suggestion
    details = '',
```

2022-08-10 15:34 UTC, BEN-HALIMA-Bilel commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +          }}
il faut faire le spread 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/109510491/183945884-e1aa078a-8930-460d-ac93-d516907d0db1.png">

2022-08-10 15:35 UTC, silouone commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +  }
wrap ca dans une fonction getClass = (theme) => { switch (theme) {...}}

2022-08-10 15:37 UTC, silouone commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +    case 'partielUncheck':
cest bizare ca. tu peux pas avoir un theme qui s'apelle coorpmanager et l'autre partielUncheck. niveau nomenclature métier les deux n'ont rien à voir, il faut uniformiser.

2022-08-10 15:38 UTC, silouone requested changes
petit retour

2022-08-10 15:41 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +    requiredSelection = false
pas de fixtures qui prennent en compte ces 2 props ?

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +        <div className={style.btnSwicthContainer}>
```suggestion
        <div className={style.btnSwitchContainer}>
```

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/input-switch/style.css
> +.btnSwicthContainer {
```suggestion
.btnSwitchContainer {
```

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +      <div className={!details ? style.alignedTxtContainer : null}>
```suggestion
      <div className={!details ? style.alignedTextContainer : null}>
```

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/input-switch/style.css
> +.alignedTxtContainer {
```suggestion
.alignedTextContainer {
```

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
> +      <div className={!details ? style.alignedTxtContainer : null}>
pour un caractère

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +    return map.convert({cap: false})((el, index) => (
tu peux aussi déstructurer ici:
``
const {type, title...} = el;
``

2022-08-10 15:56 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +            type: el.type,
après destructuration ce sera plus concis
```suggestion
            type,
            title,
            ...
```

2022-08-11 08:39 UTC, BEN-HALIMA-Bilel commented on packages/@coorpacademy-components/src/atom/input-switch/index.js
>    const className = getClassState(defaultClass, modifiedClass, null, modified);
la fonction getClassState ?

2022-08-12 09:54 UTC, GhaziCoorpacademy approved these changes

2022-08-12 10:00 UTC, silouone approved these changes

2022-08-12 12:27 UTC, merged