App review refactor state
CoorpAcademy/components pull request #2299
Opened 2022-08-12 12:34 UTC by jomaora

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-16 11:48 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/index.tsx
> +      const isProgressionPresent = !isEmpty(store.getState().data.progression);
peut être créer 2 conditions apart, si besoin, pour isProgressionPresent + isSlidePresent, car la 1ere peut être en `true` sans forcement avoir le slide car c'est en train de charger le slide (c'est le cas pour la 1ere slide), et le composant ne vas pas avoir un état correct (ça ce voit en debug pour le TU que j'ai pas encore arrivé à régler)

2022-08-16 11:48 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/index.tsx
> +  const [isProgressionCreated, setIsSlideFetched] = useState(false);
```suggestion
  const [isProgressionCreated, setIsProgressionCreated] = useState(false);
```

2022-08-16 11:55 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +export type SlidesState = Record<string, SlideFromAPI>;
```suggestion
export type SlidesState = {
  slideRefs: string[];
  values: Record<string, SlideFromAPI>;
};
```
on a besoin de la prop slideRefs, c'est un tableau de string refs (vide au début) qui garde l'ordre de fetch des slides (c'est comme ça que on fonction de la current ref on peux calculer la position de la slide) j'ai besoin de ça car un objet ne garanti pas un ordre de insertion des clés et je ne peux pas savoir la position sans ça

2022-08-16 12:24 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/reducers/ui/slides.ts
> +  return pipe(set(['0', 'questionText'], questionText), set(['0', 'answerUI'], answerUI))(state);
ah oui cool avec le set on a tout ça dans le même endroit, nouvel objet inclus 👍🏻

2022-08-16 13:35 UTC, jomaora commented on packages/@coorpacademy-app-review/src/index.tsx
> +      const isProgressionPresent = !isEmpty(store.getState().data.progression);
On va garder juste la progression et on va privilégier l'état loading sur lequel @EmelineLeduc est en train de [travailler](https://trello.com/c/c2aya3Ky/2700-pr%C3%A9voir-%C3%A9tat-loading-pour-laffichage-des-slides-fetchslide).

2022-08-16 13:37 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +export type SlidesState = Record<string, SlideFromAPI>;
L'ordre des slides est disponible dans la progression `state.slides`

2022-08-16 14:07 UTC, StefanoA1 approved these changes

2022-08-16 15:14 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        onClick: (): void => {
on utilisera probablement le `mapDispatchToProps` pour dispach les actions

2022-08-16 15:23 UTC, chrisdugne requested changes

2022-08-16 15:23 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/data/slides.ts
> +      if (has(slide.id, state)) return state;
ce n'est pas ici qu'il faut tester l'existence du slide,
ici on le stocke quoi qu'il arrive: on vient de recevoir un slide, on le met dans le state.
La logique qui definit si on change ou non, si on fetch ou non, doit se trouver au niveau du thunk, dans le `bailout` en l'occurrence

2022-08-16 15:23 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/actions/api/fetch-slide.ts
>        const {ref: slideRef} = get('state.nextContent', progressionFromAPI);
```
buildTask({
 ***,
 bailout: has(slide.id, state),
 })
```

cf mon autre commentaire

2022-08-16 16:44 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        onClick: (): void => {
pour l'instant on n'a pas de `mapDispatchToProps`.. c'est quoi ? Je pensais faire un dispatch de l'action api qui va crée l'answer sur l'api progression

2022-08-17 09:28 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        onClick: (): void => {
oui c'est la meme utilité,
ça simplifie l'utilisation du `dispatch`: tu mappes directement l'action creator coté redux,
puis coté components, quand tu appelles la fonction mappée, `dispatch(action)` est fait automatiquement;

exemple ici: [coté app-review](https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-app-review/src/index.tsx#L38) + [coté components](https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/template/app-review/slides/index.js#L373)

2022-08-17 09:32 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/reducers/ui/current-slide-ref.ts
> +    case SET_FIRST_SLIDE: {
on ne parle plus de la premiere slide uniquement désormais,
`SET_CURRENT_SLIDE` serait plus approprié ?

2022-08-17 09:32 UTC, chrisdugne approved these changes

2022-08-17 11:43 UTC, merged