Review slides loader
CoorpAcademy/components pull request #2305
Opened 2022-08-16 14:26 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR adds a loading state for review slides.
-> https://trello.com/c/c2aya3Ky/2700-pr%C3%A9voir-%C3%A9tat-loading-pour-laffichage-des-slides-fetchslide

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-16 14:32 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prévoir état loading pour l'affichage des slides (FETCH_SLIDE)](https://trello.com/c/c2aya3Ky/2700-pr%C3%A9voir-%C3%A9tat-loading-pour-laffichage-des-slides-fetchslide)

2022-08-17 08:11 UTC, StefanoA1 approved these changes

2022-08-17 08:13 UTC, jomaora requested changes

2022-08-17 08:13 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/index.js
> +        {isNil(slide.answerUI && slide.position === 0) ? (
Tu voulais plutôt dire `isNil(slide.answerUI) && slide.position === 0` peut-être ?

2022-08-17 08:13 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/loading.js
> +    finishedSlides: {
`finishedSlides` a été supprimé des properties

2022-08-17 08:13 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/loading.js
> +    finishedSlidesSize: 1,
Idem, tu pourrais profiter pour faire une vérification dans les autres fixtures et nettoyer, stp

2022-08-17 09:26 UTC, jomaora approved these changes

2022-08-17 09:37 UTC, merged