Fix width container slide and add loading slide
CoorpAcademy/components pull request #2311
Opened 2022-08-18 12:49 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-18 13:20 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[components] Fixer width du container de la slide](https://trello.com/c/yGwCszCR/2708-components-fixer-width-du-container-de-la-slide)

2022-08-18 14:35 UTC, jomaora requested changes
Les max-width en desktop doit être dans tous les div de `slideContentContainer` à 95% et en mobile à 90%. Si on utilise de max-width, on utilise pas alors width.

2022-08-18 15:35 UTC, jomaora approved these changes

2022-08-19 08:37 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/review-slide/index.js
> +        </>
est-ce que tu peux modifier le `<> `et utiliser plutôt un `div`?
```suggestion
        <div>
          <QuestionContainer
            questionOrigin={parentContentTitle}
            questionText={questionText}
            answerUI={answerUI}
          />
          <ValidateButton
            slideIndex={slideIndex}
            validateButton={validateButton}
            primarySkinColor={primarySkinColor}
          />
          <CorrectionPopin
            correctionPopinProps={correctionPopinProps}
            slideIndex={slideIndex}
            showCorrectionPopin={showCorrectionPopin}
            animateCorrectionPopin={animateCorrectionPopin}
          />
        <div/>
```

2022-08-19 09:33 UTC, StefanoA1 approved these changes

2022-08-22 07:53 UTC, merged