Edit UI qcm slide
CoorpAcademy/components pull request #2323
Opened 2022-08-22 15:45 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-22 16:02 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review] Ajouter action to EDIT_QCM](https://trello.com/c/MWB6JJ5k/2710-app-review-ajouter-action-to-editqcm)

2022-08-23 13:17 UTC, jomaora requested changes

2022-08-23 13:17 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +export type EditAction = {
EditAnswerAction

2022-08-23 13:17 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +const newState = (userAnswers: string[], questionType: string, newValue: string): string[] => {
buildAnswer

2022-08-23 13:17 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
> +const setInitialState = (state: StoreState, question: SlideFromAPI): StoreState => {
buildInitialState

2022-08-23 13:17 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
> +  const expectedActions = [{type: ANSWER_EDIT.qcmGraphic, payload: ['My Answer']}];
Essaye d'avoir un scenario où on enlève une valeur de la réponse de l'état initial... quitte à faire une set sur `ui.answers`

2022-08-23 13:17 UTC, jomaora commented on packages/@coorpacademy-app-review/src/test/util/services.mock.ts
> -import {freeTextSlide} from '../../views/slides/test/fixtures/free-text';
laisse freeTextSlide pour Stefano qui a pris ce question pour son dev

2022-08-23 13:40 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +};
```suggestion
export const ANSWER_EDIT = {
  qcm: '@@answer/EDIT_QCM',
  qcmGraphic: '@@answer/EDIT_QCM_GRAPHIC',
  qcmDrag: '@@answer/EDIT_QCM_DRAG',
  template: '@@answer/EDIT_TEMPLATE',
  basic: '@@answer/EDIT_BASIC',
  slider: '@@answer/EDIT_SLIDER'
} as const;
```

2022-08-23 13:55 UTC, jomaora approved these changes

2022-08-23 13:55 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +export const ANSWER_EDIT = {
```ts
const EDIT_QCM = '@@answer/EDIT_QCM' as const;
// idem avec les autres puis

export const ANSWER_EDIT = {
   qcm: EDIT_QCM,
   // les autres
};

export type EditAnswerAction = {
  type: EDIT_QCM | EDIT_BASIC | ...;
  payload: string[];
};
```

2022-08-23 13:56 UTC, jomaora requested changes

2022-08-23 13:56 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +export const ANSWER_EDIT = {
```ts
const EDIT_QCM = '@@answer/EDIT_QCM' as const;
// idem avec les autres puis

export const ANSWER_EDIT = {
   qcm: EDIT_QCM,
   // les autres
};

export type EditAnswerAction = {
  type: EDIT_QCM | EDIT_BASIC | ...;
  payload: string[];
};
```

2022-08-23 15:31 UTC, jomaora approved these changes

2022-08-23 16:06 UTC, esa-coorp requested changes

2022-08-23 16:06 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return includes(newValue, userAnswers)
if (newValue === undefined) return userAnswers;

2022-08-23 16:07 UTC, esa-coorp requested changes

2022-08-23 16:07 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return [];
https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-player-store/src/actions/ui/answers.js#L37-L67

```suggestion
    case 'basic':
    case 'slider':
      return [newValue];
    case 'template':
      return newValue;
    default:
      return [];
```

2022-08-24 08:02 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return [];
@esa-coorp la PR ne traite pas du slider

2022-08-24 08:05 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return includes(newValue, userAnswers)
@esa-coorp dans quel cas on peut avoir une réponse avec un valeur undefined ? Cockpit permet d'exporter des options de réponse undefined ?

2022-08-24 08:28 UTC, merged