Add action EDIT_TEMPLATE
CoorpAcademy/components pull request #2330
Opened 2022-08-25 12:58 UTC by EmelineLeduc

https://trello.com/c/h2YQ3Ufr/2717-app-review-ajouter-action-pour-edittemplate

**Detailed purpose of the PR**
This PR adds action to EDIT_TEMPLATE.
-> https://trello.com/c/h2YQ3Ufr/2717-app-review-ajouter-action-pour-edittemplate

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-25 13:46 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review] Ajouter action pour EDIT_TEMPLATE](https://trello.com/c/h2YQ3Ufr/2717-app-review-ajouter-action-pour-edittemplate)

2022-08-26 14:46 UTC, esa-coorp requested changes

2022-08-26 14:46 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +        : flatten([...userAnswers, newValue[0]]);
```suggestion
      const firstValue = head(newValue);
      return includes(firstValue, userAnswers)
        ? pull(firstValue, userAnswers)
        : flatten([...userAnswers, firstValue]);
```

2022-08-26 14:46 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return newValue;
```suggestion
    case 'template':
      return newValue;
```

2022-08-26 14:46 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/answers.ts
> +      return newValue;
le case `basic`, `slider`, et `template` retourne la même chose

2022-08-26 15:17 UTC, StefanoA1 approved these changes

2022-08-29 08:10 UTC, jomaora approved these changes

2022-08-29 08:10 UTC, merged