Action validate slide
CoorpAcademy/components pull request #2331
Opened 2022-08-25 13:30 UTC by StefanoA1

**Detailed purpose of the PR**

- Adds ACTION

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-25 14:29 UTC, jomaora requested changes

2022-08-25 14:29 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
> +  t.true(props.stack.validateButton.disabled);
Ce cas devrait pas arriver... si on a qqch dans answer, validate button doit être activé

2022-08-25 14:29 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
> +    case SET_VALIDATE_BUTTON_STATUS: {
On peut utiliser directement `POST_ANSWER_REQUEST` pour éviter un double rendu étant donné qui est déclenché pour utiliser `SET_VALIDATE_BUTTON_STATUS`

2022-08-25 14:29 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +          dispatch(setValidateButtonStatus(false));
du coup ça rendait ce dispatch innécessaire

2022-08-25 14:29 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        disabled: !state.ui.slide.validateButton,
vérifier condition

2022-08-25 15:23 UTC, jomaora requested changes

2022-08-25 15:23 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/slides.ts
> +export const setValidateButtonStatus = (payload: boolean): SetValidateButtonStatus => ({
@StefanoA1 cette action n'est plus nécessaire

2022-08-25 15:47 UTC, jomaora approved these changes

2022-08-26 08:41 UTC, EmelineLeduc approved these changes

2022-08-26 08:45 UTC, esa-coorp approved these changes

2022-08-26 08:48 UTC, merged