Add fetch correction service
CoorpAcademy/components pull request #2341
Opened 2022-08-30 15:48 UTC by StefanoA1

**Detailed purpose of the PR**

- Adds fetch correction service + UT, plus type fix

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-30 16:01 UTC, chrisdugne approved these changes

2022-08-31 08:52 UTC, jomaora requested changes

2022-08-31 08:52 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/test/fetch-correction.test.ts
> +  correctAnswer: ['Faux'],
Ta fixture n'est pas cohérente. Il y a pas de 'Faux' dans les réponses envoyées dans le body.

```
correctAnswer: ['15 jours à Bora Bora']
```

2022-08-31 08:54 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/services/test/fetch-correction.test.ts
> +  correctAnswer: ['Faux'],
ah oui j'ai pas mis à jour ça, merci

2022-08-31 08:55 UTC, jomaora approved these changes

2022-08-31 09:07 UTC, merged