Add mocked fetch correction service
CoorpAcademy/components pull request #2343
Opened 2022-08-31 13:26 UTC by StefanoA1

**Detailed purpose of the PR**
- Adds mocked fetch correction service

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-08-31 13:27 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter le Mock service `fetchCorrection` pour la sandbox](https://trello.com/c/k4vnhBpB/2723-ajouter-le-mock-service-fetchcorrection-pour-la-sandbox)

2022-08-31 13:32 UTC, jomaora requested changes

2022-08-31 13:32 UTC, jomaora commented on packages/@coorpacademy-app-review/src/test/util/services.mock.ts
> +const correctionOnRightAnswer: CorrectionFromAPI = {
@Stefano est-ce que tu peux faire la même dynamisation de cette fonction comme pour le `getSlideFixture` ou `postAnswer` ? En gros on devrait pouvoir en fonction de la ref de la slide en cours (ou la progression, à toi de voir ce qui s'adapte le mieux) retourner la bonne correction. Comme ça on a le bon comportement dans la sandbox

si currentSlide est 'freeTextSlide', donc retourner le vrai object de correction, si c'est le qcmSlide... etc

2022-09-01 08:07 UTC, jomaora approved these changes

2022-09-01 08:09 UTC, merged