Adds fetch correction reducer
CoorpAcademy/components pull request #2346
Opened 2022-09-02 12:23 UTC by StefanoA1

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-09-02 14:52 UTC, esa-coorp approved these changes

2022-09-05 12:45 UTC, jomaora requested changes

2022-09-05 12:45 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
>        const state = getState();
sort cette logique du task, et mets là avant l'action

2022-09-05 13:54 UTC, chrisdugne approved these changes

2022-09-05 14:01 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
>        const state = getState();
done 👍🏻

2022-09-05 14:24 UTC, merged

2022-09-05 15:46 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter reducer `data.answers` pour réagir à l'action FETCH_CORRECTION_SUCCESS](https://trello.com/c/eeC2V37d/2727-ajouter-reducer-dataanswers-pour-r%C3%A9agir-%C3%A0-laction-fetchcorrectionsuccess)