clear token passed to mooc's progression endpoints
CoorpAcademy/components pull request #2351
Opened 2022-09-05 15:09 UTC by jomaora

https://trello.com/c/iEXLvm3G/2624-installer-poc-app-review-sur-le-mooc

**Detailed purpose of the PR**

Currently the app-review is passing the JWT token of the connected user to the mooc's api. This is generating a [weird behavior](https://coorpacademy.slack.com/archives/G03TLJ8S6/p1662384279791019) on the onboarding platform.

After a verification with @esa-coorp, we see that token is not sent by app-player services, nor asked by the swagger (the inner logic uses the connected user to compute the good user.id to create the progression and fetch the needed data).

2022-09-05 15:15 UTC, EmelineLeduc approved these changes

2022-09-05 15:21 UTC, StefanoA1 approved these changes

2022-09-05 15:22 UTC, chrisdugne requested changes
attention, c'est necessaire pour l'app mobile;
il faut surement parametrer

2022-09-06 06:35 UTC, esa-coorp approved these changes

2022-09-06 14:17 UTC, closed without merging