[app-review] add actions fetchStartRank and fetchEndRank in postAnswer action
CoorpAcademy/components pull request #2374
Opened 2022-09-14 12:03 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR adds actions fetchStartRank and fetchEndRank in action postAnswer.
-> https://trello.com/c/4QD8oiJT/2748-app-review-faire-appel-%C3%A0-fetchstartrank-et-fetchendrank

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [x] Unit testing

2022-09-14 12:06 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review] Faire appel à fetchStartRank( ) et fetchEndRank( )](https://trello.com/c/4QD8oiJT/2748-app-review-faire-appel-%C3%A0-fetchstartrank-et-fetchendrank)

2022-09-14 12:41 UTC, jomaora requested changes

2022-09-14 12:41 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
> +test('should dispatch post-answer, fetch-slide and fetch-correction and fetch-start-rank actions when the answer is submitted and when the slide type is "type"', async t => {
when the slide type is type 🤔  ?

2022-09-14 12:41 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
> +      progression: {
On a des fixtures déjà pour ces cas... je préfère que tu les réutilises, comme ça on réduit les lignes à lire. Voir dans le fichier `src/test/util/service.mock.ts` la constant `postAnswerResponses`. Tu peux du coup faire ici

```js
progression: postAnswerResponses[sliderSlide.universalRef]
```

2022-09-14 13:29 UTC, jomaora approved these changes

2022-09-15 08:29 UTC, StefanoA1 approved these changes

2022-09-15 08:31 UTC, merged