UI slide refacto
CoorpAcademy/components pull request #2383
Opened 2022-09-16 17:27 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-09-19 15:57 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review] Refactorer ui.slide, ajouter slideRef dans la map pour gestion des props de validateButton + popinCorrection par slide](https://trello.com/c/BkA4ZOxO/2755-app-review-refactorer-uislide-ajouter-slideref-dans-la-map-pour-gestion-des-props-de-validatebutton-popincorrection-par-slide)

2022-09-20 09:09 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/tsconfig.es.json
> +    "**/**/*.test.ts"
*pour pas embarquer les tests dans le build @CoorpAcademy/revision-team

2022-09-20 12:36 UTC, jomaora requested changes

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
> +  validateButton?: boolean;
Il faut que toutes les props de cette type soient mandatory. Pour setter les valeur initial pour chaque slide, il faudra alors gérer l'action `SLIDE_FETCH_REQUEST`

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
> +): SlideState => {
Du coup tu vas devoir ajouter ici un truc du sorte

 ```js
   case SLIDE_FETCH_REQUEST:
      return set(
        [action.meta.slideRef],
        {
          validateButton: false,
          animateCorrectionPopin: false,
          showCorrectionPopin: false
        },
        state
      );
```

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
> +  t.true(state.ui.slide[freeTextSlide._id].animateCorrectionPopin);
changer le test à 

```js
t.deepEqual(state.ui.slide[freeTextSlide._id], ....);
```

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
> +  t.true(state.ui.slide[templateSlide._id].animateCorrectionPopin);
idem, deepEqual

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
> +export type AnswerState = Record<string, UIAnswerState>;
Je préfère que le type soit à l'invers... 

`export type UIAnswerState = Record<string, UISlideAnswer>;`

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
> +export type UIAnswerState = string[];
```js
UISlideAnswer
```

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
> +export type SlideState = Record<string, UISlideState>;
export type UISlideState = Record<string, UISlide>;

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
>  export type UISlideState = {
`UISlide`

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        getOr(false, ['ui', 'slide', currentSlideRef, 'animateCorrectionPopin'], state);
avec le changement que je t'ai proposé, on aura pas besoin du `getOr` car ces values seront toujours présents. Changer par un get.
Et ici c'est aussi `slideRef` et non `currentSlideRef` (on est en train de construire la vue pour la slide dans la stack

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        getOr(false, ['ui', 'slide', currentSlideRef, 'showCorrectionPopin'], state);
idem

2022-09-20 12:36 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +      const answers = getOr([], ['ui', 'answers', currentSlideRef], state);
ici c'est slideRef, pas currentSlideRef

2022-09-20 16:52 UTC, jomaora requested changes

2022-09-20 16:52 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
> +      return pipe(compact, isEmpty)(action.payload)
je crois qu'on peut faire ça autrement...
genre calculer le `pipe(compact, isEmpty)(action.payload)`et assigner la valeur directement sans faire le ternaire, histoire d'alléger la lecture

2022-09-20 16:52 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
> +  const state = reducer(undefined, {type: 'NOPE'} as unknown as FetchSlide);
c'était pas nécessaire de changer ceci, non ?

2022-09-21 08:47 UTC, jomaora approved these changes

2022-09-21 08:50 UTC, merged