Mobile/app review header
CoorpAcademy/components pull request #2394
Opened 2022-09-21 14:39 UTC by chrisdugne

**Detailed purpose of the PR**

- plugged app-review native header steps
- migrated atom review-step-item to be 100% typescript

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-09-22 08:06 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [header -> steps](https://trello.com/c/C6O4f1lG/2771-header-steps)

2022-09-22 11:55 UTC, alanlanglois commented on packages/@coorpacademy-components/src/organism/review-header/index.native.tsx
> +    // backgroundColor: '#ded', // flex-debug
No need in prod?

2022-09-22 11:55 UTC, alanlanglois commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/index.native.tsx
> +    // backgroundColor: '#77f' // flex-debug
same

2022-09-22 11:57 UTC, alanlanglois approved these changes

2022-09-22 12:57 UTC, jomaora requested changes
Pour moi la PR est ok, mais elle ne devrait passer tant que https://github.com/CoorpAcademy/components/pull/2387 ne soit pas passé, histoire de ne pas ajouter plus de dette.

2022-10-03 08:04 UTC, chrisdugne commented
> Pour moi la PR est ok, mais elle ne devrait passer tant que #2387 ne soit pas passé, histoire de ne pas ajouter plus de dette.

c'est rebase @jomaora 👍

2022-10-03 09:22 UTC, jomaora requested changes

2022-10-03 09:22 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/prop-types.ts
> +  Props as ReviewSlideProps,
Je vois un problème ici... 

`CorrectionPopinProps` n'est pas utilisé, mais en plus de ça, il n'est pas définit dans le bon fichier. On a une molecule [ReviewCorrectionPopin](https://github.com/CoorpAcademy/components/tree/master/packages/%40coorpacademy-components/src/molecule/review-correction-popin) où on devrait cette définition et ce component native

2022-10-03 09:27 UTC, jomaora commented
https://coorpacademy.slack.com/archives/GA45KH3UM/p1664788961614129

2022-10-03 09:28 UTC, jomaora approved these changes

2022-10-03 09:35 UTC, merged