[app-review] update `mapStateToProps` and bind the NEXT_SLIDE action to the popin's next button
CoorpAcademy/components pull request #2395
Opened 2022-09-22 14:26 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR updates `mapStateToProps` and binds the NEXT_SLIDE action to the popin's next button.
-> https://trello.com/c/8WfJMpBW/2707-app-review-action-nextslide

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-09-22 16:07 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review] Action NEXT_SLIDE](https://trello.com/c/8WfJMpBW/2707-app-review-action-nextslide)

2022-09-23 09:06 UTC, jomaora requested changes

2022-09-23 09:18 UTC, jomaora approved these changes

2022-09-27 08:24 UTC, StefanoA1 approved these changes

2022-09-27 12:07 UTC, merged