Learner header mode scorm
CoorpAcademy/components pull request #2396
Opened 2022-09-22 16:26 UTC by BEN-HALIMA-Bilel

in scorm mode we remove the go back icon and the go back action :
![Capture d’écran 2022-09-22 à 18 16 36](https://user-images.githubusercontent.com/109510491/191801283-9933286c-86e1-41fc-8f4b-7a1c64159c9f.png)

2022-09-23 07:32 UTC, esa-coorp requested changes

2022-09-23 07:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
> +    <Link
C'est illisible

```
{mode === 'scorm' ? (
    <div className={style.contentWrapperScorm}>
      {content}
    <div/>
):(
   <Link onClick={onClick} className={style.contentWrapper}>
      <BackIcon className={style.backIcon} color="inherit" />
      {content}
    <Link/>)

```

2022-09-23 07:32 UTC, esa-coorp commented on packages/@coorpacademy-player-web/src/map-state-to-props/popin-end.js
> +  };
Comment ça se fait qu'il y ait autant de diff. Ton lint est bien configuré

2022-09-28 10:37 UTC, esa-coorp requested changes

2022-09-28 10:37 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
> +      className={mode === 'scorm' ? style.contentWrapperScorm : style.contentWrapper}
```suggestion
      className={style.contentWrapper}
```

2022-09-28 10:37 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
> +LearnerHeaderWarpper.propTypes = {
```suggestion
LearnerHeaderWrapper.propTypes = {
```

2022-09-28 11:50 UTC, esa-coorp approved these changes

2022-09-28 12:15 UTC, silouone approved these changes

2022-09-28 12:34 UTC, merged