Add Molecule OnQuit Popin to TemplateAppReviewPlayer
CoorpAcademy/components pull request #2401
Opened 2022-09-27 16:00 UTC by antonia2929

This PR is part of this issue :
https://trello.com/c/B6reeZqQ/2772-components-popin-confirmer-quitter-mode-revision

**Detailed purpose of the PR**
Add the popin quit to the template AppReviewPlayer

**Result and observation**
### CHROME
![Capture d’écran 2022-09-27 à 17 57 59](https://user-images.githubusercontent.com/113359769/192576313-f1980fae-77e7-4dee-9cfe-7b8d36cd9f14.png)

### IE

### MOBILE
![Capture d’écran 2022-09-27 à 18 00 08](https://user-images.githubusercontent.com/113359769/192576681-88961842-70d6-4e1b-8b55-ddb7b71c9c24.png)

**Testing Strategy**
- Already covered by tests
- Manual testing

2022-09-27 16:20 UTC, jomaora requested changes

2022-09-27 16:20 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/player/index.js
> +  console.log('onQuitPopinProps');
clean

2022-09-27 16:29 UTC, jomaora commented
@antonia2929 la version IE pour mobile est KO

2022-09-28 12:02 UTC, jomaora approved these changes

2022-09-29 08:46 UTC, jomaora requested changes

2022-09-29 08:46 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/player/prop-types.ts
> +  onQuitPopinProps: PropTypes.shape({...CmPopin.propTypes})
quitPopin

2022-09-29 08:46 UTC, jomaora commented on packages/@coorpacademy-components/src/template/app-review/player/prop-types.ts
> +  congratsProps: PropTypes.shape(ReviewCongratsPropTypes),
congrats

2022-09-29 09:13 UTC, StefanoA1 approved these changes

2022-09-29 09:52 UTC, antonia2929 commented
@jomaora les namings sont changés dans app-review et dans components, j'ai aussi changé le naming congrats dans les tests côté app-review.

2022-09-29 12:06 UTC, jomaora approved these changes

2022-09-29 12:06 UTC, merged