Storybook@6 & Webpack@5
CoorpAcademy/components pull request #2404
Opened 2022-09-28 08:28 UTC by godu

2022-09-29 08:10 UTC, jomaora commented
❤️ storybook 6 !!!

2022-09-29 11:09 UTC, chrisdugne approved these changes

2022-09-29 12:14 UTC, jomaora requested changes
Les components semblent ne pas avoir accès au skin du Provider... (à gauche le storybook de prod en v5, à droit, storyboook v6 de cette PR en local)

<img width="1510" alt="Capture d’écran 2022-09-29 à 14 13 36" src="https://user-images.githubusercontent.com/7602475/193028372-413a4373-72c9-4301-a84e-3714b31482de.png">

2022-09-29 12:14 UTC, jomaora commented on packages/@coorpacademy-components/src/template/battle-requests/index.js
> -          username: battle.username,
pourquoi les supprimer ?

2022-10-03 16:18 UTC, godu commented on packages/@coorpacademy-components/README.md
> +npm run start:ie # for Internet Explorer
Split start command because storybook's addons don't support IE

2022-10-04 08:58 UTC, jomaora approved these changes

2022-10-04 09:00 UTC, merged