Skills/template
CoorpAcademy/components pull request #2411
Opened 2022-10-04 09:37 UTC by alanlanglois

**Detailed purpose of the PR**
Using context in template Skills

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-04 10:01 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EPIC] Dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review)

2022-10-04 10:03 UTC, chrisdugne requested changes

2022-10-04 10:03 UTC, chrisdugne commented on packages/@coorpacademy-components/src/types/translations.ts
> +      noSkillsDetails?: string;
il faut sync les keys avec https://github.com/CoorpAcademy/mobile/pull/770

2022-10-06 10:54 UTC, alanlanglois commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EPIC] Dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review)

2022-10-06 11:59 UTC, chrisdugne approved these changes

2022-10-06 11:59 UTC, merged