Add quit popin app review
CoorpAcademy/components pull request #2413
Opened 2022-10-04 12:32 UTC by antonia2929

This PR is part of this issue : 
https://trello.com/c/JfLUQPe8/2765-app-review-afficher-popin-de-validation-de-quit-mode-review

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-04 13:52 UTC, StefanoA1 requested changes
Some minor proposals (type import + casing)

2022-10-04 13:52 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +type quitPopinPayload = {
favour PascalCase for the types over camelCase
```suggestion
type QuitPopinPayload = {
```

2022-10-04 13:52 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/test/quit-popin.test.ts
> +import {StoreState} from '../../../reducers';
```suggestion
import type {StoreState} from '../../../reducers';
```

2022-10-04 13:52 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/reducers/ui/index.ts
> +import showQuitPopin, {ShowQuitPopinState} from './quit-popin';
```suggestion
import showQuitPopin, {type ShowQuitPopinState} from './quit-popin';
```

2022-10-04 13:52 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/reducers/ui/test/quit-popin.test.ts
> +import {CLOSE_POPIN, OPEN_POPIN, QuitPopinAction} from '../../../actions/ui/quit-popin';
```suggestion
import {CLOSE_POPIN, OPEN_POPIN, type QuitPopinAction} from '../../../actions/ui/quit-popin';
```

2022-10-04 14:05 UTC, StefanoA1 approved these changes

2022-10-04 14:48 UTC, esa-coorp requested changes

2022-10-04 14:48 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +  }
je pense que le payload est inutile. le type suffit

2022-10-04 14:48 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +  }
je pense que le payload est inutile. le type suffit

2022-10-04 14:48 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/reducers/ui/quit-popin.ts
> +    }
```suggestion
    case CLOSE_POPIN:
      return false;
    case OPEN_POPIN: {
      return true;
    }
```

2022-10-04 14:48 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +    quitPopin: showQuitPopin === true ? buildQuitPopinProps(dispatch)(onQuitClick) : undefined
```suggestion
    quitPopin: showQuitPopin && buildQuitPopinProps(dispatch)(onQuitClick)
```

2022-10-04 14:50 UTC, StefanoA1 commented
coverage

2022-10-04 14:53 UTC, jomaora requested changes

2022-10-04 14:53 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +type QuitPopinTypes = {
renommer à `QuitPopinButton`

2022-10-04 14:53 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
> +      showQuitPopin: false
Dans ce fichier, il manque un test avec un state qui va afficher la popin.

2022-10-04 14:54 UTC, StefanoA1 requested changes

2022-10-04 14:54 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +});
```suggestion
export const openQuitPopin = {
  type: OPEN_POPIN
};
```

2022-10-04 14:54 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +});
```suggestion
export const closeQuitPopin = {
  type: CLOSE_POPIN,
};
```

2022-10-04 14:54 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/test/quit-popin.test.ts
> +  await dispatch(openQuitPopin());
```suggestion
  await dispatch(openQuitPopin);
```

2022-10-04 14:54 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/ui/test/quit-popin.test.ts
> +  await dispatch(closeQuitPopin());
```suggestion
  await dispatch(closeQuitPopin);
```

2022-10-04 14:54 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
> +  }
certes

2022-10-04 15:03 UTC, jomaora requested changes
Je ferais un fichier test dans `views/slides/test/on-quit-popin.con-click.test.js` pour tester les onClick sur les boutons `Continuer` et `Arreter` une fois qu'on a un state qui affiche la popin.

Regarde le test `src/views/slides/test/slide.next-slide.on-click.test.ts` et comprend sa fonction, et tu peux t'inspirer de lui

2022-10-06 10:16 UTC, esa-coorp approved these changes

2022-10-06 13:10 UTC, jomaora requested changes

2022-10-06 13:10 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +    quitPopin: showQuitPopin === true ? buildQuitPopinProps(dispatch)(onQuitClick) : undefined
pas besoin de `===`

2022-10-06 13:10 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
> +  t.pass();
ici il faut valider qu'apres le click, les nouvelles props ont maintenant la popin de quit (qu'avant devait être undefined, donc aussi à tester avec la ligne 40)

2022-10-06 13:12 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
> +  const quitPopin = props.quitPopin as QuitPopinProps;
```suggestion
  const quitPopin: QuitPopinProps = props.quitPopin;
```

2022-10-06 13:13 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
> +  const quitPopin = props.quitPopin as QuitPopinProps;
same

2022-10-06 13:15 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
> +  const quitPopin = props.quitPopin as QuitPopinProps;
Je crois pas que là, ça marche... pour moi le `as` on l'utilise pour forcer le cast, quand on sait que à cet endroit du code, l'object est bien de tel type (genre, là, on sait qu'il n'est pas undefined parce qu'on a passé un state avec les données nécessaire pour qu'il ne le soit pas). 

À tester ta proposition, si ça marche, en effet je préfère ta syntaxe pour uniformiser.

2022-10-06 15:36 UTC, jomaora approved these changes

2022-10-06 16:06 UTC, merged