app review middleware "on view change"
CoorpAcademy/components pull request #2414
Opened 2022-10-04 16:35 UTC by chrisdugne

**Detailed purpose of the PR**

- added middleware to call outer reaction from app-review.

the goal is to use a callback from the client side (app mobile for example) whenever the current `viewName` is changed, to trigger outer changes (show/hide header/footer for example)

2022-10-07 14:51 UTC, StefanoA1 approved these changes

2022-10-10 14:57 UTC, jomaora requested changes

2022-10-10 14:57 UTC, jomaora commented on packages/@coorpacademy-app-review/src/middlewares/on-view-change.test.ts
> +    showQuitPopin: false
il manque un rebase, il y a eu des changements dans le state entre temps > `showCongrats`

2022-10-10 14:57 UTC, jomaora commented on packages/@coorpacademy-app-review/src/configure-store.ts
> +  if (options.callbackOnViewChanged) {
est-il vraiment nécessaire de passer par un middleware pour lancer cet action ?
J'ai l'impression de revenir sur un des stage initiaux du POC où plein d'actions étaient gérés par le middleware, alors qu'on a acté déjà qu'on va pas utiliser ce format [ici](https://github.com/CoorpAcademy/components/pull/2266). 

Pour rester homogène avec le reste, on pourrait plutôt passer par une action.

2022-10-11 10:32 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/player/prop-types.ts
> +  congrats?: PropTypes.InferProps<typeof ReviewCongratsPropTypes>;
ça fonctionne assez mal je trouve oui, mais en attendant de faire ces elements de vue et leurs types, (toujours en todo coté mobile) c'est mieux qu'un `unknown`

2022-10-11 14:15 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/configure-store.ts
> +  if (options.callbackOnViewChanged) {
done

2022-10-11 14:15 UTC, chrisdugne commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/prop-types.ts
> +  correctionPopinProps: CorrectionPopinProps;
https://github.com/CoorpAcademy/components/pull/2414/commits/60380e85e7cb3666e4878b7dd482d55335730002

2022-10-11 14:15 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/configure-store.ts
> +  if (options.callbackOnViewChanged) {
https://github.com/CoorpAcademy/components/pull/2414/commits/b944dfc7fdb741fa84e8eac2c06eeac417605afc

2022-10-11 18:45 UTC, chrisdugne commented
#2439

2022-10-11 18:45 UTC, closed without merging