components > types
CoorpAcademy/components pull request #2420
Opened 2022-10-07 13:37 UTC by chrisdugne

**Detailed purpose of the PR**

- exporting components types in `/es`

2022-10-07 22:23 UTC, alanlanglois approved these changes

2022-10-10 08:44 UTC, godu requested changes
Tu n'as pas besoin de définir un nouveau tsconfig

2022-10-10 08:44 UTC, godu commented on packages/@coorpacademy-components/package.json
> +    "build:es:types": "tsc -p tsconfig.es.json",
```suggestion
    "build:es:types": "tsc --module es2020 --outDir es --emitDeclarationOnly --noEmit false",
```

Il faudrait generer aussi les types pour commonjs

2022-10-10 09:03 UTC, chrisdugne commented on packages/@coorpacademy-components/package.json
> +    "build:es:types": "tsc -p tsconfig.es.json",
ok 👍

2022-10-10 15:56 UTC, godu approved these changes

2022-10-11 07:23 UTC, merged