Typscript eslint
CoorpAcademy/components pull request #2428
Opened 2022-10-10 12:53 UTC by chrisdugne

**Detailed purpose of the PR**

- added eslint check on typescript files
- applied eslint + types fixes

2022-10-10 13:22 UTC, godu approved these changes

2022-10-10 13:22 UTC, godu commented on packages/@coorpacademy-components/src/atom/provider/web-context.tsx
> +  children: unknown;
```suggestion
  children: ReactNode;
```

c'est pas mieux ?

2022-10-10 13:22 UTC, godu commented on packages/@coorpacademy-components/src/variables/theme.native.ts
> +  background?: unknown;
```suggestion
  background?: string;
```

2022-10-10 14:27 UTC, chrisdugne commented on packages/@coorpacademy-components/src/atom/provider/web-context.tsx
> +  children: unknown;
👍

2022-10-10 16:44 UTC, jomaora requested changes
Il faudrait établir déjà une hiérarchie claire pour l'utilisation des extension en typescript sur les fichiers du projet...

https://coorpacademy.slack.com/archives/GA45KH3UM/p1665418576201629?thread_ts=1665143155.566889&cid=GA45KH3UM

L'information est contradictoire est rend difficile la lecture des PRs.
Dispo pour en discuter et établir un guideline sur lequel on doit se tenir.

2022-10-10 16:44 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-slide/index.native.tsx
> +import {getOr} from 'lodash/fp';
why ?

2022-10-10 16:44 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-header-step-item/index.native.tsx
> +  const [style, setStyle] = useState<StyleSheetType | null>(null);
nos components sont censés être statesless... pourquoi faire ceci ?

2022-10-10 16:44 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/review-header-step-item/index.native.tsx
>      const _style = createStyle(current, icon);
dans quel cas on aurait pas de style ? Est-ce que si jamais on avait ce cas, on peut pas juste mettre par default 'no-answer'... c'est le cas de tous les default des swicth, du coup, je ne vois pas le besoin de ce bloc. (peut-être que qqch m'échappe)

2022-10-11 07:26 UTC, chrisdugne commented on packages/@coorpacademy-components/src/atom/review-header-step-item/index.native.tsx
> +  const [style, setStyle] = useState<StyleSheetType | null>(null);
ce n'est pas un etat applicatif, c'est un etat local pour ne pas recréer le `Stylesheet` à chaque render

2022-10-11 07:30 UTC, chrisdugne commented on packages/@coorpacademy-components/src/atom/review-header-step-item/index.native.tsx
>      const _style = createStyle(current, icon);
ici `style` est un `ReactNative.Stylesheet`, il n'est pas créé au premier render, et donc null à ce moment.
cela dit ta remarque me fait penser à:
- effectivement on peut peut-etre creer un stylesheet au premier render
- mais aussi peut etre qu'un `useMemo` est plus approprié pour gérer ces `Stylesheet`. Je peux me pencher sur le sujet sur une autre PR car c'est un comportement qui est mis en place sur de nombreux composants `native`.

2022-10-11 07:31 UTC, chrisdugne commented
> Il faudrait établir déjà une hiérarchie claire pour l'utilisation des extension en typescript sur les fichiers du projet...
> 
> https://coorpacademy.slack.com/archives/GA45KH3UM/p1665418576201629?thread_ts=1665143155.566889&cid=GA45KH3UM
> 
> L'information est contradictoire est rend difficile la lecture des PRs. Dispo pour en discuter et établir un guideline sur lequel on doit se tenir.

c'est le but d'eslint et de ses rules: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

2022-10-12 10:18 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [app-review -> types + eslint](https://trello.com/c/GfaKo7Fb/2791-app-review-types-eslint)

2022-10-12 19:58 UTC, chrisdugne commented
> > Il faudrait établir déjà une hiérarchie claire pour l'utilisation des extension en typescript sur les fichiers du projet...
> > https://coorpacademy.slack.com/archives/GA45KH3UM/p1665418576201629?thread_ts=1665143155.566889&cid=GA45KH3UM
> > L'information est contradictoire est rend difficile la lecture des PRs. Dispo pour en discuter et établir un guideline sur lequel on doit se tenir.
> 
> c'est le but d'eslint et de ses rules: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

concernant la différentiation `ts/tsx` je te citais simplement l'exemple des icones dans l'IDE, mais ça va plus loin @jomaora 

- "using JSX for Javascript with React syntax and TSX for TypeScript with React because most editors/IDEs will use the extension to enable or not the React syntax."
- "It's kind of a convention to use x in the end when your JavaScript is in JSX Harmony mode. " --> un dev exterieur s'attend à voir du jsx dans les `.tsx`
- l'outillage typescript + eslint est prévu pour ce setup, choisir de faire autrement demande de la configuration supplémentaire
- https://www.arahansen.com/when-to-use-ts-and-tsx-file-extensions/

bref, je reviens sur ce que je te disais: je pense qu'il vaut mieux utiliser `.tsx`

2022-10-12 20:01 UTC, chrisdugne commented on packages/@coorpacademy-components/src/atom/review-header-step-item/index.native.tsx
>      const _style = createStyle(current, icon);
https://github.com/CoorpAcademy/components/issues/2443

2022-10-13 12:43 UTC, jomaora approved these changes

2022-10-13 12:44 UTC, merged