add fetch-slides-by-skill service and unit test
CoorpAcademy/components pull request #2430
Opened 2022-10-10 14:15 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-10 14:23 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review][Congrats] Bouton continue revising and revise another skill](https://trello.com/c/sSB2gDPW/2785-app-reviewcongrats-bouton-continue-revising-and-revise-another-skill)

2022-10-10 14:29 UTC, StefanoA1 approved these changes

2022-10-10 14:46 UTC, jomaora requested changes

2022-10-10 14:46 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/fetch-slides-by-skill.ts
> +      headers: {authorization: token}
pas de token

2022-10-10 14:46 UTC, jomaora commented on packages/@coorpacademy-app-review/src/services/test/fetch-slides-by-skill.ts
> +const url = process.env.URL_TEST || 'http://localhost:3000';
renommer en `LAMBDA_API_REVIEW_GET_SLIDES_URL`
et mettre `"http://localhost:7006"` qui correspond au port utilisé par l'api-review en local dans le mooc. (3000 fait penser au mooc !)

2022-10-10 15:13 UTC, esa-coorp requested changes

2022-10-10 15:13 UTC, esa-coorp commented on packages/@coorpacademy-app-review/src/test/index.test.tsx
> +  url: process.env.URL_TEST || ''
idem

2022-10-10 15:52 UTC, esa-coorp approved these changes

2022-10-11 08:13 UTC, jomaora requested changes

2022-10-11 09:37 UTC, jomaora approved these changes

2022-10-11 09:38 UTC, merged