Add eng translate app review
CoorpAcademy/components pull request #2435
Opened 2022-10-11 14:13 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-12 08:18 UTC, StefanoA1 requested changes

2022-10-12 08:18 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +    congrats: buildCongratsProps(state, options.translate),
```suggestion
    congrats: buildCongratsProps(state, translate),
```

2022-10-13 14:50 UTC, jomaora requested changes

2022-10-13 14:50 UTC, jomaora commented on packages/@coorpacademy-app-review/locales/en/review.json
> +    "Content Parent Title": "From `{{contentTitle}}``{{contentType}}`",
il faut un espace en anglais pour ça, sinon `title` et `course` va être collé

2022-10-13 14:50 UTC, jomaora commented on packages/@coorpacademy-app-review/sandbox/index.tsx
> +};
laisse un espace toujours entre fonctions

2022-10-13 14:50 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/provider/web-context.tsx
> +  children: ReactNode;
Je suis étonné de voir cette ligne dans les diff, surtout que sur master, elle est déjà changée.

2022-10-13 16:06 UTC, jomaora approved these changes

2022-10-13 16:35 UTC, StefanoA1 approved these changes

2022-10-14 14:22 UTC, merged