Migrating Skills / onboarding template
CoorpAcademy/components pull request #2444
Opened 2022-10-13 08:40 UTC by alanlanglois

**Detailed purpose of the PR**
Linking all the missing props, and using templateContext for theme, translation, etc. 

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-13 19:37 UTC, alanlanglois commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EPIC] Dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review)

2022-10-14 08:46 UTC, chrisdugne requested changes

2022-10-14 08:46 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/onboarding/test/on-press.tsx
> +test('handles onPress on button', t => {
il faut mettre des `/fixtures` pour tester les différents rendering possibles

2022-10-14 08:46 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/onboarding/index.native.tsx
> +      <Tip Icon={TargetIcon} text={translations.appReview?.onboarding?.tip4} />
il y a 4 icons différents sur figma: https://www.figma.com/file/67Fqxp9Y80ZEaUTFqsMyhr/App-Outils-Revision?node-id=21%3A370

2022-10-14 08:51 UTC, chrisdugne commented on packages/@coorpacademy-components/src/types/translations.ts
> +      button?: string;
il faudrait une PR sur le mooc ou app-review pour ajouter les trads

2022-10-14 09:05 UTC, chrisdugne commented on packages/@coorpacademy-components/src/types/translations.ts
> +      button?: string;
on va egalement les dupliquer sur app-review pour centraliser sur 1 namespace qu'on pull via le script de synchro des trads

2022-10-14 09:07 UTC, chrisdugne commented on packages/@coorpacademy-components/src/types/translations.ts
> +      button?: string;
cf discussion ici https://coorpacademy.slack.com/archives/GA45KH3UM/p1665737439031459

2022-10-14 19:44 UTC, alanlanglois commented on packages/@coorpacademy-components/src/template/app-review/onboarding/index.native.tsx
> +      <Tip Icon={TargetIcon} text={translations.appReview?.onboarding?.tip4} />
Fixé, j'avais pas fais le lien entre les noms figma et nova.

2022-10-14 19:44 UTC, alanlanglois commented on packages/@coorpacademy-components/src/template/app-review/onboarding/test/on-press.tsx
> +test('handles onPress on button', t => {
on a déjà une fixture web, mais j'en ai ajouté une mobile (peut être pas utile du coup ?)

2022-10-14 19:45 UTC, alanlanglois commented on packages/@coorpacademy-components/src/types/translations.ts
> +      button?: string;
ok fixé.

2022-10-18 08:13 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/onboarding/test/on-press.tsx
> +test('handles onPress on button', t => {
ah oui je ne l'avais pas vue;
alors effectivement il ne faut pas la dupliquer, mais plutot deplacer le type `OnboardingProps`

dans https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/atom/review-presentation/prop-types.js

et bien typer la fixture en utilisant ce type (comme ici par exemple https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/template/app-review/test/fixtures/onboarding.ts#L5)

2022-10-18 15:25 UTC, chrisdugne approved these changes

2022-10-18 15:26 UTC, merged