[app-review] update stateMapToProps
CoorpAcademy/components pull request #2457
Opened 2022-10-20 14:28 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR updates `stateMapToProps` and dispatches `POST_PROGRESSION_REQUEST` action on click. On this action, the state is reset.
-> https://trello.com/c/sSB2gDPW/2785-app-reviewcongrats-bouton-continue-revising-and-revise-another-skill

![Kapture 2022-10-20 at 16 20 44](https://user-images.githubusercontent.com/79636283/196976777-29a29dde-d51d-4f49-b4af-9328ebb091f0.gif)

**Testing Strategy**

- [ ] Already covered by tests
- [x] Manual testing
- [ ] Unit testing

2022-10-20 14:29 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app-review][Congrats] Bouton continue revising and revise another skill](https://trello.com/c/sSB2gDPW/2785-app-reviewcongrats-bouton-continue-revising-and-revise-another-skill)

2022-10-20 16:07 UTC, jomaora requested changes

2022-10-20 16:07 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/index.ts
> +        'aria-label': 'Continue revising button',
utilise translate (ajoute aussi le trads ;)) voit avec @antonia2929

2022-10-21 12:02 UTC, StefanoA1 approved these changes

2022-10-21 12:14 UTC, jomaora approved these changes

2022-10-21 12:14 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/ui/test/show-congrats.test.ts
> +  const state = reducer(true, {type: POST_PROGRESSION_REQUEST} as FetchProgression);
cet as n'est pas nécessaire

2022-10-21 12:15 UTC, merged