[app-review] update mapStateToSkillsProps
CoorpAcademy/components pull request #2461
Opened 2022-10-24 16:10 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR updates `mapStateToSkillsProps` and unit test.
-> https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review

**Result and observation**
<img width="1435" alt="Screenshot 2022-10-24 at 18 09 08" src="https://user-images.githubusercontent.com/79636283/197573664-6daddf16-51dc-4b22-ba3f-ea339a6bc32e.png">

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [x] Unit testing

2022-10-24 16:10 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EPIC] Dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review)

2022-10-25 08:15 UTC, chrisdugne approved these changes

2022-10-25 09:08 UTC, StefanoA1 approved these changes

2022-10-25 09:31 UTC, jomaora commented on packages/@coorpacademy-app-review/src/test/util/services.mock.ts
> +import {mockTranslate} from '@coorpacademy/translate';
👍

2022-10-25 09:38 UTC, jomaora requested changes

2022-10-25 09:38 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/skills/index.ts
> +    iconSkillAriaLabel: 'Image without information'
@chrisdugne ça doit pas matcher les props définies dans ce dev d'Alan > https://github.com/CoorpAcademy/components/pull/2411

2022-10-25 09:50 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/views/skills/index.ts
> +    iconSkillAriaLabel: 'Image without information'
pour l'instant on lit directement dans `translations` coté native
https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-components/src/template/app-review/skills/index.native.tsx#L182-L183

2022-10-25 09:54 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/views/skills/index.ts
> +    iconSkillAriaLabel: 'Image without information'
Dans le composant web, un aria-label est ajouté au niveau de l'image, mais pas dans le composant mobile. Il faudrait donc soit l'enlever au niveau du composant web, soit l'ajouter au niveau du composant mobile.

2022-10-25 12:01 UTC, jomaora requested changes

2022-11-15 09:57 UTC, jomaora approved these changes

2022-11-15 09:58 UTC, merged