Fetch skill action
CoorpAcademy/components pull request #2464
Opened 2022-10-26 16:09 UTC by antonia2929

Part of this trello card : https://trello.com/c/swIZN13h/2800-app-review-afficher-le-nom-de-la-skill-choisie-dans-le-player

**Detailed purpose of the PR**
- add actions types : @skill/FETCH_REQUEST, @skill/FETCH_SUCCESS, @skill/FETCH_FAILURE
- Add unit test for fetch skill action

**Result and observation**
<img width="1680" alt="Capture d’écran 2022-10-26 à 18 08 48" src="https://user-images.githubusercontent.com/113359769/198078290-b540bffe-ef22-4f9d-a098-fb5cedec53c9.png">

**Testing Strategy**
- Unit testing

2022-10-27 13:09 UTC, StefanoA1 requested changes

2022-10-27 13:09 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/index.tsx
> +
Je pense que tu peux en profiter de l'useEffect de la ligne 60 car tu check les mêmes condition que pour celles de la token
```suggestion
```
Donc tu peux déplacer les lignes:
```
    const skillRef = get('skillRef', options);
    skillRef && store.dispatch(fetchSkill(skillRef));
```
là

2022-10-27 15:22 UTC, StefanoA1 approved these changes

2022-10-31 09:38 UTC, jomaora requested changes

2022-10-31 09:38 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/fetch-skill.test.ts
> +    {type: SKILL_FETCH_FAILURE, payload: new Error('Fetch skill action failed')}
c'est pas normal qu'on ait dans le même test l'action REQUEST > SUCCESS > FAILURE. (Si tu enlèves FAILURE le test passe - parce qu'en réalité, ce cas n'arrive jamais)

C'est soit REQUEST > SUCCESS, soit REQUEST > FAILURE.

Il manque alors un test pour le cas FAILURE. Tu peux t'inspirer de [celui-ci](https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts#L116).

2022-10-31 09:38 UTC, jomaora commented on packages/@coorpacademy-app-review/src/index.tsx
> +    skillRef && store.dispatch(fetchSkill(skillRef));
je préfère que le dispatch de cette action soit fait à la suite de [cette instruction](https://github.com/CoorpAcademy/components/blob/master/packages/%40coorpacademy-app-review/src/actions/api/post-progression.ts#L39). Tu devras mettre à jour des test suite à cette modification.

2022-10-31 10:41 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/actions/api/fetch-skill.ts
> +export type fetchSkillAction = {
Dans un souci d'uniformisation,  `ReceivedSkill` plutôt que 'fetchSkillAction'

2022-10-31 10:41 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/actions/api/fetch-skill.ts
> +  (dispatch: Dispatch, getState: () => StoreState, {services}: ThunkOptions): fetchSkillAction => {
`ReceivedSkill`

2022-10-31 10:42 UTC, EmelineLeduc requested changes

2022-10-31 10:42 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/actions/api/fetch-skill.ts
> +export type fetchSkillAction = {
Dans un souci d'uniformisation, ReceivedSkill plutôt que 'fetchSkillAction'

2022-10-31 10:42 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/actions/api/fetch-skill.ts
> +  (dispatch: Dispatch, getState: () => StoreState, {services}: ThunkOptions): fetchSkillAction => {
`ReceivedSkill`

2022-10-31 13:05 UTC, EmelineLeduc approved these changes

2022-10-31 14:04 UTC, jomaora approved these changes

2022-10-31 14:08 UTC, merged