Component skills mobile
CoorpAcademy/components pull request #2467
Opened 2022-10-27 13:26 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-10-27 14:47 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EPIC] Dasboard skills sur app-review](https://trello.com/c/RQQqx5uR/2656-epic-dasboard-skills-sur-app-review)

2022-10-28 13:21 UTC, chrisdugne requested changes

2022-10-28 13:21 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
> +    'aria-label': '@todo aria-label',
plutot que `@todo` tu peux mettre `mock` ou `__` pour les fixtures

2022-10-28 13:21 UTC, chrisdugne commented on packages/@coorpacademy-components/src/organism/review-skills/prop-types.ts
> +  'aria-label': string;
pas convaincu du `NoSkillsProps &` ici ?

quand il n'y a pas de skills, on doit etre dans un composant dédié à ces textes;

et quand il y en a, on a des `listSkills`

2022-10-28 13:21 UTC, chrisdugne commented on packages/@coorpacademy-components/src/molecule/skill-card/prop-types.ts
> +export type SkillProps = Omit<SkillCardProps, 'aria-label' | 'buttonLabel' | 'isCustom'>;
j'ai du mal à voir quel composant utilise `SkillCardProps` et quel composant utilise `SkillProps` :s 
on peut unifier peut etre ?

2022-10-28 14:19 UTC, chrisdugne commented on packages/@coorpacademy-components/src/organism/review-skills/prop-types.ts
> +  'aria-label': string;
ok c'est le cas 👍

2022-10-28 15:31 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/skill-card/prop-types.ts
> +export type SkillProps = Omit<SkillCardProps, 'aria-label' | 'buttonLabel' | 'isCustom'>;
En fait la molécule `SkillCard` en mobile n’a pas besoin de recevoir toutes les props : aria-label' | 'buttonLabel' | 'isCustom’ ne sont pas utiles.
Le composant parent, l’organisme `ReviewListSkills`, reçoit toutes les props (l.70 `{listSkills: Array<**SkillCardProps**>}`), mais il retourne les données formatées (avec juste les clés nécessaires pour le mobile) ->  (l. 85,   `const formattedDataList: Array<**SkillProps**>` ).  
Mais si tu préfères je peux unifier ;) Par contre, en faisant ça, je vais supprimer la variable` formattedDataList` qui du coup n’a plus lieu d’être.

2022-10-28 15:45 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/organism/review-skills/prop-types.ts
> +  'aria-label': string;
Ok, je vais donc créer un organisme `ReviewNoSkills`, puis l’appeler dans le template `Skills` qui affichera l’organisme `ReviewSkills` ou `ReviewNoSkills` selon la condition. 
(Je vais aussi adapter le comportement de ce composant pour le web en suivant le même principe).

2022-11-02 10:45 UTC, StefanoA1 approved these changes

2022-11-02 10:52 UTC, chrisdugne approved these changes

2022-11-02 12:36 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-skills/prop-types.ts
> +  item: SkillCardProps;
Ce sont pas les mêmes props, déplace le type

```js
export type ReviewSkills = {listSkills: SkillCardProps[]}
```

que t'as mis directement dans le component natif, ligne 37

2022-11-02 13:26 UTC, StefanoA1 approved these changes

2022-11-02 13:53 UTC, merged