Add placeholder translation in app-review
CoorpAcademy/components pull request #2481
Opened 2022-11-08 15:25 UTC by antonia2929

Trello card : [[OR] Placeholder des questions en EN sur des questions FR](https://trello.com/c/UXtgG9On/2829-or-placeholder-des-questions-en-en-sur-des-questions-fr)

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-11-08 16:23 UTC, jomaora requested changes

2022-11-08 16:23 UTC, jomaora commented on packages/@coorpacademy-app-review/sandbox/index.tsx
> +  console.log('type of data', typeof data);
clean

2022-11-09 07:00 UTC, esa-coorp approved these changes

2022-11-09 09:24 UTC, jomaora approved these changes

2022-11-09 09:26 UTC, merged