Replace broken Url media template slide
CoorpAcademy/components pull request #2499
Opened 2022-11-21 15:42 UTC by scalabw

**Detailed purpose of the PR**

https://trello.com/c/vgAtLg9I/2860-fix-template-slide-broken-layout

This PR fix the broken layout on Storybook for the Template slide

**Result and observation**

Before:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/22681512/203096670-b642eccf-309a-4523-b46d-6a3194e18f5e.png">

After:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/22681512/203096209-66a68797-5852-4ff6-9e7a-43672f314a18.png">

2022-11-21 15:51 UTC, jomaora requested changes
@scalabw I think you should still use the api-media service

2022-11-21 15:52 UTC, StefanoA1 approved these changes

2022-11-21 15:53 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/answer/test/fixtures/template.ts
> +      title: 'coucou'
```suggestion
```

2022-11-21 15:54 UTC, StefanoA1 requested changes

2022-11-21 15:54 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/answer/test/fixtures/template.ts
> +      title: 'coucou'
```suggestion
      title: 'coucou'
```

2022-11-21 16:19 UTC, StefanoA1 approved these changes

2022-11-22 09:36 UTC, jomaora approved these changes

2022-11-22 13:14 UTC, merged