create package review services
CoorpAcademy/components pull request #2501
Opened 2022-11-22 13:23 UTC by scalabw

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-11-22 15:21 UTC, StefanoA1 requested changes

2022-11-22 15:21 UTC, StefanoA1 commented on packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
> +import {ThunkOptions} from 'src/types/common';
```suggestion
import type {ThunkOptions} from 'src/types/common';
```

2022-11-22 15:28 UTC, StefanoA1 approved these changes

2022-11-22 15:56 UTC, StefanoA1 approved these changes

2022-11-23 14:00 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.json
> +    "esModuleInterop": true,
je pense que tu peux enlever ça (pas de tsx/jsx)

2022-11-23 14:00 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.json
> +    "jsx": "preserve",
pareil

2022-11-23 14:02 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.json
> +    "esModuleInterop": true,
you can take this out (no tsx/jsx)
```suggestion
```

2022-11-23 14:02 UTC, chrisdugne commented on packages/@coorpacademy-app-review/package.json
> +  "version": "0.10.1-alpha.0",
attention, tu as du faire une `canary`, il ne faut pas commit cette version

2022-11-23 14:02 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.json
> +    "jsx": "preserve",
same, no jsx
```suggestion
```

2022-11-23 14:02 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.json
> +    "allowJs": true,
no js
```suggestion
```

2022-11-23 14:04 UTC, StefanoA1 commented on packages/@coorpacademy-review-services/tsconfig.lib.json
> +  },
```suggestion
    "outDir": "lib",
    "incremental": true,
    "noErrorTruncation": true
  },
```

2022-11-23 14:08 UTC, godu requested changes

2022-11-23 14:11 UTC, chrisdugne commented on packages/@coorpacademy-review-services/package.json
> +    "node": ">=12.22.12"
```
    "node": ">=16.15.0"
```
= version de node des autres packages

2022-11-25 13:42 UTC, jomaora requested changes

2022-11-25 13:42 UTC, jomaora commented on packages/@coorpacademy-app-review/src/actions/api/test/fetch-slides-to-review-by-skill-ref.test.ts
> +  postAnswerResponses,
il y a des objets qui sont dans services-mock et qui ne devrait plus l'être
postAnswerResponses (l:98) et incorrectFreeTextPostAnswerResponse (l:307) de l'index. Déplace le vers app-review. Merci

2022-11-28 12:39 UTC, scalabw commented on packages/@coorpacademy-app-review/src/actions/api/test/fetch-slides-to-review-by-skill-ref.test.ts
> +  postAnswerResponses,
done !

2022-11-28 13:48 UTC, jomaora requested changes

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
> +import {postAnswerResponses, postProgressionResponse} from '@coorpacademy/review-services-mocks';
il y a encore un `postAnswerResponses`

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/test/index.test.tsx
> +import {sleep} from '@coorpacademy/review-services/es/tools/sleep';
`sleep` should not be exported by the `review-services` lib (it's not a service). Please check if this function is used internally by the `review-services`. If not, the function must be deleted there and defined here (for internal use of `app-review`).

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/sandbox/translation.mock.ts
> +import {mockTranslate} from '@coorpacademy/translate';
plase move this file to `src/tests/utils`. I'd rather see tests importing this mock from utils, than importing it from the sandbox enviroment.

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
to be imported from src/util/

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/button-revising.on-click.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
> +import {translate} from '../../../../sandbox/translation.mock';
idem

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-components/src/organism/review-stacked-slides/style.css
> +  transition: transform 1s ease-in, width 1s ease-in;
This changes should not been here in your PR, please check when you build your PR which files have been added. You must be sure that the PR does not includes files changed by other PRs.

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-review-services-mocks/src/index.ts
> +export const content: ReviewContent = {
not necessary to be exported

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-review-services-mocks/src/index.ts
> +export const engine: ReviewEngine = {
same here

2022-11-28 13:48 UTC, jomaora commented on packages/@coorpacademy-review-services/src/index.ts
> +  ChoiceItem as _ChoiceItem
👍

2022-11-28 16:46 UTC, jomaora approved these changes

2022-11-29 09:56 UTC, merged