put aria-label in img tag
CoorpAcademy/components pull request #2523
Opened 2022-12-08 03:39 UTC by youssefezzahi96

[ticket](https://trello.com/c/xdEImicV/69-header-alternative-textuelle-pour-les-img-porteuses-dinformations)

2022-12-09 09:05 UTC, DjamelSoualmi requested changes

2022-12-09 09:05 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
picture c'est une img  .. c'est dans le alt qu'il faut mettre la description 
https://github.com/CoorpAcademy/components/blob/master/packages/@coorpacademy-components/src/atom/picture/index.js/#L29

2022-12-09 09:05 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
Link dans ce  cas est pas valide j'ai l'impression

2022-12-09 09:05 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +              <Picture src={logoUrl} aria-label={logoAriaLabel} />
IDM

2022-12-12 09:34 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
<img width="805" alt="image" src="https://user-images.githubusercontent.com/111736786/207010742-5ccec266-717c-425a-94cc-c709cae34fcd.png">
apparement, d'après le manuel, si le lien est sous forme d'img, il est valide si l'img est valide

2022-12-12 09:46 UTC, StefanoA1 approved these changes

2022-12-12 10:16 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
tu peux me montre ou t'as vu ça ? 
ton cas c'est lien avec image 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/58167920/207020290-13809361-0560-4809-aad7-3e84ab48a56c.png">

2022-12-12 10:32 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
regarde la méthodologie de test :p 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/111736786/207023441-b3249618-0826-42aa-bc98-3655feb1b6ef.png">

2022-12-12 10:34 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
>                </Link>
dans notre cas l'intitulé de notre lien est fournie par l'alternative textuelle de l'image et qui permet de comprendre la fonction et la destination (alt="Brand logo http://digital.mooc:3000")

2022-12-12 17:18 UTC, merged