Add trads for avatars in Discussion section
CoorpAcademy/components pull request #2527
Opened 2022-12-12 16:21 UTC by RefkaKhl

**Detailed purpose of the PR**
Add trads for avatars in Discussion section

2022-12-12 16:25 UTC, RefkaKhl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add trads for avatars in Discussion section](https://trello.com/c/heRjEduR/73-add-trads-for-avatars-in-discussion-section)

2022-12-12 16:54 UTC, DjamelSoualmi requested changes

2022-12-12 16:54 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/forum/forum-post/index.js
> +          <Picture src={avatar} className={style.avatar} aria-label={author} />
le nom de l'auteur ne explique pas le contenue de  l'image , il faut ajouter une trad pour dire  par ex : "L'image de  l'auteur X"

2022-12-12 16:54 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/forum/forum-post/index.js
> +          <Picture src={avatar} className={style.avatar} aria-label={author} />
c'est une image il faut passer un `alt` et  pas un `aria-label `

2022-12-15 09:55 UTC, DjamelSoualmi approved these changes

2022-12-15 10:18 UTC, merged