Fix template activity mobile style
CoorpAcademy/components pull request #2529
Opened 2022-12-13 17:00 UTC by antonia2929

W.I.P

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2022-12-20 08:56 UTC, esa-coorp requested changes

2022-12-20 08:56 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/activity/test/handles-test.js
> +test.only('should call the onClick function with click on engine tab', t => {
```suggestion
test('should call the onClick function with click on engine tab', t => {
```

2022-12-20 08:56 UTC, esa-coorp commented on packages/@coorpacademy-components/src/template/activity/test/handles-test.js
> +  console.log(props);
```suggestion
```

2022-12-20 09:56 UTC, DjamelSoualmi requested changes

2022-12-20 09:56 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +    [engines, firstItem]
c'est une liste , il faut utilise la balise `ul` 
[la règle est là](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9)

2022-12-20 09:56 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +    </div>
et ça c'est les éléments de la liste du coup il faut remplacer la div par des `li`

2022-12-20 09:56 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +    [engines, firstItem]
ou `ol` si la liste est ordonnée

2022-12-20 09:56 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +    [engines, firstItem]
l'index c'est pas une clé unique, si il y un autre composant dans la même page avec des clés index aussi tu aura des soucis .... ajouter un préfixe pour spécifier le composant (ex: engineTabs_{index}

2022-12-20 09:56 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +    </div>
`type` c'est pas unique non plus

2022-12-20 10:58 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/template/activity/test/handles-test.js
> +  console.log(props);
n'oublie pas d'enlever les console.log :p

2022-12-23 13:52 UTC, youssefezzahi96 approved these changes

2022-12-23 16:12 UTC, RefkaKhl approved these changes

2022-12-26 09:19 UTC, DjamelSoualmi requested changes

2022-12-26 09:19 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/stars-summary.js
> +          <EngineTab engine={engine} key={index} firstItem={firstItem} engineIndex={index} />
```suggestion
          <EngineTab engine={engine} key={`engineTab_${index}`} firstItem={firstItem} engineIndex={index} />
```

2022-12-27 15:03 UTC, merged