[RGAA] Player: Alternative textuelle pour les <img> porteuses d'informations
CoorpAcademy/components pull request #2534
Opened 2022-12-19 15:10 UTC by youssefezzahi96

[ticket](https://trello.com/c/usYECP18/78-player-alternative-textuelle-pour-les-img-porteuses-dinformations)
fait dans cette PR :
-alternative textuelle pour le logo de l'auteur de la discipline (player)

2022-12-19 15:49 UTC, DjamelSoualmi requested changes

2022-12-19 15:49 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
> +        <Picture className={style.logo} src={authorLogo.src} alt={authorLogo.alt} />
lodash ne  permet pas de savoir si le alt est bien une chaine de char non empty ou pas , du coup il faut ajouté une condition sur le alt .. si c'est  empty il faut appliquer les réglés de l'img sans infos

2022-12-19 15:51 UTC, DjamelSoualmi requested changes

2022-12-19 15:51 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
> +        <Picture className={style.logo} src={authorLogo.src} alt={authorLogo.alt} />
tien il faut mettre à jour le type de props dans la ligne 114

2022-12-19 16:24 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
> +        <Picture className={style.logo} src={authorLogo.src} alt={authorLogo.alt} />
le default case (alt undefined) est déja traité dans le composant Picture

2022-12-21 10:46 UTC, RefkaKhl approved these changes

2022-12-21 14:07 UTC, merged