[RGAA]  add active page aria label
CoorpAcademy/components pull request #2539
Opened 2022-12-23 11:08 UTC by RefkaKhl

**Detailed purpose of the PR**

ajouter une alternative textuelle pour les pages actives 
<img width="417" alt="Capture d’écran 2022-12-23 à 11 56 21" src="https://user-images.githubusercontent.com/119853351/209324823-97fa0eb9-5c05-42ee-8be1-e707cb2d1420.png">

2022-12-23 11:09 UTC, RefkaKhl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dans chaque page web, l’information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?](https://trello.com/c/RtAeq4nM/87-dans-chaque-page-web-linformation-ne-doit-pas-%C3%AAtre-donn%C3%A9e-uniquement-par-la-couleur-cette-r%C3%A8gle-est-elle-respect%C3%A9e)

2022-12-26 09:13 UTC, DjamelSoualmi requested changes

2022-12-26 09:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +      'active-page-alt': activePageAlt
```suggestion
      'active-page-aria-label': activePageAriaLabel
```

2022-12-26 10:01 UTC, DjamelSoualmi approved these changes

2022-12-26 10:17 UTC, merged