[RGAA]Discussions + battles + MonCompte + Header: Alternative textuelle pour les <svg> porteuses d'informations
CoorpAcademy/components pull request #2543
Opened 2022-12-27 02:36 UTC by youssefezzahi96

[ticket ](https://trello.com/c/W3KvLx4V/88-discussions-battles-moncompte-header-alternative-textuelle-pour-les-svg-porteuses-dinformations)

2022-12-27 13:34 UTC, DjamelSoualmi requested changes

2022-12-27 13:34 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/select/index.js
> +  moreLabel: PropTypes.string,
```suggestion
  moreAriaLabel: PropTypes.string,
```

2022-12-27 13:34 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +              <ArrowDown color={mediumColor} className={style.caret} aria-label={moreLabel} />
ça serait cool de corriger ça aussi 
moreAriaLabel

2022-12-28 09:54 UTC, StefanoA1 approved these changes

2022-12-28 09:55 UTC, DjamelSoualmi approved these changes

2022-12-28 10:12 UTC, merged