Add information aria label review item dashboard component
CoorpAcademy/components pull request #2550
Opened 2022-12-28 17:34 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-01-03 09:33 UTC, StefanoA1 approved these changes

2023-01-04 09:13 UTC, DjamelSoualmi requested changes

2023-01-04 09:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
>      </div>
tu peux supprimer une duv t'as pas besoin de deux 

```
   <div className={style.toolTip}>
        <p className={style.tooltipText}>
          {tooltipText}
        </p>
      </div>
```

2023-01-04 09:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +const ToolTip = ({tooltipText, moreDetailsAriaLabel}) => {
```suggestion
const ToolTip = ({tooltipText, 'aria-label': moreDetailsAriaLabel}) => {
```

2023-01-04 09:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +                  moreDetailsAriaLabel={label.moreDetailsAriaLabel}
```suggestion
                 'aria-label'={label.moreDetailsAriaLabel}
```

2023-01-04 09:13 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +  moreDetailsAriaLabel: PropTypes.string
```suggestion
 'aria-label': PropTypes.string
```

2023-01-04 10:52 UTC, DjamelSoualmi approved these changes

2023-01-05 09:24 UTC, merged