using theme color for selected values
CoorpAcademy/components pull request #2551
Opened 2022-12-29 14:05 UTC by chrisdugne

**Detailed purpose of the PR**

Using brand color for mobile selects

<img width="340" alt="Screenshot 2022-12-29 at 15 04 57" src="https://user-images.githubusercontent.com/910636/209964478-2ef551fe-6f4c-4252-8899-74199f184ca5.png">

2022-12-29 14:06 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQU Je souhaite que mes réponses sélectionnées dans les dropdown soient à la couleur primaire de ma plateforme](https://trello.com/c/PGKxELe5/2906-etqu-je-souhaite-que-mes-r%C3%A9ponses-s%C3%A9lectionn%C3%A9es-dans-les-dropdown-soient-%C3%A0-la-couleur-primaire-de-ma-plateforme)

2022-12-29 14:37 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQAudric je souhaite réduire l'espacement entre les deux CTA "review" et "keep" [24px]](https://trello.com/c/1KmTJ4Uq/2907-etqaudric-je-souhaite-r%C3%A9duire-lespacement-entre-les-deux-cta-review-et-keep-24px)

2022-12-29 15:19 UTC, audric-coorp approved these changes

2022-12-30 09:43 UTC, jomaora requested changes

2022-12-30 09:43 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/questions/mobile/template/index.native.tsx
> -  const {theme, brandTheme, translations} = templateContext;
pourquoi tu enleves ici le brandTheme ?

2022-12-30 10:04 UTC, chrisdugne commented on packages/@coorpacademy-components/src/molecule/questions/mobile/template/index.native.tsx
> -  const {theme, brandTheme, translations} = templateContext;
car il est utilisé plus bas, directement dans le select, et non plus ici

2022-12-30 10:16 UTC, jomaora approved these changes

2022-12-30 11:00 UTC, esa-coorp approved these changes

2022-12-30 11:04 UTC, merged