[RGAA] activities & myAccount : Alternative textuelle pour les <svg> porteuses d'informations
CoorpAcademy/components pull request #2555
Opened 2023-01-02 14:57 UTC by youssefezzahi96

[ticket](https://trello.com/c/gizvbWLM/102-activities-alternative-textuelle-pour-les-svg-porteuses-dinformations)
purpose : 

- Activity: add aria-label to adaptive progression courses
- myAccount : add aria-label to more information icon use preferences (email props)

2023-01-02 21:18 UTC, DjamelSoualmi requested changes

2023-01-02 21:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
> +    moreInfoAriaLabel: 'show more info'
"show more languages" c'est plus précis non ?

2023-01-03 07:28 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
> +    moreInfoAriaLabel: 'show more info'
sorry, je me suis trompé du screenshot,
c'est plutot show more info :p 
<img width="1412" alt="Pasted Graphic 16" src="https://user-images.githubusercontent.com/111736786/210315070-b7d23424-fc7f-4dbc-99c6-43ea4bf671fe.png">

2023-01-03 07:31 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
> +    moreInfoAriaLabel: 'show more info'
c'est une icone pour afficher plus d'informations ( tu peux checker, tu la trouvera dans les alert de myAccount page)

2023-01-03 14:55 UTC, antonia2929 approved these changes

2023-01-04 09:19 UTC, DjamelSoualmi approved these changes

2023-01-04 10:12 UTC, StefanoA1 approved these changes

2023-01-04 15:04 UTC, merged