[RGAA]  add aria label to dashboard button
CoorpAcademy/components pull request #2556
Opened 2023-01-03 16:02 UTC by RefkaKhl

**Detailed purpose of the PR**
Ajouter des aria labels pour les boutons de dashboard
<img width="340" alt="Capture d’écran 2023-01-03 à 16 45 53" src="https://user-images.githubusercontent.com/119853351/210394091-50082bd4-911c-4518-96a2-d2cf17f397ea.png">
<img width="579" alt="Capture d’écran 2023-01-03 à 16 46 09" src="https://user-images.githubusercontent.com/119853351/210394254-cf0aee4d-c37a-4746-8efd-7ce7e82d2c9d.png">
<img width="515" alt="Capture d’écran 2023-01-03 à 16 46 23" src="https://user-images.githubusercontent.com/119853351/210394305-179af988-2800-4aa4-bb58-c09cbd4154b3.png">
<img width="577" alt="Capture d’écran 2023-01-03 à 16 46 50" src="https://user-images.githubusercontent.com/119853351/210394363-cb035fc1-56c5-4d2a-9f0a-13cb011a7d03.png">
<img width="848" alt="Capture d’écran 2023-01-03 à 16 47 05" src="https://user-images.githubusercontent.com/119853351/210394416-ffa13cf6-e045-4258-b715-8cea204490d6.png">
<img width="608" alt="Capture d’écran 2023-01-03 à 16 47 34" src="https://user-images.githubusercontent.com/119853351/210394460-985322bf-612d-4c5a-a5ed-b56d34a67841.png">

2023-01-03 16:59 UTC, esa-coorp approved these changes

2023-01-04 08:43 UTC, DjamelSoualmi requested changes

2023-01-04 08:43 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/cta/index.js
> +    submitAriaLabel: Link.propTypes.children,
```suggestion
   'aria-label': PropTypes.string,
```

2023-01-04 08:43 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/cta/index.js
> +      submitAriaLabel,
```suggestion
      'aria-label' : submitAriaLabel,
```

2023-01-04 08:43 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/button/index.js
> +  submitAriaLabel: PropTypes.string,
```suggestion
 'aria-label': PropTypes.string,
```

2023-01-04 08:43 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/button/index.js
> +    submitAriaLabel,
```suggestion
    'aria-label': submitAriaLabel,
```

2023-01-04 10:51 UTC, DjamelSoualmi approved these changes

2023-01-05 10:01 UTC, DjamelSoualmi requested changes

2023-01-09 09:19 UTC, StefanoA1 approved these changes

2023-06-28 07:56 UTC, closed without merging