[RGAA] Information icon reviewable skill keyboard events
CoorpAcademy/components pull request #2562
Opened 2023-01-09 10:19 UTC by antonia2929

Final part of this trello card :  [add aria-label for revision dashboard "reviewable list"](https://trello.com/c/ojoyK0Z2/77-add-aria-label-for-revision-dashboard-reviewable-list)

**Detailed purpose of the PR**
Customise the event on keyboard press to match [this RGAA rule about information presentation](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#10.13.1)
- Open the tooltipText content when "Enter" is pressed on the information icon
- Close this area when "Escape" or "Tab" are pressed.

**Result and observation**
![Kapture 2023-01-09 at 15 12 33](https://user-images.githubusercontent.com/113359769/211328315-785f9174-1117-4b3d-b9c5-a59110dda1f6.gif))

**Testing Strategy**
- Already covered by tests
- Manual testing

2023-01-09 14:30 UTC, StefanoA1 approved these changes

2023-01-16 10:44 UTC, DjamelSoualmi requested changes

2023-01-16 10:44 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +      >
tu peux utiliser le composant Button plz ?

2023-01-16 15:44 UTC, antonia2929 commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +      >
@DjamelSoualmi Tu parles de ce composant ci ? [Button](http://coorpacademy.github.io/components/components/?path=/story/atom-button--a)

2023-01-18 10:57 UTC, DjamelSoualmi approved these changes

2023-01-18 10:57 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/review-presentation/index.js
> +  };
je vois mal l’intérêt de ça !

2023-01-18 13:36 UTC, merged