modified navbar style
CoorpAcademy/components pull request #2596
Opened 2023-01-19 17:10 UTC by chrisdugne

**Detailed purpose of the PR**

- updated navbar style
<img width="375" alt="Screenshot 2023-01-19 at 17 44 16" src="https://user-images.githubusercontent.com/910636/213513013-f571b9b0-6146-4f4b-8ad1-87aa843dd29d.png">

2023-01-20 15:53 UTC, chrisdugne commented
note: still waiting for this issue to be solved for android https://github.com/Kureev/react-native-blur/issues/517

2023-01-20 17:08 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [Partage header / navbar entre les screens](https://trello.com/c/xatGraiS/2924-partage-header-navbar-entre-les-screens)

2023-01-23 10:02 UTC, EmelineLeduc requested changes

2023-01-23 10:02 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/organism/mobile-navigation/index.native.tsx
> +
space to delete

2023-01-23 10:25 UTC, jomaora approved these changes

2023-01-23 11:08 UTC, merged