[review] add background image  for mobile
CoorpAcademy/components pull request #2600
Opened 2023-01-23 16:19 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-01-23 16:32 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[OR] Background - mobile](https://trello.com/c/n1CWMUBj/2854-or-background-mobile)

2023-01-24 10:17 UTC, chrisdugne requested changes

2023-01-24 10:17 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/types/common.ts
> +  backgroundImage?: number;
utilise:
```
import type {ImageSourcePropType} from 'react-native'
```

2023-01-24 10:17 UTC, chrisdugne commented on packages/@coorpacademy-components/src/template/app-review/player/index.js
> +        </div>
simple commentaire: on a un bon cas ici du problème `atom/molecule/organism` etc
- ce background est bien un composant (= ensemble d'elements sortable en un `<Component>` qui rend plus lisible la construction de la vue

- mais ce n'est pas un `atom/molecule/organism` car a priori on ne va pas reutiliser ce morceau ailleurs: il est spécifique à cette vue locale

=> il faudrait plutot nester les composants specifiques dans les `template/organism/molecule` dont ils font partie: 
(par exemple)
```
└── app-review
    ├── background
    ├── dashboard
    └── player
``` 

et les `atom/molecule` ne devraient etre que des éléments **génériques**, *reutilisés* 
(bouton, text-input, card, popin...)

2023-01-24 10:20 UTC, scalabw commented on packages/@coorpacademy-components/src/template/app-review/player/index.native.tsx
> +  const source = backgroundImage as number;
backgroundImage is a number ? Why ?

2023-01-24 11:13 UTC, EmelineLeduc commented on packages/@coorpacademy-app-review/src/types/common.ts
> +  backgroundImage?: number;
Pour utiliser ce typage, je vais devoir installer react-native sur l'app-review ? Je peux en revanche modifier le typage dans ce fichier packages/@coorpacademy-components/src/template/app-review/player/prop-types.ts.

2023-01-24 12:47 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/types/common.ts
> +  backgroundImage?: number;
effectivement, ce n'est pas pratique : (
laissons number alors, peut etre rajouter un commentaire sur la ligne vers https://reactnative.dev/docs/image#imagesource

2023-01-24 12:53 UTC, chrisdugne approved these changes

2023-01-24 13:18 UTC, scalabw approved these changes

2023-01-24 13:23 UTC, jomaora approved these changes

2023-01-24 13:31 UTC, merged