adding order to certificate sections
CoorpAcademy/components pull request #2601
Opened 2023-01-24 08:36 UTC by Ouiza-B

Add order to certificate sections

https://trello.com/c/5HLejkee/1160-modification-du-composant-section-certificate-pour-supporter-lorder

2023-01-24 08:42 UTC, Ouiza-B commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modification du composant section certificate pour supporter l'order](https://trello.com/c/5HLejkee/1160-modification-du-composant-section-certificate-pour-supporter-lorder)

2023-01-24 09:10 UTC, esa-coorp requested changes

2023-01-24 09:10 UTC, esa-coorp commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +        <div className={style.order}>{order}</div>
index commence à 0?
```suggestion
        <div className={style.order}>{order+1}</div>
```

2023-01-24 09:10 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +        <div className={style.order}>{order}</div>
on commence par 0 ?

2023-01-24 09:11 UTC, esa-coorp reviewed
@Ouiza-B peux tu mettre une copie d'écran de ton composant et resolution mobile et desktop sur ta PR?

2023-01-24 09:51 UTC, silouone reviewed
on  ne veut pas appliquer les order sur tout les pages. car metier wise ca na pas de sens. 
ilfaudrait faire un check sur le tag 'published' only

2023-01-24 10:47 UTC, DjamelSoualmi requested changes

2023-01-24 10:47 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +          <div className={style.order}>{order + 1}</div>
you need to add an aria-label to explain the meaning of this number ( for your cas it will be like "The order of the certification" )

2023-01-24 15:52 UTC, silouone approved these changes

2023-01-24 16:45 UTC, esa-coorp approved these changes

2023-01-25 10:16 UTC, DjamelSoualmi requested changes

2023-01-25 10:16 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/list-items/index.js
> +      <ListItem {...item} order={index} aria-label={ariaLabel} />
```suggestion
      <ListItem {...item} order={index} />
```
le aria-label est déjà dans `item`

2023-01-25 10:23 UTC, DjamelSoualmi approved these changes

2023-01-25 10:44 UTC, merged