[RGAA] etiquette des champs de formulaires (battles - signup) critères: 11.1 - 11.2
CoorpAcademy/components pull request #2606
Opened 2023-01-26 08:00 UTC by youssefezzahi96

[ticket](https://trello.com/c/tmQQHocS/100-traiter-les-etiquettes-des-formulaires-crit%C3%A8re-111-112)

2023-01-26 09:42 UTC, DjamelSoualmi reviewed
du coup le aria label sert à rien maintenant ?

2023-02-06 14:18 UTC, DjamelSoualmi requested changes

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/labeled.js
> +    'aria-labelledby': 'select aria-labelledby',
```suggestion
    'aria-labelledby': 'select-aria-labelledby',
```
c'est un id

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/select/index.js
> +          {...(ariaLabel ? {title: ariaLabel} : {})}
çapose pas de probleme si on a title et arialabelledby ?

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/select/test/fixtures/default.js
> +    'aria-labelledby': 'select aria-labelledby',
idm

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/filters/filters-wrapper.js
> +            <p id={`titleId-${idx}`} className={style.title}>
```suggestion
            <p id={`title-id-${idx}`} className={style.title}>
```

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +                <span id={`titleId-${settingName}`} className={style.label}>
```suggestion
                <span id={`title-id-${settingName}`} className={style.label}>
```

2023-02-06 14:18 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/template/activity/test/fixtures/default.js
> +    'aria-label': 'select aria-label',
idm

2023-02-06 17:10 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/select/index.js
> +          {...(ariaLabel ? {title: ariaLabel} : {})}
no :) parce que dans ce cas les reader prennent arialabelledby en priorité :)

2023-02-07 05:34 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/template/activity/test/fixtures/default.js
> +    'aria-label': 'select aria-label',
ca ce n'est pas un id par contre :p

2023-02-14 15:26 UTC, DjamelSoualmi approved these changes

2023-02-14 15:30 UTC, merged