[RGAA] Add tooltip information text on logo mooc header
CoorpAcademy/components pull request #2613
Opened 2023-01-30 09:43 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-02-01 16:45 UTC, StefanoA1 requested changes

2023-02-01 16:45 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/mooc-header/style.css
> +.tooltipIconContainer + [role="tooltip"] {
```suggestion
.logo .tooltipIconContainer + [role="tooltip"] {
```
pour éviter un possible clash avec autres tooltips

2023-02-06 13:41 UTC, StefanoA1 approved these changes

2023-02-08 09:01 UTC, RefkaKhl approved these changes

2023-02-08 15:16 UTC, merged