[TMA] fix select group options
CoorpAcademy/components pull request #2616
Opened 2023-01-30 16:10 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**
BEFORE
![Kapture 2023-01-30 at 17 07 47](https://user-images.githubusercontent.com/79636283/215530641-ceebfb34-0bf7-4b0c-8958-1f39d9c885b9.gif)

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-01-30 16:32 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MOOC] Nouveau filtre catalogue | Custom playlists](https://trello.com/c/RFULEVyn/2931-mooc-nouveau-filtre-catalogue-custom-playlists)

2023-01-30 16:37 UTC, jomaora approved these changes

2023-01-30 16:40 UTC, jomaora requested changes

2023-01-30 16:40 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/select/test/fixtures/group-options.js
>            {name: 'Re-energize yourself', value: 'Re-energize yourself', selected: false}
à changer aussi et où ça soit nécesaire

2023-01-30 17:03 UTC, scalabw approved these changes

2023-01-31 09:34 UTC, jomaora approved these changes

2023-01-31 09:43 UTC, merged