[RGAA] Add svg color to css files and properties
CoorpAcademy/components pull request #2622
Opened 2023-02-02 13:28 UTC by antonia2929

Trello card : [10.1 - Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l’information ?](https://trello.com/c/aBLqtIOv/148-101-dans-le-site-web-des-feuilles-de-styles-sont-elles-utilis%C3%A9es-pour-contr%C3%B4ler-la-pr%C3%A9sentation-de-linformation)

**Detailed purpose of the PR**
Delete the `color`attribute of all svg file according to this RGAA rule : [Dans le site web, des [feuilles de styles](https://accessibilite.numerique.gouv.fr/methode/glossaire/#feuille-de-style) sont-elles utilisées pour contrôler la [présentation de l’information](https://accessibilite.numerique.gouv.fr/methode/glossaire/#presentation-de-l-information) ?](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#10.1)

**Result and observation**

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-02-06 13:25 UTC, StefanoA1 approved these changes

2023-02-06 14:31 UTC, DjamelSoualmi requested changes

2023-02-06 14:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
> +      <ArrowIcon className={lessClassName} style={{color: mediumColor}} />
tu peux mettre la coleur dans le css ? quand on a une class css pour l'icon il veut mieux mettre tout le css de l'icon dedans

2023-02-06 14:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/accordion/part/index.js
> +        <LessIcon className={openIconClassName} style={{color: mediumColor}} />
idm

2023-02-06 14:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
> +                <ArrowIcon className={lessClassName} style={{color: mediumColor}} />
idm

2023-02-06 14:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/brand-form/index.js
> +      <ArrowLeft style={{color: darkColor}} className={style.arrowBack} />
idm

2023-02-06 14:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +                className={style.caret}
idm

2023-02-08 13:41 UTC, DjamelSoualmi approved these changes

2023-02-08 14:50 UTC, merged