add uploading file  progress component
CoorpAcademy/components pull request #2623
Opened 2023-02-03 11:25 UTC by youssefezzahi96

[ticket
](https://trello.com/c/LS6CuJoG/1186-bulk-composant-inspect-loading-state-progress-100)**Purpose of the PR :** 
- create UploadingFileProgress component + create fixtures for the component itself
![image](https://user-images.githubusercontent.com/111736786/216591596-1258065a-be17-44de-8d52-c0b2f4e566c0.png)
- add it UploadingFileProgress in BrandUpdate component + create fixtures for this case
![image](https://user-images.githubusercontent.com/111736786/216591219-cbd0391f-2bf7-4503-b042-2bc090747a53.png)

2023-02-03 14:41 UTC, chrisdugne commented on packages/@coorpacademy-components/src/molecule/uploading-file-progress/test/fixtures/default.js
> +  props: {
hello, on peut aussi utiliser des `.ts` pour les fixtures, ce qui permet de reutiliser la partie `Props` ici; 

comme ça on obtient des fixtures pour storybook bien carrées, sans props qui restent apres X refacto

```
import type {Props} from '../types';
type Fixture = {props: Props};
```

2023-02-07 10:11 UTC, silouone approved these changes

2023-02-07 13:24 UTC, GhaziCoorpacademy requested changes

2023-02-07 13:24 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/uploading-file-progress/style.css
> +    ;
```suggestion
```

2023-02-07 13:42 UTC, Ouiza-B approved these changes

2023-02-08 07:50 UTC, GhaziCoorpacademy approved these changes

2023-02-08 11:22 UTC, merged