[RGAA] Battle Opponent Atom + Tooltip: 12.11
CoorpAcademy/components pull request #2637
Opened 2023-02-14 18:17 UTC by StefanoA1

Crit 12.11:
Dans chaque page web, les contenus additionnels apparaissant au survol, à la prise de focus ou à l'activation d'un composant d'interface sont-ils, si nécessaire, atteignables au clavier

**Detailed purpose of the PR**

- Adds Battle Opponent Atom + Tooltip

**Result and observation**
![Screen Recording 2023-02-14 at 19 11 11](https://user-images.githubusercontent.com/33550261/218823260-70ac4357-5f1c-488c-8e19-30e87cb5a759.gif)

**Testing Strategy**

- [x] Manual testing
- [x] Unit testing

2023-02-14 18:30 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [12.11 - Dans chaque page web, les contenus additionnels apparaissant au survol, à la prise de focus ou à l'activation d'un composant d'interface sont-ils, si nécessaire, atteignables au clavier ?](https://trello.com/c/RBLiiHXe/97-1211-dans-chaque-page-web-les-contenus-additionnels-apparaissant-au-survol-a%CC%80-la-prise-de-focus-ou-a%CC%80-lactivation-dun-composant)

2023-02-16 10:30 UTC, RefkaKhl approved these changes

2023-02-16 10:39 UTC, DjamelSoualmi requested changes

2023-02-16 10:39 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
> +        {isRandom ? null : <img src={userAvatarSrc} aria-hidden="true" />}
```suggestion
        {isRandom ? null : <img src={userAvatarSrc} alt="" />}
```

2023-02-16 10:39 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
> +  const translate: Required<WebContextValues>['translate'] = GetTranslateFromContext(legacyContext);
pourquoi tu passes pas les locales en props ?

2023-02-16 10:39 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/battle-opponent-list/index.tsx
> +        opponents
c'est une liste , il faut la mettre dans des balise ul et mettre les oppenents dans des items de la liste

2023-02-16 10:42 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
> +  const translate: Required<WebContextValues>['translate'] = GetTranslateFromContext(legacyContext);
pour celui là c'est une trad qu'on à côte components (le reste sont passes autant que props)

2023-02-16 15:38 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
> +        {isRandom ? null : <img src={userAvatarSrc} aria-hidden="true" />}
done

2023-02-16 15:39 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/molecule/battle-opponent-list/index.tsx
> +        opponents
done

2023-02-17 09:44 UTC, DjamelSoualmi approved these changes

2023-02-17 09:44 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
> +            data-testid="battle-engaged-opponent-information-button"
il manque  un aria-label ici non ?

2023-02-17 10:35 UTC, merged