[RGAA]change links style in footer and header
CoorpAcademy/components pull request #2639
Opened 2023-02-15 16:29 UTC by RefkaKhl

<!-- Before creating your PR :
 - Have you added a Modification Type Label ?
 - Did you use the trello power up to link your PR and the trello ticket ?
 - 10.6 - Dans chaque page web, chaque lien dont la nature n’est pas évidente est-il visible par rapport au texte environnant ?

https://user-images.githubusercontent.com/119853351/219090436-6e26bd83-29cd-4bba-8f4f-49c12e2bb3a0.mov

https://user-images.githubusercontent.com/119853351/219090485-0204df08-4d90-4de5-851b-0c56170bf0b8.mov

2023-02-15 16:31 UTC, RefkaKhl commented
![](https://github.trello.services/images/mini-trello-icon.png) [10.6 - Dans chaque page web, chaque lien dont la nature n’est pas évidente est-il visible par rapport au texte environnant ?](https://trello.com/c/O3k0LFzF/29-106-dans-chaque-page-web-chaque-lien-dont-la-nature-nest-pas-%C3%A9vidente-est-il-visible-par-rapport-au-texte-environnant)

2023-02-15 19:56 UTC, StefanoA1 requested changes

2023-02-15 19:56 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +
Test coverage is missing for these 2 events

2023-02-16 11:03 UTC, DjamelSoualmi requested changes

2023-02-16 11:03 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/mooc-header/style.css
> +  width: 3px;
```suggestion
  width: 3px;
  display: inherit;
```

2023-02-17 11:00 UTC, DjamelSoualmi approved these changes

2023-02-20 11:03 UTC, antonia2929 approved these changes

2023-02-20 11:04 UTC, merged