Fix select mobile
CoorpAcademy/components pull request #2653
Opened 2023-02-21 17:00 UTC by EmelineLeduc

**Detailed purpose of the PR**
This PR modifies components `Answer` and `QuestionTemplate` to fix the bug related to the use of several select in mobile revision player.

**Result and observation**

![Kapture 2023-02-21 at 16 20 07](https://user-images.githubusercontent.com/79636283/220394450-57f5ad4b-9db2-4cbc-bb81-4166024487e1.gif)

**Testing Strategy**

- [ ] Already covered by tests
- [x] Manual testing
- [ ] Unit testing

2023-02-22 11:00 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug select, afficher des options d'autres questions](https://trello.com/c/UOO7yNBS/2996-bug-select-afficher-des-options-dautres-questions)

2023-02-22 11:09 UTC, scalabw approved these changes

2023-02-22 13:09 UTC, jomaora requested changes

2023-02-22 13:09 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/questions/mobile/template/index.native.tsx
> +      {part.value || ''}
pourquoi ce trim a été supprimé ?

2023-02-22 13:09 UTC, jomaora commented on packages/@coorpacademy-components/src/molecule/questions/mobile/template/index.native.tsx
> -  index: number;
pourquoi l'index a été supprimé ?

2023-02-24 15:45 UTC, jomaora approved these changes

2023-02-27 11:45 UTC, chrisdugne approved these changes

2023-02-28 16:08 UTC, merged