[RGAA] remove margin bottom on switch in filters && add height to languageSe…
CoorpAcademy/components pull request #2656
Opened 2023-02-22 14:22 UTC by antonia2929

…lect

 

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-02-23 12:07 UTC, StefanoA1 requested changes
generated fixtures are missing -> `npm run generate`

2023-02-23 12:25 UTC, DjamelSoualmi approved these changes

2023-02-23 12:48 UTC, StefanoA1 approved these changes

2023-02-27 15:03 UTC, StefanoA1 approved these changes

2023-03-01 14:44 UTC, merged