[RGAA]add aria label to buttons
CoorpAcademy/components pull request #2660
Opened 2023-02-23 16:32 UTC by RefkaKhl

Traiter les retours de ce ticket
[https://trello.com/c/6DO1Jgh7/103-119-dans-chaque-formulaire-lintitul%C3%A9-de-chaque-bouton-est-il-pertinent-hors-cas-particuliers](https://github.com/CoorpAcademy/coorpacademy/pull/url)

2023-02-23 16:33 UTC, RefkaKhl commented
![](https://github.trello.services/images/mini-trello-icon.png) [11.9 - Dans chaque formulaire, l’intitulé de chaque bouton est-il pertinent (hors cas particuliers) ?](https://trello.com/c/6DO1Jgh7/103-119-dans-chaque-formulaire-lintitul%C3%A9-de-chaque-bouton-est-il-pertinent-hors-cas-particuliers)

2023-02-27 13:39 UTC, antonia2929 approved these changes

2023-02-27 14:34 UTC, StefanoA1 requested changes

2023-02-27 14:52 UTC, DjamelSoualmi requested changes

2023-02-27 14:52 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/locales/en/global.json
> +  "validateariaLabel":"Validate your answer and go to next step"
```suggestion
  "close_button_ariaLabel":" Close review slide",
  "post_comment_aria_label": "Post your comment",
  "validate_aria_label": "Validate your answer and go to next step"
```

2023-02-28 14:30 UTC, merged