Fix select filter
CoorpAcademy/components pull request #2663
Opened 2023-02-27 17:07 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-02-28 16:12 UTC, jomaora approved these changes

2023-02-28 16:25 UTC, StefanoA1 approved these changes

2023-02-28 17:18 UTC, esa-coorp requested changes

2023-02-28 17:18 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/select/index.js
> +    () => (titleSize <= textLength ? title : truncate({length: textLength}, title)),
je ne comprends pas le besoin de faire des truncates

https://developer.mozilla.org/fr/docs/Web/CSS/text-overflow
`text-overflow ellipsis` ne fonctionne pas ....

2023-03-01 09:59 UTC, jomaora approved these changes

2023-03-01 10:17 UTC, esa-coorp approved these changes

2023-03-01 10:34 UTC, merged