create actionnable expandible table
CoorpAcademy/components pull request #2665
Opened 2023-02-28 04:45 UTC by youssefezzahi96

[ticket](https://trello.com/c/YbO0HtBE/1188-composant-inspect-post-progress-100) 
actionnable errors table is a component that would be used on bulk tables. and is built using errors table, and expandible table already created.
Purpose of the PR:
-create actionnable expandible errors table.
-actionnable expandible errors table should be RGAA compliant
![image](https://user-images.githubusercontent.com/111736786/221755361-d9d47b2f-9b38-4d6d-bbb7-94f3f704ccf8.png)
![image](https://user-images.githubusercontent.com/111736786/221755398-633fa84a-8ad0-400b-9f04-0d95aa141fae.png)
![image](https://user-images.githubusercontent.com/111736786/221755430-3bd2c50c-1b90-4cc6-9098-fefe022d826b.png)
![image](https://user-images.githubusercontent.com/111736786/221755457-218214bd-326a-4cd6-88ed-4f4a83e08275.png)

**Action menu:**
![image](https://user-images.githubusercontent.com/111736786/221755520-0876cbaa-03cb-494a-bb79-d24f6cdd4068.png)

**sticky columns when scrolling horizontally:**
![image](https://user-images.githubusercontent.com/111736786/221755614-877d15db-cad6-4707-82ee-ad6e06a8a04c.png)
![image](https://user-images.githubusercontent.com/111736786/221755673-7b4bacd8-f034-4b7d-baeb-24d468c43310.png)

2023-02-28 17:07 UTC, esa-coorp requested changes

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.js
> +// eslint-disable-next-line css-modules/no-unused-class
pk?

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.js
> +      // className={menuClassName ? style[menuClassName] : style.bulletPointMenu}
ton commentaire

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +        <div>{title}</div>
pourquoi tu ajoutes une `div`?

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +      <div> {''}</div>
idem

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +            // eslint-disable-next-line no-nested-ternary
on évite de désactiver cette regle

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +                  // eslint-disable-next-line react/jsx-no-bind
idem

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/style.css
> +  /* overflow-x: auto;
le commentaire

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-errors-table/index.tsx
> +        <div>{title}</div>
enleve la div

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-errors-table/index.tsx
> +      <div> {''}</div>
idem

2023-02-28 17:07 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-errors-table/index.tsx
> +              // eslint-disable-next-line react/jsx-no-bind
idem

2023-02-28 17:08 UTC, esa-coorp commented
@youssefezzahi96 ton `diff coverage is 64.35%.`

2023-03-03 15:48 UTC, esa-coorp requested changes

2023-03-03 15:48 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.js
> +// eslint-disable-next-line css-modules/no-unused-class
peux tu enlever ce commentaire?

2023-03-03 16:30 UTC, GhaziCoorpacademy approved these changes

2023-03-09 12:18 UTC, esa-coorp approved these changes

2023-05-02 02:56 UTC, closed without merging