remove onClick on key enter pressed + fix space and enter bug
CoorpAcademy/components pull request #2667
Opened 2023-02-28 17:21 UTC by scalabw

https://trello.com/c/WyN38fOP/2986-or-bug-quand-on-clique-sur-la-barre-despace

**Detailed purpose of the PR**

This PR fix the bug when pressing enter or space key in certain cases such as:

-> Pressing space OR enter when in an input surrounded by some other types of inputs

-> Pressing enter or space when button to validate answer is disabled

**Result and observation**

2023-02-28 17:29 UTC, chrisdugne commented on packages/@coorpacademy-components/src/organism/review-slide/index.js
> +      if (event.key === 'Enter' || (event.key === ' ' && disabled)) {
les parenthèses ne sont pas au bon endroit ou je me trompe ?
```
(event.key === 'Enter' || event.key === ' ') && disabled)
```

2023-02-28 17:39 UTC, scalabw commented on packages/@coorpacademy-components/src/organism/review-slide/index.js
> +      if (event.key === 'Enter' || (event.key === ' ' && disabled)) {
on ne veut pas que la touche enter trigger la validation de la slide car il y a des slides ce type:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/22681512/221933487-98fe146d-e215-4352-85fa-8b8f1c74e0f4.png">

2023-03-01 09:42 UTC, EmelineLeduc approved these changes

2023-03-01 09:57 UTC, chrisdugne approved these changes

2023-03-01 10:18 UTC, jomaora requested changes
When I press enter on the slide and the focus is on the inut text (after filling the input text), the application is reloaded

![bug-enter-slide](https://user-images.githubusercontent.com/7602475/222109859-a3587c90-7354-4ca9-99b0-cfe93a7fbb56.gif)

When I'm on another slide than free-text or template, and I press the space key

![app-ko-when-slide-non-basic-and-press-space-key](https://user-images.githubusercontent.com/7602475/222110788-8a4cc489-4c33-4f34-a56b-3d982e632420.gif)

2023-03-01 10:39 UTC, jomaora approved these changes
I have nor build the components package. it's ok

2023-03-01 14:16 UTC, merged