atom.input-html > using RTL
CoorpAcademy/components pull request #2668
Opened 2023-03-01 13:52 UTC by chrisdugne

**Detailed purpose of the PR**

- migrated `atom.input-html` to latest React API
- migrated `atom.input-html` testing using React Testing Library

2023-03-02 14:13 UTC, chrisdugne commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RTL] select + textarea + html](https://trello.com/c/9UuILIgR/3010-rtl-select-textarea-html)

2023-03-02 14:48 UTC, StefanoA1 requested changes

2023-03-02 14:48 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/input-html/index.js
> +    [onChange]
```suggestion
    [onChange, setText]
```

2023-03-02 14:48 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/input-html/index.js
> +  const {skin} = context;
```suggestion
  const skin = GetSkinFromContext(context);
```

2023-03-03 09:33 UTC, EmelineLeduc approved these changes

2023-03-03 10:32 UTC, chrisdugne commented on packages/@coorpacademy-components/src/atom/input-html/index.js
> +    [onChange]
`setText` ne change pas, elle est 'générée' par un `useState`;

(d'ailleurs `setText` n'est pas proposé ici par `eslint[react-hooks/exhaustive-deps]`)

2023-03-03 10:45 UTC, StefanoA1 approved these changes

2023-03-03 11:05 UTC, merged