modifiy image upload component props image type
CoorpAcademy/components pull request #2671
Opened 2023-03-02 14:27 UTC by adamska27

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-03-02 17:02 UTC, esa-coorp approved these changes

2023-03-02 17:05 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
> +      previewView = <iframe className={style.preview} src={previewContent.src} />;
je suis pas convaincu qu'il faille une preview pour le pdf . A la limite un lien qui ouvre sur autre onglet .... @adamska27

2023-03-03 08:43 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
> +      previewView = <iframe className={style.preview} src={previewContent.src} />;
j'ai vu avec Audric, je lui ai proposé les 2 choix possible lien ou iframe et il a préféré avoir une preview

2023-03-03 16:43 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
> +      previewView = <iframe className={style.preview} src={previewContent.src} />;
modification et utilisation d'un bouton link

2023-03-04 11:27 UTC, silouone approved these changes

2023-03-06 13:39 UTC, esa-coorp requested changes

2023-03-06 20:59 UTC, esa-coorp approved these changes

2023-03-08 14:15 UTC, silouone approved these changes

2023-03-08 15:03 UTC, merged