Page confid
CoorpAcademy/components pull request #2674
Opened 2023-03-06 13:53 UTC by DjamelSoualmi

[Ticket](https://trello.com/c/XYqENK8H/134-moocrgaa-refonte-page-confidentialit%C3%A9)
create privacy page
**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-03-06 16:04 UTC, chrisdugne commented on packages/@coorpacademy-components/src/molecule/privacy-policy-download/index.js
> +import Button from '../../../es/atom/button';
```
import Button from '../../../atom/button';
```

2023-04-07 14:28 UTC, StefanoA1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MOOC][RGAA] - Refonte page "Confidentialité"](https://trello.com/c/XYqENK8H/134-moocrgaa-refonte-page-confidentialit%C3%A9)

2023-04-21 08:05 UTC, StefanoA1 commented
Fixed app-review tsc errors + fixed typecheck & globals + fixed components pages proptypes + fixes unique key warning

2023-04-24 12:02 UTC, StefanoA1 commented
Fixed app-review tsc errors + fixed typecheck & globals + fixed components pages proptypes + fixed unique key warning

2023-04-25 09:56 UTC, chrisdugne commented on packages/@coorpacademy-app-review/src/index.tsx
> +import type {AppReviewProps} from '@coorpacademy/components/es/src/template/app-review/prop-types';
Hello, il n'existe pas ce folder @StefanoA1  `/es/src/` ?

2023-06-13 08:57 UTC, jomaora approved these changes

2023-06-13 11:05 UTC, esa-coorp requested changes

2023-06-13 12:15 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/expandable-item/index.tsx
> +          <div
non c'est div car c'est le parent et je spécifie la balise dans le contenue que je passe

2023-06-13 12:17 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/hero/types.ts
> +};
je sais pas ce qui doit être obligatoire .. je vais mettre le titre , description et l'image comme required

2023-06-13 12:19 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/menu-links/style.css
> +  text-decoration-color: cm_primary_blue!important;
je clean

2023-06-13 14:14 UTC, esa-coorp approved these changes

2023-06-13 14:16 UTC, merged