create Actionnable expandible table
CoorpAcademy/components pull request #2678
Opened 2023-03-08 02:54 UTC by youssefezzahi96

[ticket](https://trello.com/c/YbO0HtBE/1188-composant-inspect-post-progress-100) 
Actionnable errors table is a component that would be used on bulk tables. and is built using errors table already created.
(in the future, a nice to have is to integrate errors table support in the expandible actionable table)

Purpose of the PR:

- create expandible actionnable errors table.
- update wizardContents to support expandible actionnable errors table
- update listItems to support expandible  actionnable errors table
- add expandible actionnable errors table to brandUpdate
- create bulk inspect fixtures
- create bulk dashboard saved fixtures
- create bulk dashboard pending fixtures
- expandible  actionnable errors table  test coverage 100%
- update some components from js to ts 

How to review : 
big part of changes is just converting some components from js to ts (with very small changes) :

- button-link 
- button-menu
- bullet-point-menu-button

the other changes concern bulk tables.

this PR  and the  [previous one](https://github.com/CoorpAcademy/components/pull/2665)  comparison: 

- this PR has only one table component (expandible actionnable errors table) that manages bulk tables (except errors table).
- the other one has two table components that manage bulk tables (expandible actionnable errors table && expandible) errors table.

**inspect - table  :**
![Pasted Graphic 32](https://user-images.githubusercontent.com/111736786/220517318-236d3979-d6ef-4909-a760-2b25195fe3b8.png)

![Pasted Graphic 33](https://user-images.githubusercontent.com/111736786/220517346-95a7af0e-c61a-419a-8692-9bb7820fd510.png)

![Pasted Graphic 34](https://user-images.githubusercontent.com/111736786/220517365-1b869e1d-5684-4fa0-8af4-8311af1ff3e0.png)

brandUpdate Template bulk inspect: 
![image](https://user-images.githubusercontent.com/111736786/222289348-a25f231b-0c42-416a-9dd1-3378f31e626e.png)

**dashboard / saved :** 
![image](https://user-images.githubusercontent.com/111736786/221755361-d9d47b2f-9b38-4d6d-bbb7-94f3f704ccf8.png)
![image](https://user-images.githubusercontent.com/111736786/221755398-633fa84a-8ad0-400b-9f04-0d95aa141fae.png)
![image](https://user-images.githubusercontent.com/111736786/221755430-3bd2c50c-1b90-4cc6-9098-fefe022d826b.png)
![image](https://user-images.githubusercontent.com/111736786/221755457-218214bd-326a-4cd6-88ed-4f4a83e08275.png)

**Action menu:**
![image](https://user-images.githubusercontent.com/111736786/221755520-0876cbaa-03cb-494a-bb79-d24f6cdd4068.png)

**sticky columns when scrolling horizontally:**
![image](https://user-images.githubusercontent.com/111736786/221755614-877d15db-cad6-4707-82ee-ad6e06a8a04c.png)
![image](https://user-images.githubusercontent.com/111736786/221755673-7b4bacd8-f034-4b7d-baeb-24d468c43310.png)

![image](https://user-images.githubusercontent.com/111736786/222627322-7ddcb8a8-385a-4c9d-9347-e4c6f17c7f0c.png)

**dashboard / pending**
![image](https://user-images.githubusercontent.com/111736786/223605380-2a24063a-ca16-46c1-9f70-976147528c29.png)
![image](https://user-images.githubusercontent.com/111736786/223605489-fa8b8187-1a8f-437b-999e-8714a98f2028.png)

2023-03-08 13:32 UTC, esa-coorp requested changes

2023-03-08 13:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/atom/button-link/style.css
> +  color: #0061FF;
ca doit être dans la palette ? colors.css

2023-03-08 13:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +    columnWidth = `${(1 / columns.length) * 100}%`,
```suggestion
    columnWidth = `${100 / _.size(columns)}%`,
```

2023-03-08 13:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +    const isRowExpanded = expandedRows.includes(index);
includes de Array n'est supporté par tous les navigateurs

```suggestion
    const isRowExpanded = _.includes(expandedRows, index);
```

2023-03-08 13:32 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +            <div>
ce div ne sert pas

2023-03-08 17:21 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
> +            <div>
regarde en css il sont utilisés
![image](https://user-images.githubusercontent.com/111736786/223784532-bc008ac8-f3b9-4801-9b59-3d6c6567189a.png)

2023-03-09 16:34 UTC, GhaziCoorpacademy approved these changes

2023-03-10 07:46 UTC, silouone commented on packages/@coorpacademy-components/src/atom/button-link/index.tsx
> +    type === 'bulkInspect' && style.bulkInspectButton,
il a quoi de spécific le bulk inspect button pour mériter son propre style non generique ? car tt les autres son generique? donc soit cest un nouveau design qui merite un generique soit on adapt un existant

2023-03-10 07:47 UTC, silouone commented on packages/@coorpacademy-components/src/atom/button-link/types.ts
> +  type?: 'primary' | 'secondary' | 'tertiary' | 'text' | 'dangerous' | 'bulkInspect';
tu vois ici on se rend bine compte que bulkInspect ne fit pas

2023-03-10 07:50 UTC, silouone commented on packages/@coorpacademy-components/src/organism/list-items/index.js
> +    case 'bulk-dashboard-saved':
ca m'embete d'etre encore une fois pas generique ici. si demain on a un autre dashboard qui veut display un array de ce type ....

2023-03-10 07:51 UTC, silouone reviewed
LGTM sur la structure, qqc retour de naming pour rendre plus generique le nouveua composant que tu as crée

2023-03-10 17:52 UTC, silouone approved these changes

2023-03-13 10:02 UTC, esa-coorp requested changes

2023-03-13 10:05 UTC, silouone commented on packages/@coorpacademy-components/src/atom/button-link/index.tsx
> +// eslint-disable-next-line css-modules/no-unused-class
pour ce coms la cest a priori aprce qu'il injecte la classe en dynamique ds la ppté className et donc il a une classe non utiliser car lint ne detecte pas l'import. on peut discuter d'un alternative si tu as une preference

2023-03-20 15:29 UTC, esa-coorp approved these changes

2023-03-21 08:01 UTC, merged