[TMA] Popin end external course components
CoorpAcademy/components pull request #2692
Opened 2023-03-17 10:43 UTC by antonia2929

Trello card : [TMA - [MOOC] [Player] Pop in complétion cours externe](https://trello.com/c/W4DcC6QZ/159-tma-mooc-player-pop-in-compl%C3%A9tion-cours-externe)

**Detailed purpose of the PR**
- Implement the close popin on the end of an external course

**Result and observation**

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-03-28 13:27 UTC, StefanoA1 requested changes

2023-03-28 13:27 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    ) : null;
```suggestion
    const popin = useMemo(() => !isNil(closePopin) ? (
      <div>
        <CmPopin {...closePopin} />
      </div>
    ) : null, [closePopin]);
```

2023-03-28 13:27 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    ) : null;
pareil pour completeButton, 2 d'un coup en profitant

2023-03-28 13:27 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    ) : null;
et mainContentSlot, donc 3

2023-03-28 15:05 UTC, antonia2929 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    ) : null;
@StefanoA1  Etant donné qu'on est dans une class component, je pense que je ne peux pas utiliser les hooks ici.

2023-03-28 15:46 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    ) : null;
@antonia2929 le composant  `ExternalCourse` est facile à migrer vue que il y a pas même des bindings ou autre, ça va te prendre qqs minutes et ça rends le composant compatible vers les hooks/lapis react modernes

2023-03-29 14:22 UTC, StefanoA1 requested changes

2023-03-29 14:22 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +  );
```suggestion
  const handleOnClick = useCallback(
    field => {
    // or: const onClick = getOr(noop, ['onClick'], field);
     const {onClick = noop} = field;
     return e => {
      e.stopPropagation();
      e.preventDefault();
      return onClick(e);
    }
    },
    []
  );
```

2023-03-29 14:22 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +  const quitButton = !isNil(quit) ? (
same

2023-03-29 14:52 UTC, StefanoA1 approved these changes

2023-03-30 08:53 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/template/external-course/index.js
> +    const {onClick = noop} = field;
// another option
const onClick = getOr(noop, ['onClick'], field);

2023-03-30 08:55 UTC, DjamelSoualmi requested changes

2023-03-30 08:55 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-right: 32px;
```suggestion
  margin: 0px 32px;
```

2023-03-30 08:55 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +    margin-right: 16px;
```suggestion
    margin: 0px 16px;
```

2023-03-30 08:55 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +    margin-right: 32px;
IDM

2023-03-30 12:44 UTC, esa-coorp requested changes

2023-03-30 12:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  width: 434px;
il y a pas d'impact de rendu sur l'ensemble des fixtures de la cm popin (pas exemple la go1 popin)?

2023-03-30 12:44 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  margin-right: 32px;
👍

2023-04-03 10:02 UTC, antonia2929 commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +  width: 434px;
@esa-coorp pour les popins cookies non car je n'ai pas modifié ces marges là.
Pour les autres, j'ai remodifié quelques propriétés, j'ai mis les variations des popins en commentaire de la PR.

2023-04-04 13:40 UTC, DjamelSoualmi approved these changes

2023-04-04 13:56 UTC, merged