[MassiveBattle] Radio with title component
CoorpAcademy/components pull request #2760
Opened 2023-06-26 07:40 UTC by antonia2929

Trello card 

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-06-26 09:08 UTC, jomaora requested changes

2023-06-26 09:08 UTC, jomaora commented on packages/@coorpacademy-components/src/atom/radio-with-title/style.css
> +  box-shadow: inset 0 0 0 0.4em cm_primary_blue;
0.5em looks match more with the Figma, no?

This is with 0.4em
<img width="391" alt="Capture d’écran 2023-06-26 à 11 04 16" src="https://github.com/CoorpAcademy/components/assets/7602475/b0b15a73-695a-463c-b029-83f22eafda44">

This is with 0.5em
<img width="360" alt="Capture d’écran 2023-06-26 à 11 04 05" src="https://github.com/CoorpAcademy/components/assets/7602475/af3f2c30-e421-46e4-8e6f-a8750f4f7813">

This is the Figma
![Capture d’écran 2023-06-26 à 11 04 26](https://github.com/CoorpAcademy/components/assets/7602475/a4244694-4819-4676-9668-72938815add1)

2023-06-26 09:50 UTC, StefanoA1 requested changes

2023-06-26 09:50 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/radio-with-title/index.tsx
> +    onChange = noop,
no onChange function provided scenario not covered
```
    onChange = noop,
```

2023-06-26 09:50 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/radio-with-title/index.tsx
> +  const handleChange = useCallback(
handleChange event is not covered, `input` should be triggered on a unit test to cover it

2023-06-27 14:23 UTC, jomaora approved these changes

2023-06-27 15:35 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/radio-with-title/test/on-change.tsx
> +  const {container} = render(
```suggestion
  const {container, rerender} = render(
```

2023-06-27 15:36 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/atom/radio-with-title/test/on-change.tsx
> +  fireEvent.click(radio);
```suggestion
 rerender(    <RadioWithTitle
      title={title}
      checked={checkedValue}
      onChange={handleChange}
      data-name={dataName}
      aria-label={''}
      name={''}
    />);
  fireEvent.click(radio);
```

2023-06-28 08:24 UTC, merged