[MassiveBattle] Select Population Component
CoorpAcademy/components pull request #2765
Opened 2023-07-04 15:38 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-07-10 15:48 UTC, StefanoA1 commented on packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
> +      })}
```suggestion
      {map((item: TitleRadioWrapperProps, key: number) => {
        return (
          <li key={key} className={style.item}>
            <TitleRadioWrapper {...item} />
          </li>
        );
      }, items)}
```

2023-07-10 15:55 UTC, StefanoA1 approved these changes

2023-07-11 12:31 UTC, DjamelSoualmi requested changes

2023-07-11 12:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/molecule/title-radio-wrapper/style.css
> +    width: 300px;
c'est responsive  ça ?

2023-07-11 12:31 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
> +          <li key={key} className={style.item}>
```suggestion
          <li key={`select-opponents-item-$(key}`} className={style.item}>
```
`key` n'est pas forcement unique dans la page

2023-07-11 12:53 UTC, DjamelSoualmi approved these changes

2023-07-11 13:42 UTC, merged