[massive-battle] create new component and update `BrandFormGroup` component
CoorpAcademy/components pull request #2767
Opened 2023-07-11 15:25 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-07-12 10:36 UTC, esa-coorp requested changes

2023-07-12 14:36 UTC, DjamelSoualmi requested changes

2023-07-12 14:36 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/organism/title-and-input/index.tsx
> +const buildInput = (childType: string, field: any) => {
```suggestion
const buildInput = (childType: string, field: Autocomplete || SelectMultiple || SelectOpponents) => {
```
c'est pas un any c'est l'un des trois types

2023-07-12 14:50 UTC, DjamelSoualmi approved these changes

2023-07-13 08:23 UTC, esa-coorp approved these changes

2023-07-13 08:48 UTC, merged