refacto statusItem
CoorpAcademy/components pull request #2771
Opened 2023-07-26 15:57 UTC by GhaziCoorpacademy

https://trello.com/c/MYTe90SC/1327-refacto-template-inspect

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-07-26 15:57 UTC, GhaziCoorpacademy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refacto template Inspect.](https://trello.com/c/MYTe90SC/1327-refacto-template-inspect)

2023-08-08 08:30 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
> +  /* height: 10px; */
enlève le commentaire

2023-08-08 08:31 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
>  .invalid {
enlève le commentaire

2023-08-08 08:32 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
>  .invalidIcon {
enlève les commentaire

2023-08-08 08:32 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
>    color: cm_negative_100;
enlève les commentaires

2023-08-08 08:48 UTC, adamska27 requested changes

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/style.css
> +  .firstMessage {
t'as un espace devant

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/style.css
> +  .secondMessage {
idem

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
> +  height: 32px; */
???
t'as commenté ça dans tout le fichier

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/status-item/types.ts
> +    width: string;
peut-être que tu pourrais le typer moins précis, en mode record, en théorie tu peux envoyer n'importe quelles propriétés en style custom:
Record<string, string | number>

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/expandible-actionable-table/style.css
> +  /* background-color: black; */
?

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/brand-tabs/index.js
> +    status: PropTypes.string,
c'est un bon nom ça? c'est réellement un status?

2023-08-08 08:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/index.js
> +EmptyStateBulkInspect.propTypes = {
faudrait pas créer un fichier type associé?

2023-08-08 08:51 UTC, youssefezzahi96 commented
il te manque du coverage sur ce fichier 
src/atom/status-item/index.tsx

2023-08-08 09:35 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/index.js
> +  secondMessage: PropTypes.string.isRequired
un meilleur nommage : 
```suggestion
  mainText: PropTypes.string.isRequired
  subText: PropTypes.string.isRequired
```

2023-08-09 13:06 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/index.js
> +  secondMessage: PropTypes.string.isRequired
je me suis inspiré du composant `EmptySearchResult` (pour le nommage firstMessage, secondMessage)
<img width="995" alt="bulkImg" src="https://github.com/CoorpAcademy/components/assets/94372828/7d5fefcb-217c-4434-9ddf-2f65286c66b2">

2023-08-09 13:32 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/atom/status-item/types.ts
> +    width: string;
oui, sauf qu'on a besoin que du width et height à passer en custom -> limiter le customStyle à width + height.

2023-08-09 13:34 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/brand-tabs/index.js
> +    status: PropTypes.string,
cette prop est passée au component `statusItem` 🤷‍♂️ 
tu as une proposition pour le nommage ?

2023-08-09 15:29 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/index.tsx
> +export default EmptyStateBulkInspect;
pourquoi t’as crée une nouveau composant Empty state bulk inspect alors qu’il y a presque le meme (la seule diff est le css) Empty Search Result

2023-08-09 15:35 UTC, adamska27 requested changes

2023-08-09 15:35 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/status-item/style.css
> +  width: 31.25%;
un peu étrange ces valeurs

2023-08-09 15:38 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/atom/status-item/types.ts
> +  customStyle?: {
il faut que tu utilises  le customstyle dans une fixture, comme ca on vois l'utilité

2023-08-09 15:39 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/brand-tabs/index.js
> +    status: PropTypes.string,
j'ai vu qu'on passait des nombres pour ça que ça me paraissait étrange mais on peut aussi passer des status...

2023-08-09 15:39 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/empty-state-bulk-inspect/index.tsx
> +export default EmptyStateBulkInspect;
j'avoue 🤔

2023-08-09 15:50 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/molecule/brand-tabs/index.js
> +      {!isUndefined(status) ? (
si tu utilise  !isUndefined tu permet l'utilisation de chaines vide, dans ce cas t'aura une bulle vide :/  
```suggestion
      {!status? (
```

2023-08-09 16:16 UTC, youssefezzahi96 commented
je vois que à chaque tu veux utiliser StatusItem, tu le met à l'intérieur  d'un wrapper et tu set le css du wrapper dans le fichier css, y a que les propriétés width et height qui changent d'un wrapper à un autre, une proposition serait de changer le composant de rajouter une couche (le wrapper) de nature dans le composant StatusItem, et donner la main à l'utilisateur de changer le width et le height via les props

2023-08-09 16:24 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-inspect-empty-state.js
> +        },
```suggestion
        customStyle: {
          paddingTop: '12px',
          paddingRight: '24px',
          paddingBottom: '12px',
          paddingLeft: '24px'
        }
```

2023-08-09 16:24 UTC, youssefezzahi96 commented on packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-inspect-empty-state.js
> +        onClick: () => console.log('click')
```suggestion
         customStyle: {
          paddingTop: '12px',
          paddingRight: '24px',
          paddingBottom: '12px',
          paddingLeft: '24px'
        }
```

2023-08-10 12:53 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/brand-tabs/index.js
> +      {!isUndefined(status) ? (
c'est plutôt `status ?`

2023-08-10 15:35 UTC, youssefezzahi96 approved these changes

2023-08-11 09:49 UTC, adamska27 approved these changes

2023-08-11 13:41 UTC, merged