Style card on hover
CoorpAcademy/components pull request #2772
Opened 2023-07-26 16:09 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-07-26 16:47 UTC, antonia2929 commented
@esa-coorp mockup link : [blocking condition](https://www.figma.com/proto/fGRgsFI4CZwpaXLRQNWU5M/Blocking-condition?type=design&node-id=2-2936&t=CuxOCXAb1fkTpLmB-0&scaling=min-zoom&page-id=1%3A2&starting-point-node-id=2%3A2936)

2023-07-31 09:58 UTC, jomaora approved these changes

2023-08-01 08:21 UTC, esa-coorp requested changes

2023-08-01 08:21 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/card/style.css
> +  background-color: #B81400;
est ce ca doit être une couleur de la palette?

2023-08-07 15:20 UTC, EmelineLeduc approved these changes

2023-08-07 15:46 UTC, merged