list items bulk update
CoorpAcademy/components pull request #2777
Opened 2023-08-02 13:45 UTC by youssefezzahi96

[ticket](https://trello.com/c/rvm3EPlw/1323-refacto-composant-pour-bulk-upsert)
Things done : 

- turn Tags status into generic ones, and add missing status (failure)
- update list-item component to support bulk import updates
- update list-items component to support bulk import updates 

results: 

1. list-item: 

- ready for saving:
![image](https://github.com/CoorpAcademy/components/assets/111736786/f2f91815-c762-44f0-98c2-950f7ef42ea7)

- totaly failed:
![image](https://github.com/CoorpAcademy/components/assets/111736786/3c022582-e17b-405c-af00-89bf58e1f2b0)

- partialy failed:
![image](https://github.com/CoorpAcademy/components/assets/111736786/08395a5a-d790-4b68-97c5-faf398076cc2)

- upload in progress:
![image](https://github.com/CoorpAcademy/components/assets/111736786/e64c6977-db42-49a9-a247-1ad45cfc6fa6)

2. list-items: 

- imports pending:
![image](https://github.com/CoorpAcademy/components/assets/111736786/e8a96270-535b-4247-b2e1-533c88e2bb9a)

- imports queued:
![image](https://github.com/CoorpAcademy/components/assets/111736786/c1c2a3bf-80b8-4005-9797-7f4cedc6a81f)

- imports saved: 
![image](https://github.com/CoorpAcademy/components/assets/111736786/aaef5239-77de-45f0-a17f-7da1aac6c4d6)

2023-08-03 12:48 UTC, adamska27 requested changes

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/button-menu/index.tsx
> +    leftJustify = false
leftJustify? c'est pas contradictoire ça? 😅

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/button-menu/index.tsx
> +    [leftJustify]
???

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/button-menu/index.tsx
> +    leftJustify = false
ic pourquoi tu n'as pas utilisé la props existante 'type'?
elle est justement utilisée uniquement pour l'application d'un style custom sur le bouton,
tu pourrais rajouter un type: 'bulk', qui applique ta class CSS,
ça évite de rajouter une props

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/tag/index.js
> +  progress: style.progress
t'aurais pu garder le même ordre pour aider à comprendre le diff 😅  donc:
```
published === success
revised === progress    
archived === warning
draft === failure
 ```

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
>  const ListItem = props => {
```suggestion
const ListItem = ({data, settings, order, 'aria-label': ariaLabel, contentType, isBulkStyle = false}) => {
```

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +  const titleView = (
pas besoin de faire une const de ça vu comment tu l'utilises,
tu peux l'utiliser direct ligne 59

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +    [titleView],
remove
comme ça c'est juste un map

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +        {dataColumnsView}
```suggestion
<div key="titleKey" className={style.title} title={title}>
 {title}
</div>
{dataColumnsView}
```

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +    order !== null && order !== undefined ? (
```suggestion
    !isNil(order)
```

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/style.css
> +
delete

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +  const orderView =
là aussi pas utile de le mettre dans une const
surtout que c'est que 3 lignes

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/style.css
> +  /* min-width: 93px; */
???

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +          <div className={style.see}>
see ?

2023-08-03 12:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-items/style.css
> +  color: var(--font-font-color-tertiary, #9999A8);
???

2023-08-07 08:21 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/button-menu/style.css
> +  color: cm_grey_900;
tu peux remplacer ça:
```
 background-color: cm_grey_100;
 color: cm_grey_900;
```
par:
```
composes: default;
```

2023-08-07 08:21 UTC, adamska27 commented on packages/@coorpacademy-components/src/atom/button-menu/style.css
> +.dangerousLeft {
```
.dangerousLeft {
  composes: dangerous;
  justify-content: flex-start;
}
```

2023-08-07 08:21 UTC, adamska27 commented on packages/@coorpacademy-components/src/organism/list-item/index.js
> +    [
pk tu t'embête à concat ça?

2023-08-08 08:17 UTC, adamska27 approved these changes

2023-08-08 12:29 UTC, GhaziCoorpacademy approved these changes

2023-08-09 08:32 UTC, merged