[massive-battle] add option xlsx content in drag and drop
CoorpAcademy/components pull request #2779
Opened 2023-08-07 14:08 UTC by EmelineLeduc

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2023-08-09 12:40 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modify the DragAndDrop component to add the preview of an xlsx file](https://trello.com/c/skcMggKX/3141-modify-the-draganddrop-component-to-add-the-preview-of-an-xlsx-file)

2023-08-09 15:20 UTC, EmelineLeduc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modify the DragAndDrop component to add the preview of an xlsx file](https://trello.com/c/skcMggKX/3141-modify-the-draganddrop-component-to-add-the-preview-of-an-xlsx-file)

2023-08-16 10:46 UTC, jomaora commented
@DjamelSoualmi this PR modify components used only on CM, so it should not have any impact on RGAA on the mooc. This is the graph of components and its dependences

![Capture d’écran 2023-08-16 à 12 46 18](https://github.com/CoorpAcademy/components/assets/7602475/04c2477f-829c-46bd-a29d-3229d328311d)

2023-08-16 11:47 UTC, DjamelSoualmi requested changes

2023-08-16 11:47 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
> +  color: #C5C5C9;
la couleur n'existe pas dans colors.css ? il faut la rajouter

2023-08-16 11:47 UTC, DjamelSoualmi commented on packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
> +  background-color: #E5E5E5;
IMD

2023-08-16 13:04 UTC, jomaora approved these changes

2023-08-16 13:07 UTC, DjamelSoualmi approved these changes

2023-08-16 13:11 UTC, antonia2929 approved these changes

2023-08-16 14:20 UTC, merged