Fix CMPopinCard style
CoorpAcademy/components pull request #2811
Opened 2023-10-05 14:00 UTC by antonia2929

Trello ticket : 

**Detailed purpose of the PR**
- Add unit test for handleClose function
- Update popin width styles
![Capture d’écran 2023-10-09 à 16 41 57](https://github.com/CoorpAcademy/components/assets/113359769/d6cd5564-4e00-40af-944e-d5d225226482)

- Add closePopin function to close the popin when a lick is outside the component
![Kapture 2023-10-09 at 16 44 06](https://github.com/CoorpAcademy/components/assets/113359769/307d05ac-c1b8-49a2-8623-2cc7e27388bf)

**Result and observation**

**Testing Strategy**
- [ ] Already covered by tests
- [x] Manual testing
- [x] Unit testing

2023-10-09 14:58 UTC, EmelineLeduc requested changes

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +// import React from 'react';
Line 1 should be deleted

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +// const stopPropagation = e => e.stopPropagation();
Clean code (line 33-34)

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +  // const handleCloseButton = useCallback(
Clean code

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/cm-popin/test/on-close.js
> +import test from 'ava';
Could you migrate the code to TS ?

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/molecule/select-multiple/index.js
> +      console.log('closeHandle');
Clean code : delete the console.log

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/organism/mooc-header/index.js
> +        // eslint-disable-next-line no-console
Clean code : delete the console.log

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/template/common/dashboard/style.css
> +/*
clean code

2023-10-09 14:58 UTC, EmelineLeduc commented on packages/@coorpacademy-components/src/template/common/search-page/style.css
> +/* .hidden {
clean code

2023-10-09 15:16 UTC, EmelineLeduc approved these changes

2023-10-09 15:33 UTC, silouone approved these changes

2023-10-09 15:59 UTC, esa-coorp requested changes

2023-10-09 15:59 UTC, esa-coorp commented on packages/@coorpacademy-components/src/molecule/cm-popin/style.css
> +}
je préfère avoir un className et par de tag générique (ici `button`). Risque d'effet de bord.

2023-10-10 08:03 UTC, esa-coorp approved these changes

2023-10-10 12:28 UTC, silouone approved these changes

2023-10-10 12:30 UTC, merged