add DELETE bulk popin icons & fixtures
CoorpAcademy/components pull request #2816
Opened 2023-11-13 10:16 UTC by youssefezzahi96

[ticket](https://trello.com/c/Ma9ARIG0/1382-integration-cm-page-inspect) 
The purpose is to add DELETE bulk popin icons & fixtures.
Result: 
![Pasted Graphic 15](https://github.com/CoorpAcademy/components/assets/111736786/a0af75f6-b9e3-46a9-aa01-4275947eeb00)

2023-11-13 14:25 UTC, GhaziCoorpacademy commented on packages/@coorpacademy-components/src/molecule/cm-popin/index.js
> +                  icon={secondButton.icon}
t'as pas mis à jour les proptypes

2023-11-13 14:45 UTC, GhaziCoorpacademy approved these changes

2023-11-14 15:41 UTC, silouone approved these changes

2023-11-14 15:41 UTC, silouone approved these changes

2023-11-14 15:47 UTC, adamska27 approved these changes

2023-11-14 15:48 UTC, silouone requested changes
rename les svg please c'estnimp la impossib le de retrouver. frame-218 & delete 1. Donc l'icon et le cowboy la on le renomme mdr

2023-11-14 17:16 UTC, silouone approved these changes

2023-11-14 23:58 UTC, merged