[WIP] create learning profile banner
CoorpAcademy/components pull request #2830
Opened 2024-03-08 11:49 UTC by youssefezzahi96

[ticket](https://go1web.atlassian.net/jira/software/projects/CLXP/boards/626?selectedIssue=CLXP-2)
purpose: 
is to create learning profile banner component.
things done: 
component & test
to be discussed/checked: 
uploading images on S3 as all other banners, or change the ways things are done (local images)
Visual Results (story book):
![image](https://github.com/CoorpAcademy/components/assets/111736786/e04e633d-b8a0-4c5f-9fa0-27c1a609817c)

2024-03-08 15:24 UTC, wernerdurand approved these changes
Nickel 👌

2024-03-08 15:32 UTC, silouone commented on packages/@coorpacademy-components/src/molecule/dashboard/learning-profile-banner/index.js
> +              src="https://static.coorpacademy.com/site/notebook.png"
quand tu m'en parlais je pensais c'etait cote FE que ca allait etre feeder . donc en effet jrejoins adrien, pas ouf aha. 

si tu pouvais au moins le déclarer ds des constantes

2024-03-12 11:27 UTC, AdrieanKhisbe requested changes
Few feedbacks

2024-03-12 11:27 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/dashboard/learning-profile-banner/index.js
> +  const TARGET_IMG_URL = 'https://static.coorpacademy.com/assets/images/section-item-dart.png';
you can extract the two const out of the LearningProfileBanner

2024-03-12 11:27 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/dashboard/learning-profile-banner/index.js
> +            <img className={style.image} src={BOOK_IMG_URL} alt="Note book image" />
```suggestion
            <img className={style.image} src={BOOK_IMG_URL} alt="Notebook image" />
```

2024-03-12 11:27 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/dashboard/learning-profile-banner/style.css
> +  background-image: url(https://static.coorpacademy.com/site/startBattleBackground.png);
use the generic path I created

2024-03-13 10:43 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/dashboard/learning-profile-banner/index.js
> +import React from 'react';
👍

2024-03-13 10:44 UTC, AdrieanKhisbe approved these changes

2024-03-14 11:27 UTC, silouone approved these changes

2024-03-15 13:52 UTC, merged