CLXP-192 Details page UX improvements
CoorpAcademy/components pull request #2901
Opened 2024-11-22 04:14 UTC by HuyIT9898

**Detailed purpose of the PR**
 Details page UX improvements

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2024-11-26 16:17 UTC, AdrieanKhisbe approved these changes

2024-11-26 16:17 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/certification-card/index.js
>          <div className={style.titleWrapper}>
💭  Maybe we could add a dynamic data name:  `certification-$ref` or `certification-$name`

2024-11-26 16:17 UTC, AdrieanKhisbe commented on packages/@coorpacademy-components/src/molecule/progress-bar/index.js
> +      data-name="progress-bar-wrapper"
👍

2024-11-29 14:48 UTC, adamska27 requested changes

2024-11-29 14:48 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/playlist-detail/index.js
>      onBackClick,
we can do a check on this to handle disabled or not the back button, something like that:

````
 <ButtonLinkIcon
          faIcon="arrow-left"
          data-name="back-button"
          aria-label="Back"
          onClick={onBackClick}
          className={style.backButton}
          tooltipPlacement="right"
         disabled={isNil(onBackClick)}
        />

````

2024-12-02 09:23 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/playlist-detail/index.js
>      onBackClick,
ah Huy, the product prefer to hide the button instead of disbaled it

2024-12-02 09:24 UTC, adamska27 requested changes

2024-12-02 09:24 UTC, adamska27 commented on packages/@coorpacademy-components/src/template/certification-detail/index.js
> +          disabled={isNull(onBackClick)}
better use isNil to apply if value is nul or undefined

2024-12-02 14:34 UTC, adamska27 approved these changes

2024-12-03 06:20 UTC, merged