CLXP-195 remove content completed and courses
CoorpAcademy/components pull request #2905
Opened 2024-12-27 14:58 UTC by antonia2929

**Detailed purpose of the PR**

**Result and observation**

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra lib ?**
      If checked, Which extra lib did you add ? (name, purpose, link ...).

**Testing Strategy**

- [ ] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

2025-01-02 11:16 UTC, adamska27 requested changes

2025-01-02 11:16 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
> +  const {score, content, questionsToReview = 0} = metrics;
update the propTypes too

2025-01-02 11:17 UTC, adamska27 commented
need to update myLearning component too (src/template/my-learning/index.js)

2025-01-03 10:35 UTC, adamska27 requested changes

2025-01-03 10:35 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
>            {questionsToReview ? (
il sert plus à rien ce check là, non?

2025-01-03 10:35 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/default.js
> +    questionsToReview: 25
il manque le score dans toutes les fixtures learner-skill-card

2025-01-03 10:35 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
> +        <ProgressBar />
je sais pas pourquoi on re-construit une progressbar ici, on a un composant exprès, essaye de voir pour l'utiliser et clean l'autre

2025-01-03 13:28 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/no-skill-courses.js
> -import {defaultProps} from './default';
peut être garder celui ci, 
le renommer en "no-content",
même si je vois pas trop le scénario mais on a une condition si content => display progressBar,
donc ce serait une fixture pour tester ce use case qui n'affiche pas la progressBar

2025-01-03 13:28 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/no-skill-courses.js
> -      contentCompleted: 50
à retirer

2025-01-03 15:01 UTC, antonia2929 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/no-skill-courses.js
> -import {defaultProps} from './default';
@adamska27 en vrai cette use case là on l'a déjà c'est la fixture "no skill courses and questions"
![Capture d’écran 2025-01-03 à 16 00 13](https://github.com/user-attachments/assets/0752d8e3-f44f-4730-b9eb-f32b12f3a71c)

2025-01-03 15:02 UTC, antonia2929 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/no-skill-courses.js
> -import {defaultProps} from './default';
mais vu qu'il n'y a plus de skill courses je peux la renommer en "no content"

2025-01-03 15:05 UTC, adamska27 commented on packages/@coorpacademy-components/src/molecule/learner-skill-card/test/fixtures/no-skill-courses.js
> -import {defaultProps} from './default';
ah oui, on a les 2 sur celui là donc ça va c'et bon pas la peine d'en rajouter 👍

2025-01-03 15:09 UTC, adamska27 approved these changes

2025-01-06 09:15 UTC, merged